### ISSUE TITLE
[Bug]tabLabel

### ISSUE THREAD

**Issue by Richard-Cao** [skv-headless/react-native-scrollable-tab-view#142]
When `let a = complaint.orderList.completed.length;` , and `tabLabel={'已完成  ' + a}`, childView not render:
`<ListView
						tabLabel={'已完成  ' + a}
						dataSource={completedSource}
						renderRow={this.renderCompletedOrder}
						style={styles.listView}`

**Comment by Richard-Cao** [comment]
@brentvatne

**Comment by skv-headless** [comment]
If you remove  ```+ a``` it works again? It would be great if you reproduce this bug in the example https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabsExample.js and make a pull request.

**Comment by Richard-Cao** [comment]
@skv-headless remove `+a` it works again. I will reproduce this bug in this example soon.

**Comment by Richard-Cao** [comment]
@skv-headless this `a` is http request response list length. This bug only display on first `Reload JS`

**Comment by Richard-Cao** [comment]
@skv-headless and my project use `redux`, I do not know reason, how to reproduce

**Comment by skv-headless** [comment]
check after #148
