### ISSUE TITLE
[Bug]this.scrollView.setPage

### ISSUE THREAD

**Issue by Richard-Cao** [skv-headless/react-native-scrollable-tab-view#143]
In source code I see:
```
if(Platform.OS === 'ios') {
      var offset = pageNumber * this.state.container.width;
      this.scrollView.scrollTo(0, offset);
    } else {
      this.scrollView.setPage(pageNumber);
    }
```
But `TaskQueue: Error with task : Cannot read property 'setPage' of null`
In [ScrollView](https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js) have not a function like `setPage`
@brentvatne

**Comment by skv-headless** [comment]
Hi. What version of react native do you use? For android ```scrollView``` is ```ViewPagerAndroid```.

**Comment by Richard-Cao** [comment]
@skv-headless 0.18

**Comment by skv-headless** [comment]
@Richard-Cao How can I reproduce it? is it ios or android?

**Comment by Richard-Cao** [comment]
@skv-headless android

**Comment by naeemulhaque** [comment]
@skv-headless This is hit on iOS as well (0.3.5, 0.3.6). Cannot read property scrollTo of null.
```
  goToPage(pageNumber) {
    this.props.onChangeTab({ i: pageNumber, ref: this._children()[pageNumber], });

    if (Platform.OS === 'ios') {
      const offset = pageNumber * this.state.containerWidth;
      this.scrollView.scrollTo(0, offset);
```

**Comment by naeemulhaque** [comment]
I've a collection of pages (each page is using 1-2 instances of react-native-scrollable-tab-view). If I traverse the collection back and forth, this crash is hit. Usually after 10-15 pages.

**Comment by skv-headless** [comment]
I catch it when page is loading while trying to swipe another tab.

**Comment by skv-headless** [comment]
Should be fixed. Reopen if you still can reproduce.
