### ISSUE TITLE
Consider changing the `key` for dynamic children

### ISSUE THREAD

**Issue by grabbou** [skv-headless/react-native-scrollable-tab-view#148]
Hey,

When dynamically rendering children of ScrollableTabView and having a dynamic tabLabel that changes over time, I am experiencing a weird behaviour of tab's content disappearing (the render() methods of sub-components within the tab's content are called).

It happens with the below pseudo-code:

```js
<ScrollableTabView>
    {tabs.map((tab, i) => <ScrollView key={i} tabLabel={tab.label}>{tab.component}</ScrollView>)}
</ScrollableTabView>
```

Where tab.label changes as user types a new keyword to the textField. It can be e.g. "Artists", or "Artists (24)" indicating the number of results.

I think that's the cause because we are building up a key for dynamic children using the tabLabel passed, which because the tabLabel changes itself, makes the key to be fully dynamic also.

As a temporary workaround, I've built up a custom HOC for `DefaultTabBar`, that, from an integer tabLabel (0, 1, 2, 3, 4...) etc., can access tabs array from the snippet above and just get the proper, dynamic `label`. Tabs array is passed as a property to it as well, so that it nicely updates when dynamic labels change.

It works, although I would love this issue to be discussed to see if it's just me having issues with understanding how React references dynamic children.

Anyway - if we could probably reuse the `key` if it's present on children, that would be cool. That is, instead of this line: https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/index.js#L134 we could have
```js
const key = (child.props.key || child.props.tabLabel) + '_' + idx
```
I think that would've solved it as well.

**Comment by skv-headless** [comment]
Use array index is not a good idea.
```const key = child.props.key || child.props.tabLabel```
Need to check case with same ```tabLabel```s
@grabbou thanks for great filled issue :+1:

**Comment by skv-headless** [comment]
We can't use ```tabLabel``` as a key it can be the same, so ```child.props.tabLabel + '_' + idx``` but we should provide a method to users to set right key (if they know what are they doing).
```const key = child.props.key || `${child.props.tabLabel}_${idx}` ``` seems to be the best solution. @grabbou will you submit a PR?

**Comment by grabbou** [comment]
Yeah, sure. I'll get that submitted in the morning, thanks :)

**Comment by hey99xx** [comment]
@skv-headless I'm curious why using array index alone isn't a good idea. What is wrong with for example `TAB${idx}` ?

**Comment by Richard-Cao** [comment]
#194

**Comment by Richard-Cao** [comment]
this #194

**Comment by Richard-Cao** [comment]
look this [ViewPagerAndroid returns empty view when new source data added](https://github.com/facebook/react-native/issues/4775)

**Comment by Richard-Cao** [comment]
this issue [ViewPagerAndroid returns empty view when new source data added](https://github.com/facebook/react-native/issues/4775) had solution.
@skv-headless

**Comment by Richard-Cao** [comment]
@brentvatne

**Comment by skv-headless** [comment]
Guys, please check this in master
