### ISSUE TITLE
Orientation iOS - landscape bug

### ISSUE THREAD

**Issue by hey99xx** [skv-headless/react-native-scrollable-tab-view#154]
Hi I've only tried to reproduce this bug on IOS . I've created a sample app with `react-native init` (version , installed this package via npm, and put the sample code inside FacebookTabsExample.js 

Relevent part from package.json

    "dependencies": {
        "react-native": "^0.19.0",
        "react-native-scrollable-tab-view": "^0.3.5"
      }

The code I used

    var SimpleExample = React.createClass({
        render() {
            return (
                <ScrollableTabView style={{marginTop: 20}}>
                       <Text tabLabel='Tab #1'>My</Text>
                       <Text tabLabel='Tab #2'>favorite</Text>
                       <Text tabLabel='Tab #3'>project</Text>
                </ScrollableTabView>
            )
        }
    });`

On the simulator, if you go to tab#3 and then rotate the device, the scroll view goes somewhere in between tab#1 and tab#2 . Once you touch again, you continue as nothing happened . Ive tried to debug what is going on, I think what is going on is handleLayout is called - > calls goToPage -> calls scrollTo -> but the final step onMomentumScrollEnd gets called very prematurely.
![screen shot 2016-02-10 at 1 58 38 pm](https://cloud.githubusercontent.com/assets/17169137/12964757/c35a1096-d006-11e5-811b-78171635b63c.png)

**Comment by skv-headless** [comment]
I confirm.

**Comment by skv-headless** [comment]
fixed in master. I encourage you to try.
