### ISSUE TITLE
get this Warning: ScrollView doesn't take rejection well - scrolls anyway

### ISSUE THREAD

**Issue by tofrookie** [skv-headless/react-native-scrollable-tab-view#185]
i have too ScrollableTabView
one inside another,
outside one set props locked={true}
when i scrolled, it will give a warning:'Warning: ScrollView doesn't take rejection well - scrolls anyway'

**Comment by yixiaops** [comment]
i have the warning too!!!!!

**Comment by tofrookie** [comment]
now i have a listview inside ScrollableTabView
also waring.........

**Comment by uyson** [comment]
+1

**Comment by zhouhesheng** [comment]
three listview in ScrollableTabView(0.4.0), with react-native 0.21, warning too.

**Comment by skv-headless** [comment]
https://github.com/facebook/react-native/issues/1501

**Comment by skv-headless** [comment]
It should be fixed. Reopen if not
