### ISSUE TITLE
[Bug]Change Tab View Children Dynamic Not Display

### ISSUE THREAD

**Issue by Richard-Cao** [skv-headless/react-native-scrollable-tab-view#194]
@brentvatne 
```
lists.push(
        <View
          key={typeId}
          tabLabel={CATEGORIES[typeId]}
          style={{flex: 1}}
        >
          {this.renderContent(this.state.dataSource.cloneWithRows(read.articleList[typeId] == undefined ? [] : read.articleList[typeId]), typeId)}
        </View>);
```
And
```
<ScrollableTabView
            renderTabBar={() => <ReadingTabBar />}
            tabBarBackgroundColor="#fcfcfc"
            tabBarUnderlineColor="#3e9ce9"
            tabBarActiveTextColor="#3e9ce9"
            tabBarInactiveTextColor="#aaaaaa"
          >
          {lists}
          </ScrollableTabView>
```
when I change `lists` **dynamic** and render, `lists` not display

**Comment by skv-headless** [comment]
Is ```lists``` in a state? Could you please show how do you change ```lists```?

**Comment by Richard-Cao** [comment]
@skv-headless when 'render', 'lists' will change. I used 'redux' to change state.

**Comment by starInEcust** [comment]
+1 
I think it's a bug of ViewPager

`let pageComponentArray =[
			[<Theme key="Theme" />, <Popular key="Popular" />],
			[<EmojiView key="EmojiView" />, <StickerView key="StickerView" />, <EmojiArtView key="EmojiArtView" />, <EmotionView key="EmotionView"/>]
		];`
I pushed the components in a Array and change index.The it cause a bug that just like #https://github.com/facebook/react-native/issues/4775.

I tried to use brentvatne's method: "change the key every time you update the data source"
`getPageComponent() {
		let timeStamp = new Date().getTime();
		return [
			[<Theme key={`Theme_${timeStamp}`} />, <Popular key={`Popular_${timeStamp}`} />],
			[<EmojiView key={`EmojiView_${timeStamp}`} />, <StickerView key={`StickerView_${timeStamp}`} />, <EmojiArtView key={`EmojiArtView_${timeStamp}`} />, <EmotionView key={`EmotionView_${timeStamp}`} />]
		];
	}`
but it doesn't seem to work.

so what's the best way to solve this problem?

**Comment by Richard-Cao** [comment]
@brentvatne

**Comment by Richard-Cao** [comment]
look this [ViewPagerAndroid returns empty view when new source data added](https://github.com/facebook/react-native/issues/4775)

**Comment by Richard-Cao** [comment]
this issue [ViewPagerAndroid returns empty view when new source data added](https://github.com/facebook/react-native/issues/4775) had solution.
@skv-headless

**Comment by Richard-Cao** [comment]
@brentvatne
