### ISSUE TITLE
ScrollableTabBar getting slower over time

### ISSUE THREAD

**Issue by LandDragoon** [skv-headless/react-native-scrollable-tab-view#206]
When I use the ScrollableTabBar and move around through the different views a couple of times, the tabbar itself will get slower and slower (while the actual switching is still quick). Result of this is that after some time, you'll switch views by swiping and the tabbar will change tabs very slowly.

This behavior doesn't occur when using the DefaultTabBar.

**Comment by faceyspacey** [comment]
yea, performance can get pretty bad. I'm not sure what it is. I'm glad to know you're thinking it's just the scrollable tab bar--if that's the case, I'm gonna switch back to the non-scrollable one. 

...I feel like possibly too much animation is happening in javascript rather than natively.

**Comment by Pranjal5** [comment]
Even I am facing the same problem, for very simple app the javascript fps fall from 60 to 30 in Android where as for iOS fps is quite stable(>55). I checked the performance using Perf Monitor and even used the log timings to observe this difference.

**Comment by skv-headless** [comment]
should be fixed in master please check this.

**Comment by LandDragoon** [comment]
Seems to work properly for me now.

**Comment by saudpunjwani101** [comment]
@skv-headless are u referring to react-native-scrollable-tab-view-master? using this one makes the scroll between tabs feel slower. The animation isn't that smooth as compare to react-native-scrollable-tab-view, even when the debugging mode is off. But using without master makes the scroll slower each time a new screen is pushed. Is there a better solution to optimise this?
