### ISSUE TITLE
Warning: ScrollView doesn't take rejection well - scrolls anyway

### ISSUE THREAD

**Issue by donghanji** [skv-headless/react-native-scrollable-tab-view#211]
When used the react-native-scrollable-tab-view,use nested,like this:

<pre>

class TabView extends Component {
  render() {
    var self=this;
    return (
      &lt;ScrollableTabView
        tabBarPosition={'bottom'}
      &gt;
        &lt;View style={styles.container} tabLabel="View 1"&gt;
          &lt;Text style={styles.welcome}&gt;
            Welcome to React Native 1!
          &lt;/Text&gt;
        &lt;/View&gt;
        &lt;ScrollableTabView
          tabLabel="View 2"
          &gt;
          &lt;View style={styles.container} tabLabel="View 2.1"&gt;
            &lt;Text style={styles.welcome}&gt;
              Welcome to React Native 2.1!
            &lt;/Text&gt;
          &lt;/View&gt;
          &lt;View style={styles.container} tabLabel="View 2.2"&gt;
            &lt;Text style={styles.welcome}&gt;
              Welcome to React Native 2.2!
            &lt;/Text&gt;
          &lt;/View&gt;
        &lt;/ScrollableTabView&gt;
        &lt;View style={styles.container} tabLabel="View 3"&gt;
          &lt;Text style={styles.welcome}&gt;
            Welcome to React Native 3!
          &lt;/Text&gt;
        &lt;/View&gt;
      &lt;/ScrollableTabView&gt;
    );
  }
}

</pre>

Will get the warning message:ScrollView doesn't take rejection well - scrolls anyway

Debug in Chrome,this is throw with "ScrollResponder.js",its "scrollResponderHandleResponderReject" method.This is its comments and the "scrollResponderHandleResponderReject" method:

<pre>
  /**
   * Invoke this from an `onResponderReject` event.
   *
   * Some other element is not yielding its role as responder. Normally, we'd
   * just disable the `UIScrollView`, but a touch has already began on it, the
   * `UIScrollView` will not accept being disabled after that. The easiest
   * solution for now is to accept the limitation of disallowing this
   * altogether. To improve this, find a way to disable the `UIScrollView` after
   * a touch has already started.
   */
  scrollResponderHandleResponderReject: function() {
    warning(false, "ScrollView doesn't take rejection well - scrolls anyway");
  },
</pre>

It said,the solution for now is to accept the limitation of disallow this altogether.

Is there an other better way to solve this problem here?

**Comment by skv-headless** [comment]
#187

**Comment by donghanji** [comment]
Others have encountered this issue,
see here,https://github.com/facebook/react-native/issues/1501

**Comment by skv-headless** [comment]
https://github.com/facebook/react-native/commit/5f77f15bac82c7a13605fdbd1ee7e2823c1821bf

**Comment by skv-headless** [comment]
I think it is fixed
