### ISSUE TITLE
Do not accepting ScrollView in second component

### ISSUE THREAD

**Issue by edelworksgithub** [skv-headless/react-native-scrollable-tab-view#220]
`<ScrollableTabView tabBarUnderlineColor="#ED9A11" tabBarActiveTextColor="#ED9A11" tabBarInActiveTextColor="#000">
		<Projects tabLabel="Projects" navigator={this.props.navigator} token={this.props.token} />
		<KPIMetrics tabLabel="KPI Metrics" navigator={this.props.navigator} token={this.props.token} />
	  </ScrollableTabView>`
I am displaying listview in both components
So I need to put ScrollView(with RefreshControl) in first component and it worked..
but when putting the same in second one gives me error..
![screenshot_2016-03-26-20-48-52_com tasksandmetricsmanagement](https://cloud.githubusercontent.com/assets/8638256/14117341/ddcac60c-f601-11e5-8478-deabaa89419d.png)

**Comment by skv-headless** [comment]
Probably problem in your component. Anyway I can't help you without ```Projects``` and ```KPIMetrics``` components.

**Comment by skv-headless** [comment]
reopen if you still think that problem in ```react-native-scrollable-tab-view```
