### ISSUE TITLE
Use StaticContainer to prevent re-renders of hidden pages

### ISSUE THREAD

**Issue by cancan101** [skv-headless/react-native-scrollable-tab-view#232]

**Comment by skv-headless** [comment]
I understand what is ```StaticContainer``` but I have no idea how you want to use it inside ```react-native-scrollable-tab-view```.

**Comment by cancan101** [comment]
I would wrap each child with `StaticContainer` and set `shouldUpdate` based on whether the tab is being shown (either tab is totally shown or transition to/from that tab).

See: https://github.com/facebook/react-native/blob/648aaf440b70780e3ca35314760cd6c5e69ea8a0/Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js#L104-L111

**Comment by skv-headless** [comment]
I'm afraid that updates will happen after tab would be selected. It would be not cool.
In that case such behaviour should optional.

**Comment by cancan101** [comment]
What do you mean?

**Comment by code-smith** [comment]
Check this
#303
https://github.com/code-smith/react-native-scrollable-tab-view
