### ISSUE TITLE
Tab label is off center when using more than 1 word

### ISSUE THREAD

**Issue by devbriguy** [skv-headless/react-native-scrollable-tab-view#243]
![screenshot 2016-04-18 12 03 00](https://cloud.githubusercontent.com/assets/16087561/14610886/a3575880-055d-11e6-8daa-4532faa2f680.png)

**Comment by skv-headless** [comment]
It works for me https://github.com/brentvatne/react-native-scrollable-tab-view/wiki/Basic-usage. What tabBar do you use? Could you share your code?

**Comment by devbriguy** [comment]
@skv-headless 

Here you go: 
`     <ScrollableTabView style={styles.container} initialPage={1} tabBarTextStyle={styles.tabText}  tabBarBackgroundColor='#f2f2f2' tabBarActiveTextColor='black' tabBarUnderlineColor={Constants.MAIN_GREEN_COLOR}>
        <EventView tabLabel='Events' navigator={this.props.navigator} />
        <CareTeamView tabLabel='Care Team' navigator={this.props.navigator} />
        <SharedView tabLabel='Shared Files' navigator={this.props.navigator} />
      </ScrollableTabView > `

And the styles ...
`var styles = StyleSheet.create({
  container: {
    marginTop: 65,
  },
  tabText: {
    fontSize: 16,
    fontFamily: Constants.MAIN_FONT_MEDIUM,
    color: Constants.MAIN_GRAY_COLOR,
    textAlign: 'center',
  },
});`

**Comment by stereoki** [comment]
submitted fix here https://github.com/skv-headless/react-native-scrollable-tab-view/pull/275

**Comment by devbriguy** [comment]
@stereoki confirmed
