### ISSUE TITLE
onChangeTab Example

### ISSUE THREAD

**Issue by coreyphillips** [skv-headless/react-native-scrollable-tab-view#249]
Are there any working examples of how to use onChangeTab?

**Comment by skv-headless** [comment]
Hi I think I use it. Ask me if you have a question otherwise it would be great addition.

**Comment by skv-headless** [comment]
I think most interesting ```onChangeTab``` usage is lazy tab loading. Example would be awesome.

**Comment by jdrydn** [comment]
I can't seem to call any methods of my components using this `onChangeTab` function, similar to:

```js
<ScrollableTabView ... onChangeTab={({ i, ref }) => ref.componentEntersView()} ... >...</...>
```
with
```js
module.exports = React.createClass({
  componentEntersView() {
    console.log('Yay we triggered this when the tab was switched to us!');
  },
  render() {
    // Does some rendering
  }
});
```

And I can't find any examples in this repo? A quick search "_onChangeTab_" shows the README & the main file, and nothing else :cry:

Is there something blindingly obvious that I'm not doing?

**Comment by code-smith** [comment]
@skv-headless Any examples? The problem i encountered is ref which is passed isn't an object of that child component( its not the ref which react offers) , its a component class itself and i was not able to manipulate state to do lazy loading.
I think i need some help here , please respond.

**Comment by code-smith** [comment]
@skv-headless I had to give refs to my tabs(children) and then make calls using those refs.

each tab was given a ref:
 <tab ref={(child)=> {this.children[i] = child}}
/>
this.children is an array of refs to each children.
Use the onChangeTab as follows,
onChangeTab={ ({ i, ref })=> {this.children[i].callsomeMethods} }
so basically the ref passed isn't of much help only the index is useful to point to the child .

**Comment by skv-headless** [comment]
Sorry for delay. I've made an example #348.

**Comment by skv-headless** [comment]
Let me now if it doesn't work for you
