### ISSUE TITLE
iPhone camera app animation effect

### ISSUE THREAD

**Issue by L-Jovi** [skv-headless/react-native-scrollable-tab-view#251]
hey, it's not a issue and I just want to know,

how should I make this smart __react-native-scrollable-tab-view__ animate like iPhone __camera__ app's animation behaviour,

I mean that tab scroll delay a bit, and change to next tab.

![camera-app-animation](https://cloud.githubusercontent.com/assets/7262199/14973901/c8e43be4-1120-11e6-9d83-74d62620c5a4.jpg)

thanks for your time :)

**Comment by skv-headless** [comment]
Just first thoughts:
All children are blurred (for ex https://github.com/react-native-fellowship/react-native-blur). When scroll started blur current view. When tab selected render content of tab(without blur effect). Don't promise that it would look the same way.

**Comment by L-Jovi** [comment]
thanks for your reply!  I'll try my way :)

and how about the scroll behaviour, I can't express it well, tab scroll just like .. mechanical movement,  I mean it not scrolling at moment and not be recognized your gesture.

maybe I have no idea to implement it now.

**Comment by skv-headless** [comment]
You probably don't need ```react-native-scrollable-tab-view``` at all. https://facebook.github.io/react-native/docs/panresponder.html sends an event where you can find ```dx``` which is distance of your finger movement since beginning of the gesture. After certain number show blur effect and change scene.

**Comment by L-Jovi** [comment]
thanks for your patience :)
