### ISSUE TITLE
ScrollableTabView does not play well with ToolbarAndroid

### ISSUE THREAD

**Issue by tvalentius** [skv-headless/react-native-scrollable-tab-view#252]
Hi i am trying to achieve the scrollable tab under a Toolbar with React Native like Whatsapp

![screen shot 2016-05-03 at 11 39 44 am](https://cloud.githubusercontent.com/assets/890146/14974162/b79dbfe2-1123-11e6-98c8-e84cba44b84e.png)

here's the snippet of my code 
`<View style={{flex:1}}>
          
          <ToolbarAndroid
          title="Movie Viewer"
          style={styles.toolbar}
        />
          
        <ScrollableTabView
            tabBarActiveTextColor="#FFFFFF"
            tabBarUnderlineColor="#FFFFFF"
            tabBarBackgroundColor="#f7913d"
            tabBarTextStyle={[TYPO.paperFontButton,{fontSize:15}]}>

            <ScrollView  tabLabel="MOVIE">
              <ListView
                    dataSource={this.state.dataSource}
                    renderRow={this.renderMovie}
                    style={styles.listView}
                  />
            </ScrollView>
            <ScrollView tabLabel="SCHEDULE" style={styles.tabView}>
              <ListView
                    dataSource={this.state.dataSource}
                    renderRow={this.renderSchedule}
                    style={styles.listView}
                  />
            </ScrollView>
            <ScrollView tabLabel="THEATER">
              <Card>
                  <Text>theater tab</Text>
              </Card>
            </ScrollView>
            <ScrollView tabLabel="UPCOMING">
              <Card>
                <Text>upcoming tab</Text>
              </Card>
            </ScrollView>
        </ScrollableTabView>
      </View>`

At first it seems to work, but the Tab other than the first one seems missing.

Please let me know if there is a better approach to achieve this.

Cheers

**Comment by skv-headless** [comment]
If you remove ```ToolbarAndroid``` everything work?
Code seems good. Maybe you can create example project on github to reproduce this issue?

**Comment by tvalentius** [comment]
If i remove it, everything works just fine.

I just notice that i can also reproduce the issue/bug by adding a View or Text component before ScrollableTabView

**Comment by skv-headless** [comment]
I've just tried to add ```<View/>``` before ```ScrollableTabView``` everything works. Maybe something with styles? If you can reproduce on one of the examples https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabsExample.js I can take a look

**Comment by tvalentius** [comment]
Found the issue and i think it's not related with ScrollableTabView .

Thanks for helping @skv-headless  :D

**Comment by Albertao** [comment]
I'm facing this same problem too,can u plz tell me how to fix it?thx~

**Comment by skv-headless** [comment]
@tvalentius can you help @Albertao ?

**Comment by Albertao** [comment]
@skv-headless I've found the answer, and the solution is add the style flex:1 to your <View>tag, then the problem will be solved,thanks~
