### ISSUE TITLE
Hide bar above icon TabView

### ISSUE THREAD

**Issue by MayeuldP** [skv-headless/react-native-scrollable-tab-view#254]
Hello

the module work well, I come here more for a visual problem. 

I wanted to know how can I hide the bar above the icon ? 

I have the ScrollTabView icon of this example : 

![demo-fb](https://cloud.githubusercontent.com/assets/15033774/14987438/429b1a96-1150-11e6-9d1b-ae6ae9e2bed9.gif)

And the ScrollTabView bar above of this example... : 

![demo](https://cloud.githubusercontent.com/assets/15033774/14987418/33f9525a-1150-11e6-9173-bf5011e580da.gif)

How can I just have the icon like the first example ? I hope that you understood the problem.... :/

**Comment by MayeuldP** [comment]
Got it ! I just have to disable the color of `tabUnderlineStyle` in facebookTabBar.js so that we can't see the underline bar... It work great... But in fact there still little bug. When I swipe, sometime, the icon's color is flashing one time. Don't know why... is it the node_module which is not very responsive or me who have a problem ? @skv-headless

**Comment by skv-headless** [comment]
Not sure what a you talking about. Try to update ```react-native-scrollable-tab-view``` or probably it is a feature not a bug 😄 .

**Comment by MayeuldP** [comment]
I really have to read more ^^ ! It was this two lines : 

`this.setAnimationValue({ value: this.props.activeTab, });`
  `this._listener = this.props.scrollValue.addListener(this.setAnimationValue);` 
Just have to comment them in FacebookTabBar.Js

So yes it was a feature (so which doesn't work very good)... thank's ! It works great now .
