### ISSUE TITLE
Error with webpack

### ISSUE THREAD

**Issue by weidaxu1988** [skv-headless/react-native-scrollable-tab-view#255]
I just webpack, and I got the following error

ERROR in ./~/react-native-scrollable-tab-view/DefaultTabBar.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./Button in /Users/dawei/workspace/DingDong/node_modules/react-native-scrollable-tab-view
 @ ./~/react-native-scrollable-tab-view/DefaultTabBar.js 10:13-32

It seems like webpack cannot figure out Button.android.js and Button.ios.js
how can i config webpack to solve the problem?

**Comment by skv-headless** [comment]
I think guys from webpack should better know. Actually I have no idea.

**Comment by r1cebank** [comment]
add 
```resolve: {
        extensions: ['', '.js', '.android.js', '.ios.js']
    },```

right before `module` in your webpack.config.js

**Comment by skv-headless** [comment]
thanks 👍

**Comment by summerkiflain** [comment]
@skv-headless I am using this with expo sdk33, react-native-web, I don't have `webpack.config.js` how can I resolve './Button' properly, I can see that there are 3 type of button available. ios, android and windows.

**Comment by FrancoisDeBellescize** [comment]
@summerkiflain you have to follow the doc : https://docs.expo.io/versions/v33.0.0/guides/customizing-webpack/

`expo customize:web` will allow you to generate a webpack.config.js
