### ISSUE TITLE
How to make the tab content has the different height?

### ISSUE THREAD

**Issue by futurefeeling** [skv-headless/react-native-scrollable-tab-view#258]

**Comment by skv-headless** [comment]
In my app I use custom tab bar https://github.com/skv-headless/react-native-scrollable-tab-view#injecting-a-custom-tab-bar. I'll keep this issue to improve API in that way.

**Comment by skv-headless** [comment]
I changed my mind :) I will close. But I will think about extending api

**Comment by futurefeeling** [comment]
it will be better soon if you add this api :)

**Comment by futurefeeling** [comment]
😢 by the way, maybe I make an fault, I mean the 'height' is the height of view content, like i point in following pic

![image](https://cloud.githubusercontent.com/assets/9881593/15238967/e66eaddc-1910-11e6-94ad-882775352b9c.png)

**Comment by skv-headless** [comment]
Here works flexbox rules

**Comment by futurefeeling** [comment]
but I run you FacebookExample.js makes the same result, the height of the content has a same height.

![image](https://cloud.githubusercontent.com/assets/9881593/15241645/16554980-1924-11e6-8f33-13a7c50b97de.png)

![image](https://cloud.githubusercontent.com/assets/9881593/15241649/1f531616-1924-11e6-8978-16f728b966de.png)

Or somewhere I missed?

It will be better if you can make another example to show how to implement.

following is my code:

```js
<ScrollableTabView
    initialPage={0}
    renderTabBar={() => <HomeTabBar />}
    >
    <ProductItems tabLabel="新品上架" products={require('../data/newest.json')}/>   // flexbox err here?
    <ProductItems tabLabel="爆款专区" products={require('../data/hot.json')}/>
    <View tabLabel="批发市场">
        <Text>批发市场</Text>
    </View>
</ScrollableTabView>
```

**Comment by skv-headless** [comment]
Sorry I can't understand 😢 Could you create a pull request with explanation what is wrong?

**Comment by futurefeeling** [comment]
sorry, a lazy weekend.

![issue](https://cloud.githubusercontent.com/assets/9881593/15278478/d2bb6720-1b4b-11e6-920e-a21ee16d4a28.png)

in your example ,the height of all tab contents based on the highest tab content.

But in my case, I want all of the tab contents has a height based on its own content height.That means maybe every tab content has a different height.

**Comment by sbefort** [comment]
@futurefeeling did you figure this out?  I have the same issue.

**Comment by futurefeeling** [comment]
@sbefort still a problem, and i had to change the UI. If you have some solve idea, tell me please. thanks

**Comment by bondanherumurti** [comment]
i actually managed to create different height, by using onChangeTab and every time the function fired, i specify using 

```javascript
{height: this.state.tabHeight}
``` 

with local state...

**Comment by ivpusic** [comment]
same issue here

**Comment by ismdcf** [comment]
@bondanherumurti can u post ur code . How is that possible to change the height of the container when tab changes

**Comment by franj0** [comment]
[SOLVED] Hi guys, I'm have spent two days on solving problem with height in tabs in "react native".
So the problem is that height is passed from highest tab to other tabs...
I have used "native-base" rule Container Content etc.. and that was fucking problem.
Native base components, container and content probably have sam predefined CSS propertys and mess something with height. 
Try to use npm install react-native-scrollable-tab-view package and remove Container and Content, wrap  tabs in  <View style={{flex:1}}>...</View>  and there is no more problem with height in other tabs. 
ps. every tab component wrap in ScrollView instead of View... gl hf

**Comment by alexpchin** [comment]
I'm just adding a comment to this... I'm not 100% sure if I'm correct but I believe this might solve the problem?

```js
<ScrollableTabView style={{ flex: 1 }}>
  <FlatList tabLabel="First" contentContainerStyle={{ flexGrow: 1 }} /> // Could be inside a named component...
  <FlatList tabLabel="Second" contentContainerStyle={{ flexGrow: 1 }} /> // Could be inside a named component...
</ScrollableTabView>
```
