### ISSUE TITLE
ScrollableTabBar Android performance degradation

### ISSUE THREAD

**Issue by Azimus** [skv-headless/react-native-scrollable-tab-view#259]
Hello we are currently using ScrollableTabBar in our Project, and we are experience lags and performance degradation even on latest android devices. on other hand  on iOS it works perfect. Can we do something to improve performance on android?

**Comment by skv-headless** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/issues/206 is it the same?

**Comment by skv-headless** [comment]
Just to be sure. Did you try https://facebook.github.io/react-native/docs/performance.html#development-mode-dev-true ?

**Comment by Azimus** [comment]
Looking same with #206, i am also aware of mode-dev-true, when we install it as builded .apk in behaves much better, but still slows down over time (2-3 min)

**Comment by skv-headless** [comment]
should be fixed in master please check this.

**Comment by Azimus** [comment]
Thank you for quick reaction - works much better +1 )
