### ISSUE TITLE
how to cut length of underline cursor

### ISSUE THREAD

**Issue by L-Jovi** [skv-headless/react-native-scrollable-tab-view#263]
I try to modify source code that in order to reduce length to half, I change __DefaultTabBar.js__ file

`width: containerWidth / numberOfTabs,` to `width: containerWidth / numberOfTabs / 2,`

but I find that position is wrong

![screen shot 2016-05-17 at 12 24 47 pm](https://cloud.githubusercontent.com/assets/7262199/15311148/62342d72-1c2a-11e6-96b7-5e1b91212621.png)

what should I do?  thanks for your time.

**Comment by skv-headless** [comment]
I should also update this line https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/DefaultTabBar.js#L72

**Comment by L-Jovi** [comment]
@skv-headless  thanks for your reply, I custom the position successfully :)

**Comment by skv-headless** [comment]
👍

**Comment by cciszak** [comment]
@skv-headless unfortunately your comment is not valid anymore as the code has been updated and you are pointing to a different line I believe. Could you let me know how to center the underline?

**Comment by cciszak** [comment]
?

**Comment by booboothefool** [comment]
@skv-headless how do you do this for ScrollableTabView?

**Comment by HyperSimon** [comment]
@booboothefool +1
