### ISSUE TITLE
android view not working.

### ISSUE THREAD

**Issue by vincentlkl** [skv-headless/react-native-scrollable-tab-view#271]
The tab bar is not working on android when I click on the tab on android the content is not showing.

			        <ScrollView tabLabel="Tab2">
								<Tab2Page />
							</ScrollView>
![android](https://cloud.githubusercontent.com/assets/2097251/15494919/a454f07a-21bf-11e6-9eed-ea0d7302b0dd.gif)
![ios](https://cloud.githubusercontent.com/assets/2097251/15494921/a82f4dee-21bf-11e6-8cba-929c976cd4e8.gif)

**Comment by skv-headless** [comment]
What version do you use?

**Comment by vincentlkl** [comment]
"react-native": "^0.26.0"
"react-native-scrollable-tab-view": "^0.4.3"

**Comment by skv-headless** [comment]
I can't reproduce this bug. Could you please give a code snippet? Even better if you create a pull request to example with this bug

**Comment by vincentlkl** [comment]
@skv-headless. I found the issue already.


```
<ScrollView style={styles.bottomFrame}>
  <ScrollableTabView tabBarUnderlineColor="#38B69A" tabBarActiveTextColor="#38B69A">
    <ScrollView tabLabel="Tab1">
      <Tab1Page />
    </ScrollView>

   <ScrollView tabLabel="Tab2">
      <Tab2Page />
    </ScrollView>

   <ScrollView tabLabel="Tab3">
      <Tab3Page />
    </ScrollView>

  </ScrollableTabView>
</ScrollView>
```

After I have changed the ScrollView to VIew. It works like charm. So probably i will move the scroll into the content of each tab. Thanks for the help.
