### ISSUE TITLE
I want to control the tabbar show and hide

### ISSUE THREAD

**Issue by zhongjie-chen** [skv-headless/react-native-scrollable-tab-view#272]
```javascript
renderTabBar={()=><DefaultTabBar ref='tabBar' backgroundColor='rgba(255, 255, 255, 0.7)' />}
```
'tabBar' is undefined

**Comment by skv-headless** [comment]
I do always like this https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute

**Comment by skv-headless** [comment]
Does it work for you?

**Comment by zhongjie-chen** [comment]
@skv-headless Thank you for your answer，I can get this, but how to control the show and hide with animation

**Comment by skv-headless** [comment]
Sorry don't understand you. Could you make a video with effect that you want?

**Comment by skv-headless** [comment]
https://facebook.github.io/react-native/docs/animations.html what else can I say? In my app we hide on content scroll. If it is your case I can make a gist for you.

**Comment by argubihelmi** [comment]
hi, sorry to up old thread but i'm currently looking for ways to hide the tabbar on content scroll. can you share the gist @skv-headless ? thank you very much.

**Comment by proProbe** [comment]
@skv-headless I would also love to see the gist!
