### ISSUE TITLE
Change `renderTabBar()` property to `renderTabBar(props)`

### ISSUE THREAD

**Issue by kiliwalk** [skv-headless/react-native-scrollable-tab-view#274]
Just like react native `ListView`'s `renderScrollComponent` property, pass `props` parameter to and use it in the custom function. With this feature, we can make a more flexible tab bar, such as putting a wrapper View to surround the `DefaultTabBar` or `ScrollableTabBar`.

And what makes me to want this change is that if I set a padding in the style of `ScrollableTabBar` when the bar content's width >= bar's width, an area(width=padding) in the right side of the bar content will never be shown when scrolling.
If changed, I can write as below to add padding:
```js
<ScrollableTabView renderTabBar={(props)=>{
  return <View style={{padding: 10}}><ScrollableTabView.ScrollableTabBar {...props}/></View>
}} />
```

**Comment by skv-headless** [comment]
Sounds reasonable 👍 . It is really easy to do.
