### ISSUE TITLE
Tabs styles can not be overwritten.

### ISSUE THREAD

**Issue by stereoki** [skv-headless/react-native-scrollable-tab-view#287]
please remove default borders and height or make them configurable as backgroundColor. 
it's not possible to override these options.

thanks,
artyom

**Comment by skv-headless** [comment]
Not sure what styles are you talking about.
this borders https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/DefaultTabBar.js#L91?

**Comment by stereoki** [comment]
exactly!

**Comment by skv-headless** [comment]
I think you can https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/DefaultTabBar.js#L72

**Comment by stereoki** [comment]
It doesn't work for me. I can add new styles, but can not override existing ones.

**Comment by skv-headless** [comment]
try to set every borderWidth to 0
```
borderTopWidth: 0,
borderLeftWidth: 0,
borderRightWidth: 0,
```
I will try but not sure when

**Comment by stereoki** [comment]
tried different combinations. i'm sure it's impossible to set already defined properties. i can add new, but can not change existing ones.

**Comment by skv-headless** [comment]
good idea to fill issue to react-native

**Comment by stereoki** [comment]
i found the root cause of the issue. it's not on RN side. the problem is that when you pass style object, its properties apply to parent element and then the same properties apply to the tabs. i suggest to add new property tabBarStyle (similar to tabBarTextStyle). i can fix that if you confirm.

**Comment by skv-headless** [comment]
Could you please give code links?

**Comment by stereoki** [comment]
when you add `style` to ScrollableTabView component the styles apply to component itself
https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/index.js#L233
and the same applies to the tab bar
https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/DefaultTabBar.js#L72

**Comment by stereoki** [comment]
just a kindly reminder.

**Comment by skv-headless** [comment]
Do you use code like this?
```<ScrollableTabView renderTabBar={() => <DefaultTabBar style={{borderWidth:0}} />}>```

**Comment by stereoki** [comment]
Now it works. Thank you!

**Comment by skv-headless** [comment]
🎉
