### ISSUE TITLE
Cross Platform Compatible? 

### ISSUE THREAD

**Issue by SpaceRangerWes** [skv-headless/react-native-scrollable-tab-view#288]
Is the library compatible on Android as well? It works incredibly well with iOS testing, but here is what happens on android 6.0.

![scrollable-view-error](https://cloud.githubusercontent.com/assets/4719435/15556283/b9a2d04a-2292-11e6-960e-c0476f1b82f5.gif)

**Comment by skv-headless** [comment]
I can't reproduce that bug. Could you please reproduce it on example project?

**Comment by tannerkrewson** [comment]
This happens to me too, when i have the ScrollableTabView inside of a View.

**Comment by tannerkrewson** [comment]
OK, here is the fix:

Put style={{flex: 1}} onto any View that contains a ScrollableTabView

**Comment by skv-headless** [comment]
cool 👍
