### ISSUE TITLE
Warning in rn 0.25.1 +

### ISSUE THREAD

**Issue by folivi** [skv-headless/react-native-scrollable-tab-view#291]
hi all,
how to get rid of the warning:
ReactNative.createElement is deprecated. Use React.createElement from the "react" package instead
?

**Comment by skv-headless** [comment]
Would you like to send a pull request?

**Comment by folivi** [comment]
Hi, actually I'm asking how to fix the message.

**Comment by skv-headless** [comment]
Are you sure that it is not produced by your code?

**Comment by folivi** [comment]
yes.
It even occurs  with the example when I change ReactNative version to 0.25.1

2016-05-30 14:24 GMT+02:00 Evgeniy Sokovikov <notifications@github.com>:

**Comment by lwinkyawmyat** [comment]
[Releases Vsersion-0.25.1](https://github.com/facebook/react-native/releases/tag/v0.25.1) had some **deprecations**.

```javascript
import React, { Component, View } from 'react-native';
```
 to
```javascript
import React, { Component } from 'react';
import { View } from 'react-native';
```


**So we got below warning message:**
```
Warning:
ReactNative.createElement is deprecated. Use React.createElement from the "react" package instead
```

We can easily change with [codemod](https://github.com/sibeliusseraphini/codemod-RN24-to-RN25) suggest by react-native official release v0.25.1 note.

**Comment by skv-headless** [comment]
I don't see where I'm using ```ReactNative.createElement```

**Comment by lwinkyawmyat** [comment]
@skv-headless I also don't see `ReactNative.createElement` your module. :+1:
It will be another module.

**Comment by skv-headless** [comment]
Should be fixed in master.
