### ISSUE TITLE
Can you export Tab bar components?

### ISSUE THREAD

**Issue by mschipperheyn** [skv-headless/react-native-scrollable-tab-view#293]
This would be helpful if you want to only slightly customize the existing tabbar.

**Comment by mschipperheyn** [comment]
I'm also noticing that props doesn't seem to get passed when implementing a custom renderTabBar property

**Comment by skv-headless** [comment]
1) sure. You can https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/SimpleExample.js#L6
2) Could you please explain?

**Comment by skv-headless** [comment]
Close for no response from author.
