### ISSUE TITLE
slow underline transitions on device

### ISSUE THREAD

**Issue by vonovak** [skv-headless/react-native-scrollable-tab-view#295]
hi! 
I'm using scrollable tab view to render 4  listviews (one per tab). The transition between them is, unfortunately a bit laggy. What I have in mind is not so much the content, as the underlining of the active tab. Even when having just two simple tabs with little content, the animation of the underlining doesn't always seem to be completely smooth. 
This is especially visible when having 4 tabs, selecting the first and then tapping on the 4th. The underline makes a 'short stop' at each of the tabs between.

Is anyone else experiencing this? (RN 0.26, android 6). Note it works nice when in debug mode, but that is because the code runs in chrome.

If you have an idea on what could be the root cause and point me in some direction, I might try to improve on this.
thanks for this awesome component!

**Comment by skv-headless** [comment]
Have you tried https://facebook.github.io/react-native/docs/performance.html#development-mode-dev-true ?

**Comment by sunpan163** [comment]
I've had the same problem

**Comment by skv-headless** [comment]
We tested on really old devices and it works good

**Comment by vonovak** [comment]
@skv-headless 
What if you have  4 tabs, select the first and then tap on the 4th? For me, the underline makes a 'short stop' at each of the tabs between.

**Comment by skv-headless** [comment]
Did you check my link? What platform are you talking about?

**Comment by vonovak** [comment]
yes, I did. doesn't help, unfortunately. I'm on android.

**Comment by skv-headless** [comment]
Yeah. It would be great. A lot of people asking about this. Maybe some FAQ in the end of readme

**Comment by Mimicx** [comment]
i have the same issue, underline makes a 'short stop' and the animation of the underlining doesn't always seem to be completely smooth

"react-native": "0.50.4",
"react-native-scrollable-tab-view": "^0.8.0",
