### ISSUE TITLE
Swiping to switch page is broken in RN 0.28.0-rc.0

### ISSUE THREAD

**Issue by sjmueller** [skv-headless/react-native-scrollable-tab-view#299]
Heads up that horizontal swiping to switch pages is broken in RN 0.28, when setup similarly to the repo's fb example. Using the page property to switch still behaves as expected. Failure tested with both 0.4.3 and 0.4.4.

**Comment by skv-headless** [comment]
what error do you get?

**Comment by sjmueller** [comment]
No error, just feels like the bounds of the scrollable area is only one page wide, rather than the actual number of page components (in our case, two). The result is that when attempting to swipe, you get the rubber banding effect (even through you can see the next page) then when releasing, it snaps back to same starting page.

**Comment by grabbou** [comment]
Can confirm this is happening @ptomassross

**Comment by kevinejohn** [comment]
+1

**Comment by esperyong** [comment]
+1

**Comment by sjmueller** [comment]
Same problem occurring even in react-native 0.2**9**.0-rc.0, which was just released recently

**Comment by skv-headless** [comment]
Sorry guys. I will take a look asap. Try this https://github.com/skv-headless/react-native-scrollable-tab-view/pull/301 until I will fix this.

**Comment by skv-headless** [comment]
Fixed in master. Many thanks to @dieppe
