### ISSUE TITLE
How can you hide the tab bar?

### ISSUE THREAD

**Issue by RonakKhandelwal** [skv-headless/react-native-scrollable-tab-view#305]
The animation is painfully slow while the current tab is being highlighted. so what I wanted was to remove the animation which changes the "underline" in the tab or better yet can you hide the tab bar itself? also is there any instruction or tut for creating custom tab bar.

**Comment by skv-headless** [comment]
First of all try ```dev=false``` https://facebook.github.io/react-native/docs/performance.html#development-mode-dev-true.
Just take one of the tab bars for example this https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabBar.js and do there whatever you want.
