### ISSUE TITLE
textColor #fff

### ISSUE THREAD

**Issue by steida** [skv-headless/react-native-scrollable-tab-view#308]
Someone forget to remove console.log from code. Use eslint please ;)

```js
var textColor=require(661 /* ./../../Themes/light */).tabTextColor;
console.log("textColor",textColor);
```

**Comment by skv-headless** [comment]
Sorry have no idea what are you talking about

**Comment by steida** [comment]
Hmm, maybe something in React Native. Nevermind.

![screen shot 2016-06-12 at 16 15 59](https://cloud.githubusercontent.com/assets/66249/15991647/fb78aeac-30b8-11e6-90ac-8ae7d0aa69e3.png)

**Comment by skv-headless** [comment]
😄
