### ISSUE TITLE
how can I create "Previous" and "Next" button?

### ISSUE THREAD

**Issue by michalfeher** [skv-headless/react-native-scrollable-tab-view#314]
I need a button that would get me into previous/next page.
Thanks.

**Comment by skv-headless** [comment]
In ```onChangeTab``` callback keep in state index of previous and current tab.

**Comment by michalfeher** [comment]
Thanks. Could you please share some example?

**Comment by skv-headless** [comment]
No Actually I don't use that feature. There is an issue for that #249

**Comment by michalfeher** [comment]
I think this is something different than what I've asked. What you referenced is a callback when the tab is changing. I need something that would trigger a tab change. Just like clicking on the particular tabs.

**Comment by skv-headless** [comment]
https://gist.github.com/skv-headless/3a1391d3b52736e7367eb33c3bc1a52b I hope it will help

**Comment by michalfeher** [comment]
perfect, thank you!

**Comment by yogeshR5** [comment]
@michalfeher  could you share next and previous arrow in tab example code
