### ISSUE TITLE
Cannot get tab item by ref after upgrading to 0.5.0

### ISSUE THREAD

**Issue by ivpusic** [skv-headless/react-native-scrollable-tab-view#315]
I have something like this

      <ScrollableTabView onChangeTab={e => this.loadDataForTab(e.i)}>
        <Tab1 ref='tab1' />
        <Tab2 ref='tab2' />
        <Tab3 ref='tab3' />
      </ScrollableTabView>

In `loadDataForTab` method I am calling method on TabX, for example: `this.refs.tab2.method()`. After upgrading to 0.5.0, this is not working anymore (this.refs.tab2 is undefined). It is working only for the first tab => `this.refs.tab1.method()`. Also if I switch initial setup to 

      <ScrollableTabView onChangeTab={e => this.loadDataForTab(e.i)}>
        <Tab2 ref='tab2' />
        <Tab1 ref='tab1' />
        <Tab3 ref='tab3' />
      </ScrollableTabView>

then `this.refs.tab2.method()` is working but not `this.refs.tab1.method()`.

BTW: tab ref received from `onChangeTab` event does not have access to initial component, so ref.method() does not exists.

Any ideas?

**Comment by skv-headless** [comment]
Now tabs lazy rendered. If I understood your case correct you can move that logic to ```componentDitMount```

**Comment by ivpusic** [comment]
the same thing is in componentDitMount.

**Comment by est7** [comment]
initialPage cant trigger onChangeTab callback
