### ISSUE TITLE
First tab doesn't render when upgrading from 0.4.4 to 0.5.0

### ISSUE THREAD

**Issue by LeBlaaanc** [skv-headless/react-native-scrollable-tab-view#317]
What's the trick to get it to render?

**Comment by skv-headless** [comment]
Could you share code snippet?

**Comment by LeBlaaanc** [comment]
I'll see if I can simplify what I have and post. In the meantime any idea how static-container determines the view is visible?

**Comment by sjmueller** [comment]
+1

I am having problems with my second page's listview being blank, and it's very hard to get it to appear.

**Comment by sjmueller** [comment]
For more information, it seems to go back to this commit, line 197:

https://github.com/skv-headless/react-native-scrollable-tab-view/commit/967b79fcdab70e7700b169fe187fdf10557626ee#diff-168726dbe96b3ce427e7fedce31bb0bcR197

changing that line to simply `{child}` fixes the problem, which means that the lazy loading is currently bugged (at least with react-native > 0.28.0)

**Comment by Richard-Cao** [comment]
this problem +1 @skv-headless  @brentvatne

**Comment by Richard-Cao** [comment]
please fix...

**Comment by skv-headless** [comment]
Still I don't know how to reproduce that bug

**Comment by Richard-Cao** [comment]
@skv-headless https://github.com/attentiveness/reading/blob/master/app/pages/Main.js#L339 can reproduce

**Comment by ronak301** [comment]
+1
I am having same problem after upgrading to 0.5.1 from 0.4.4
Platform : IOS
Fix: as mentioned by @sjmueller  changing 197th line to {child} fixed for me.
Definitely, this has to be fixed in upcoming release.

**Comment by skv-headless** [comment]
Do you use dynamic tabs? I mean you load it from somewhere?

**Comment by skv-headless** [comment]
I will appreciate if you check this out #340

**Comment by ronak301** [comment]
seems good. when u will be releasing new release with this fix.

**Comment by skv-headless** [comment]
I want to look at it one more time without hurry. On this week I suppose.

**Comment by Richard-Cao** [comment]
Wonderful!

**Comment by ronak301** [comment]
Cool.

**Comment by sjmueller** [comment]
Not sure if this fixed the issues for everyone else, but I tried `v0.5.2` and definitely still have blank screens when switching tabs. Tested with react native `0.28.0` and `0.29.0-rc.2`.

**Comment by 9mm** [comment]
@sjmueller did you resolve it by chance? I was thinking I am crazy, I'm glad I found this issue.

**Comment by samuelkraft** [comment]
I also have blank tabs when switching by tapping a tab. If I swipe it seems to work. `v0.5.2`
