### ISSUE TITLE
this.scrollView.scrollTo is not a function

### ISSUE THREAD

**Issue by cinic2003** [skv-headless/react-native-scrollable-tab-view#318]
When I upgrade to RN 0.27.2,click to switch page,got this error:

**this.scrollView.scrollTo is not a function

Constructor.goToPage
index.js  @ 82:0

Object.onPress
TabBar.js @58:0**

.....

**Comment by skv-headless** [comment]
I've update examples to RN 0.27.2 . Everything works fine. Do you use custom tab bar? Please attach your code snippet.

**Comment by cinic2003** [comment]
Thanks,I will check it

**Comment by skv-headless** [comment]
Did you find the problem?

**Comment by PeterRock** [comment]
debug like this:
console.log(this.scrollView);
if it shows null or undefined, I guess you didn't bind this.scrollView

**Comment by skv-headless** [comment]
What line?

**Comment by skv-headless** [comment]
Probably update will help. In every place where ```scrollView``` used there is check for ```scrollView``` defined

**Comment by skv-headless** [comment]
close for no response

**Comment by moniquealtero** [comment]
There is an available method called goToPage, you can use like this:

`if(this._scrollTab) this._scrollTab.goToPage(2)`

Hope it helps.
