### ISSUE TITLE
What’s the meaning of Prop 'Page'

### ISSUE THREAD

**Issue by hiphonezhu** [skv-headless/react-native-scrollable-tab-view#320]
I am confused. Is there any example to explain it?

**Comment by skv-headless** [comment]
It is an attempt to control visible tab by property. Better to use ```ref.goTo(page)``` like here https://gist.github.com/skv-headless/3a1391d3b52736e7367eb33c3bc1a52b. What do you want do to with it?

**Comment by hiphonezhu** [comment]
I known what you say. But when I tried to use 'Page', it does not seem to work well.
just like:
render() {
  return (
    <ScrollableTabView
      page={2}
      renderTabBar={() => <DefaultTabBar/>}>
      ...
    </ScrollableTabView>
  );
}

**Comment by skv-headless** [comment]
Don't use it. Why do you need this property?

**Comment by hiphonezhu** [comment]
@skv-headless 
What's mean 'Don't use it.', I am learning the prop, just confused

**Comment by skv-headless** [comment]
It is a legacy I would like to remove it but someone might use it. Probably in next version I'll remove it.
