### ISSUE TITLE
How do I change animation speed?

### ISSUE THREAD

**Issue by jsdario** [skv-headless/react-native-scrollable-tab-view#322]
Sorry that I was unable to find it on the README.md!

**Comment by skv-headless** [comment]
react-native doesn't allow this. For example for iOS https://github.com/facebook/react-native/blob/13dfb6267a16f3430cf609d47b290ab977082300/Libraries/Components/ScrollView/ScrollView.js#L370 there is no such option. I think it is possible to do (decelerationRate in scrollView for ios, dont know about android). I will keep this issue if you open issue in ```react-native``` repo.

**Comment by skv-headless** [comment]
I was wrong. You can set ```decelerationRate```. You can try with ```contentProps```. But you cant change speed of scroll neither for ```UIScrollView``` nor ```ViewPager```.
