### ISSUE TITLE
no scrolling after upgrade to RN 0.28

### ISSUE THREAD

**Issue by knowbody** [skv-headless/react-native-scrollable-tab-view#325]
After upgrading to RN 0.28 the scrolling stop working, when I click on the TabBar items it scrolls to the correct tab, but when I try to swipe left or right it always comes back to the first tab, regardless which tab is selected. Any idea what can be wrong?

**Comment by IlyasM** [comment]
+1

**Comment by skv-headless** [comment]
Try master version

**Comment by almasakchabayev** [comment]
Having similar issues, when trying to run in master have weird errors

**Comment by skv-headless** [comment]
weird errors?

**Comment by almasakchabayev** [comment]
@skv-headless sorry, stupid mistake. works in master

**Comment by knowbody** [comment]
@skv-headless thanks for your help!
