### ISSUE TITLE
How to use contentProps?

### ISSUE THREAD

**Issue by rqzheng2015** [skv-headless/react-native-scrollable-tab-view#326]
Hi guys, I'm facing the problem that buttons only respond at second tap in a ScrollView, there's a solution here https://github.com/facebook/react-native/issues/4087
 Is there any demo to use contentProps so i can add the props to this component? ?

**Comment by skv-headless** [comment]
What property do you want to add?

**Comment by rqzheng2015** [comment]
keyboardShouldPersistTaps={true}
bounces={true}
and so on...I just don't know how to set an array of props in it by 'containProps', please show me an example, thanks.

**Comment by skv-headless** [comment]
Should work
```
 <ScrollableTabView contentProps={{bounces: true}}>
        <ReactPage tabLabel="React" />
        <FlowPage tabLabel="Flow" />
        <JestPage tabLabel="Jest" />
      </ScrollableTabView>
```

**Comment by rqzheng2015** [comment]
No i mean how to pass an array of properties? you example just pass one props, please show me another example, thanks.

**Comment by skv-headless** [comment]
updated note above

**Comment by ignivanishant** [comment]
its not workingi use it like
 <ScrollView 
        ref='modalScrollView' 
        contentProps={{keyboardShouldPersistTaps: true,}}
        automaticallyAdjustContentInsets={true}
      
        style={{}}>
        <View style={{backgroundColor:'#fff'}}>
          <View style={{justifyContent:'center',height:(Screen.height/100)*8,}}>
          <Text style={{alignSelf:'center',fontFamily:'Roboto-regular',fontSize:(Screen.height/100)*3.5}} numberOfLines={1}>{this.state.networkName.capitalizeEachLetter()}</Text> 
          </View>
          {(this.state.networkPassword) &&
            <View style={styles.netPwd}>
              <Text style={styles.enterPasswordText}>Enter Password To Add:</Text>
              <TextInput style=  {styles.textInput}
                ref='password'
                placeholder='Password'
                onChangeText={this.onChangeSearchText} 
                autoCapitalize='none'
                returnKeyType='done'
                secureTextEntry={true} 
                onSubmitEditing={(event) => this.checkNetworkPassword()}
                // onFocus={()=>this._handleScrollView(React.findNodeHandle(this.refs.password))}
                // onBlur={()=>this._resetScrollView(React.findNodeHandle(this.refs.password))}
                onFocus={()=>this.moveModal(React.findNodeHandle(this.refs.password))}
                onBlur={()=>this.moveModal(React.findNodeHandle(this.refs.password))}
              />
            </View>
          } 
          <TouchableHighlight onPress={this.checkNetworkPassword} 
            style={styles.addButtonContainer}>
            <Text style={styles.addButton}>Add</Text>
          </TouchableHighlight>
        </View>
      </ScrollView>  


but it didn't work for me

**Comment by ignivanishant** [comment]
can you plz provide me solution
and its all inside a model
