### ISSUE TITLE
Scrolling is broken with RN0.28

### ISSUE THREAD

**Issue by JeandeCampredon** [skv-headless/react-native-scrollable-tab-view#329]
As soon as I update to RN to 0.28, the behaviour of the scrolling is totally erratic. I end up being to the first view (index = 0).
Only the Tabbar let us scroll.
Can't give it a look now, but I'll try asap !

PS: It is reproducible on any example

**Comment by skv-headless** [comment]
It is fixed. Update ```react-native-scrollable-tab-view``` version

**Comment by JeandeCampredon** [comment]
my bad,  thanks !
