### ISSUE TITLE
Listview is snapping and scrolling between tabs you can swipe diagonal with upgrade to 0.25

### ISSUE THREAD

**Issue by jkyau** [skv-headless/react-native-scrollable-tab-view#330]
Hi, 

I've upgraded to 0.25 and my listview in each tab now has the following 3 issues. 

1) As you scroll up the content will snap up to the next row. Can we turn the snap off?
2) When you swipe left or right to the next tab, you can swipe diagonally which feel sstrange. It was much nicer when you can just scroll horizontally to the next tab. Can we only allow horizontal scroll between tabs?
3) Onendreached in my list view keeps getting called now. Everytime I swipe the new tab onendreach gets called several times on the list view. Not sure what is going on here, please help. 

Thanks for any and all help!

**Comment by jkyau** [comment]
Some context here is that in each of my tabs, the content is a different listview. It used to work great in 0.24, not sure what has changed.

**Comment by JAStanton** [comment]
I am experiencing the same behavior you listed as well as one additional behavior that may be associated:

- Switching tabs with different scroll views in each tab, the tab I am switching _from_ scrolls to the top as the tab switch animation occurs.

Do you get this behavior as well? If not I can make a separate issue.

**Comment by skv-headless** [comment]
Try version ```0.5.0``` for react <0.28.

**Comment by JAStanton** [comment]
I tried this on:
react-native version: `0.27.2` 
react-native-scrollable-tab-view on version: `0.5.0`

**Comment by jkyau** [comment]
@skv-headless i'm on 0.24.1, 0.5.0

**Comment by jkyau** [comment]
@JAStanton any luck?

**Comment by skv-headless** [comment]
@JAStanton before https://github.com/skv-headless/react-native-scrollable-tab-view/commit/6f17f23ac2f2a0167cb8f13821543063e1204a95 examples was on
react-native version: 0.27.2 
react-native-scrollable-tab-view: 0.5.0
and I'm pretty sure that it worked fine. Sorry for asking are you sure that you not using ```0.5.1```?
Is behaviour like here https://github.com/skv-headless/react-native-scrollable-tab-view/pull/301#issuecomment-225950305 ?

**Comment by JAStanton** [comment]
Yeah let me get back with you in an hour or so. I was on 0.5.1 and I switched to 0.5.0 but maybe I should have blown away node_modules or cleaned my dependencies first, maybe it lingered in my build. That gif is pretty short but I believe thats the same behavior. I'll get back with you. Thanks

**Comment by jkyau** [comment]
I blew away node_modules and cleaned dependencies but they definitely seem to linger. The strangest issue is that onEndReached keeps getting called, and the vertical scroll seems to have a snap and doesn't scroll smoothly anymore. I have moved back to 0.24.1 and 0.5.0 and did a fresh clean, but can't seem to get the scrollable tab bar back to a working state.

**Comment by JAStanton** [comment]
@skv-headless `0.5.0` was the trick for me! whatever `0.5.1` introduced was no bueno! no more odd snapping, no more swiping diagonally,  no more odd scrolling past my content issues. 👍

**Comment by jkyau** [comment]
@skv-headless @JAStanton we've updated to 1.5.1 and 0.28 and everything is all good now. You can close this. Thanks!

**Comment by skv-headless** [comment]
Sorry guys for that issue.
