### ISSUE TITLE
Experiencing lag while switching when i am having  long listviews in each tab.

### ISSUE THREAD

**Issue by ronak301** [skv-headless/react-native-scrollable-tab-view#331]
Version : 0.4.4
Let say i have component c1 which have 3 tabs in it. Each renders listview l1 , l2, l3 respectively. I have two concerns 
1 ) when my component (c1) renders , all three tabs are called and their

 corresponding data is fetched  , i mean component c1 doesnt show anything , untill all three tabs done thier fetching. Shouldnt it be on demand rendering.
2 ) since i have long listview, while switching a tabs , a huge lag is seen. I tried using interaction manager but that didnt help.

**Comment by skv-headless** [comment]
1) It should not work this way. Since version 0.5 each tab loads lazily after open.
2) Sounds strange. What fps monitor shows you? Could you make a video? Have you tried ```dev=false```. What platform.

**Comment by ronak301** [comment]
1) it is fine now. after updating to 0.5.1 , it renders lazily. but first tab is not rendered, (one of open issue right now , so applied hack for now)
2 ) I have uploaded video (in dev=true mode). Now there is less lag while switching , but still a lag i can say as per the fps.
FPS 
 Dev = true =>  UI : 54(minimum) JS: 11( minimum ) , when switched too fast.
 Dev = false => UI: 49(minimum) JS: 55 ( minimum ), when switched too fast.

Also , can i animate tab title's opacity when its become active using existing api.
Thanks.


[Screen Recording.mov.zip](https://github.com/skv-headless/react-native-scrollable-tab-view/files/338564/Screen.Recording.mov.zip)

**Comment by skv-headless** [comment]
You can animate using onScroll property. Not sure that I can do anything with your performance problem.

**Comment by ronak301** [comment]
Thanks @skv-headless , i will try out onScroll property. 
Will update here, if i can get rid of this performance issue.

**Comment by skv-headless** [comment]
I'll close since I can't do anything with react-native animation performance.
