### ISSUE TITLE
Problem with children container width

### ISSUE THREAD

**Issue by antoxi4** [skv-headless/react-native-scrollable-tab-view#336]
![screenshot_2016-06-29-09-25-02](https://cloud.githubusercontent.com/assets/11519065/16442556/0fa77d56-3ddc-11e6-9534-0e6d30300e31.png)

How i can fix this problem?
I need a difference width but not bigger than parrent.

**Comment by skv-headless** [comment]
Why do you asking here?) Put it on stackoverflow. You can add a link here I will try to ask when I have time.

**Comment by antoxi4** [comment]
Sorry)))
