### ISSUE TITLE
onEnter, onLeave or call child methods

### ISSUE THREAD

**Issue by fbacker** [skv-headless/react-native-scrollable-tab-view#337]
Anyone know how to call a child method or is there a way to implement child method calls ?
I'm trying to call a method when a page is "unselected". This to cleanup using the camera. However I cannot figure out how to call my onExit method on child PageRedeem

	<ScrollableTabView
	  initialPage={2}
	  ref="tabview"
	  style={styles.navigation}
	  renderTabBar={() => <FacebookTabBar />}
	  onChangeTab={(obj) => {
	    console.log("change to index",obj.i);
	    if(obj.i!=2){
	      // item exists but not onExit()
	      self.refs.tabview._children()[2].onExit();
	      // item exists but not onExit
	      self.refs.pageRedeem.onExit();
	    }
	  }}>
	  <TmpView label="Page 1" itemcol="#414A8C" tabLabel={{label:"Reture", icon:"ios-skip-backward"}} />
	  <TmpView label="Page 2" itemcol="#994A8C" tabLabel={{label:"Vinster", icon:"ios-ribbon"}} />
	  <PageRedeem tabLabel={{label:"Lös in", icon:"ios-qr-scanner"}} ref="pageRedeem" />
	  <TmpView label="Page 4" itemcol="#CCCCCD" tabLabel={{label:"Fellogg", icon:"md-hammer"}}  />
	  <TmpView label="Page 5" itemcol="#4133CD" tabLabel={{label:"Kontakt", icon:"md-contact"}} />
	</ScrollableTabView>

A neat feature is that if a child has the function onEnter or onLeave these would be called automatically from ScrollableTabView.

**Comment by skv-headless** [comment]
Sorry for delay. I've made an example #348. Later I will add ```onLeave``` example.

**Comment by skv-headless** [comment]
Let me now if it doesn't work for you

**Comment by fbacker** [comment]
Good fix. If I'm using a 'clean' class it works

export default TmpView;

However if I'm using for example 'redux' it cannot find onEnter / onLeave

export default connect(mapStateToProps,mapDispatchToProps)(PageRedeem);

Any suggestion on how to fix?
Tried adding functions to mapStateToProps, mapDispatchToProps and context
without any luck.
PageRedeem.contextTypes = {
    store: PropTypes.object,
    onEnter: PropTypes.func,
    onLeave: PropTypes.func
};

**Comment by fbacker** [comment]
maybe not the prettiest solution.

in child class

    componentDidMount() {
      this.props.onAdded(this);
    }

then when adding

    <PageRedeem onAdded={self.childAdd.bind(self)}  i={2} tabLabel={{label:"Lös in", icon:"ios-qr-scanner"}}  />


and the add func

    childAdd(item){
      this._children[item.props.i)] = child;
    }
        
with this childs can use redux connect.
