### ISSUE TITLE
next page not prerendered

### ISSUE THREAD

**Issue by knowbody** [skv-headless/react-native-scrollable-tab-view#341]
I think after I update to 0.5.0, when I scroll through the tabs and the tab is open for the first time it is blank until it gets loaded. going back to the previous and then back again works fine. It's just the first render of each view.

Shouldn't it render the current tab and both previous and next as well?

**Comment by skv-headless** [comment]
I will appreciate if you try it in master

**Comment by knowbody** [comment]
I moved to https://github.com/react-native-community/react-native-tab-view/ as it fits my current requirements better, but I'll give it a shot this evening and will get back to you! thanks for working on it
