### ISSUE TITLE
Any plans to provide a tab bar in which the list of tab labels is horizontally scrollable?

### ISSUE THREAD

**Issue by prithsharma** [skv-headless/react-native-scrollable-tab-view#342]

**Comment by skv-headless** [comment]
Yep. Why not?

**Comment by prithsharma** [comment]
Is there some way to achieve this in the current version?

**Comment by skv-headless** [comment]
No. Actually I've never met such pattern in apps and not sure how it works

**Comment by prithsharma** [comment]
![gm_20160703_131131](https://cloud.githubusercontent.com/assets/1752153/16544339/ffa1f91c-411f-11e6-8da2-4145bcce4c2f.gif)
Here you go, this is a gif of a working example of this in Android. I have seen similar examples in iOS too.

**Comment by skv-headless** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/ScrollableTabsExample.js
Here https://github.com/skv-headless/react-native-scrollable-tab-view#demo if you click on "run this example" link you will see a demo.

**Comment by prithsharma** [comment]
@skv-headless -  I did not understand fully. I was trying to point to the fact that the tab bar in my gif example is itself horizontally scrollable(the number of tabs is a lot more than what can fit in the screen width). Is this present in the Facebook example? The Facebook example has only 5 tabs it seems. Tell me if I'm missing something here.

**Comment by prithsharma** [comment]
Thanks. I missed the scrollable tabs example, my bad. Sorry for that.
