### ISSUE TITLE
Separate tabbar tabs from tab content and target programmatically?

### ISSUE THREAD

**Issue by MovingGifts** [skv-headless/react-native-scrollable-tab-view#343]
The default behavior is that the tabbar tabs are attached in the same container. How can we go about having it separate from the container but still work.

For example, add a ref to each scrollView like ref='tab1' and ref='tab2' and then from a totally separate container on the same page, trigger it programmatically with a prop of tabTarget='tab1' and tabTarget='tab2', or onPress='tabTarget('tab1')?

**Comment by PeterRock** [comment]
You can do this by props `page`.
for example

`
  constructor(props) {

    super(props);

    this.state = {

      selected: 0, // page index

    };

  }
`

`
<ScrollableTabView

    page={this.state.selected}

    ...

   >`

` <Text onPress={() => this.setState({ selected: 1 }) }>Clicker to goto Page 1</Text>`

**Comment by skv-headless** [comment]
I would not recommend to use page property because other guys met few issues with that. I try to avoid using refs. Could you show somehow what you trying to achieve?

**Comment by MovingGifts** [comment]
Sure, I have multiple pages, and all follow a common skeleton layout, wrapped in their respective containing views: header/subheader/content and I plug in the components in the relevant parts. So I want the tabs to be in the subheader layout container and the content of the tabs to go in the content layout container. Currently, they're all attached together, and I am trying to separate them into their appropriate layout container. Does that make sense?

**Comment by MovingGifts** [comment]
@skv-headless Any ideas how to do this?

**Comment by skv-headless** [comment]
here https://gist.github.com/skv-headless/3a1391d3b52736e7367eb33c3bc1a52b how to use ```goToPage```. But I don't like the idea of separating tab bar and content because I would have to make implicit communication between them. I it would not be easy to do 😢 
Why do you need to put tab bat into subheader? Do you really need this?

**Comment by MovingGifts** [comment]
@skv-headless Thank you for your input. I played around a but more and decided to just use initialPage with the tab index# based on the prop and try to work with the plugin as is without separating the pieces. I'll let you know if I come across any issues/limitations. Thanks again!!

**Comment by MovingGifts** [comment]
@skv-headless I just ran into an issue with not using my layout skeleton.

For the tab content, I am using 2 imported components, with their tabLabel. Those components should be centered (horizontally and vertically) in the view within the displayed tab content, so I have within each of those components a wrapping `<View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}` but the components are only centered horizontally because of `alignItems: 'center'` , but not vertically.

I am not sure why the vertical centering isn't working, since I have `justifyContent: 'center'.` I know I can use marginTop, but the views need to be centered for all device screens, so I can't really use that. As a tip, when I use a backgroundColor in those components to see the height, I can see that the height isn't extending all the way to the bottom when rendered using the tabs component.

How do you think I can get the vertical centering to work? (note: these are 2 very short components, so scrolling within these specific tab content isn't necassary, that's why I am centering them)

**Comment by skv-headless** [comment]
I messed this comment. Sorry. If it's still an issue please create a new one. With picture please 😃
