### ISSUE TITLE
Scrollview inside a tab have different scroll behaviour since v0.5

### ISSUE THREAD

**Issue by Proyoyo** [skv-headless/react-native-scrollable-tab-view#345]
I'm using RN 0.26.1.
Since upgrading to react-native-scrollable-tab-view 0.5, All scrollview inside my tabbar behaves differently than what it was before. The Scrollview will scroll as if there is a threshold that it needs to reach before actually scrolling (it seems to behave like a stepped scrollview).

This was tested on iOS.

**Comment by Proyoyo** [comment]
Revering back to 0.4.4 removes this issue.

**Comment by skv-headless** [comment]
Could you please make a video to be sure that I understood you correctly?

**Comment by Proyoyo** [comment]
Here is how it behaves on 0.4.4: http://imgur.com/iuu6Iwe

Here is how scrollview inside scrollable tab view behaves since 0.5.x: http://imgur.com/Bb1tG5f

As you can see, in 0.5.x, it behaves like a stepped scroll view with some momentum threshold before scrolling to a certain part of the scrollview.

**Comment by Proyoyo** [comment]
If it's a little bit difficult to see, you can check the scroll indicator on the right.

**Comment by skv-headless** [comment]
Try to switch to 0.5.0 version. If it works for you versions since 0.5.1 are for react-native 0.28

**Comment by Proyoyo** [comment]
That fixes it. Thanks!
