### ISSUE TITLE
Empty tabs on Android

### ISSUE THREAD

**Issue by tsyirvo** [skv-headless/react-native-scrollable-tab-view#346]
Hey :)

I'm using RN 0.2.4 & react-native-scrollable-tab-view 0.5.2.

I have two tabs, each with some text inside. On iOS, everything is working fine but on Android, my tabs appear empty.
The titles & swiping are working but whether I put some texts or images inside views or scrollviews, nothing is shown…

Do you have any idea where this might be coming from ?

Cheers,

EDIT: I tried with previous versions of RNSTV and the problem is the same on my end :/

**Comment by vonovak** [comment]
did you set `flex:1` on everything in the tabView?

**Comment by tsyirvo** [comment]
I already had `flex: 1` on the ScrollableTabView component and added it to its child components (the tabViews) but still nothing on Android...

**Comment by skv-headless** [comment]
I need an example to debug and fix this. If you reproduce that bug on one of the examples it will help a lot.

**Comment by tsyirvo** [comment]
Ok i'll try to implement an exemple as is to see if I missed something on my end!

**Comment by skv-headless** [comment]
Thanks. I will be waiting 

![hachiko](https://cloud.githubusercontent.com/assets/1488195/16583795/f23945be-42c8-11e6-9d0c-be09bf137e5c.jpg)

**Comment by wildQueequeg** [comment]
I have this issue as well. TabView will not render any content when it is inside another component. To reproduce, wrap a TabView in a View. Please fix

**Comment by explorigin** [comment]
FYI, The changed happened between 0.5.1 and 0.5.2.

**Comment by qxqxqxqx** [comment]
Same issue on rn 0.28,please fix

**Comment by susan-github** [comment]
Add flex: 1 on the **wrapper** of  "ScrollableTabView" component instead of "ScrollableTabView"

**Comment by skv-headless** [comment]
I will take a look asap. For now you can try to remove wrapper and pass style props to ```react-native-scrollable-tab-view``` might help.

**Comment by tsyirvo** [comment]
Adding `flex: 1` to the wrapper component fixed it for me! Thanks @susan-github 
I don't know why I didn't try this sooner :p

**Comment by ahmetacikgoz** [comment]
Same issue on

"react-native": "^0.29.0",
"react-native-scrollable-tab-view": "^0.5.3",

**Comment by crozzfire** [comment]
@ahmetacikgoz +1 , This broke after upgrading to RN0.29. Have you found any workaround? Setting flex:1 in the wrapper doesn't help in my case.

**Comment by mehdijjz** [comment]
I'm having the same issue

**Comment by EJohnF** [comment]
on RN 0.54, lib 0.8.0 
but it happens randomly, sometimes content shows, then - no
While conten render is called (checked via console.log)

**Comment by theRedster** [comment]
Also having same issue as EJohnF in my wierd case, logging out of app and logging back in fixes it until the emulator is reloaded.

**Comment by georgian3688** [comment]
@EJohnF Did you able to get it work? I am also getting the exact issue. 

I have **scrollView** inside scrollableTabView, its coming randomly sometimes blank. I am using react-native version 0.54.4 and lib version 0.8.0.  

@ptomasroos Can you please tell me any workaround for this?

**Comment by EJohnF** [comment]
Sorry, I don't remember already what was there :/
