### ISSUE TITLE
Image instead of Icon

### ISSUE THREAD

**Issue by ajoshdee** [skv-headless/react-native-scrollable-tab-view#347]
Hi, how can render my icons using Image instead of using the Icons api?

**Comment by skv-headless** [comment]
Not sure that I understood you 😢  What icons api do you mean?

**Comment by ajoshdee** [comment]
react-native-vector-icons

**Comment by skv-headless** [comment]
Do you mean this example https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabBar.js ?

**Comment by ajoshdee** [comment]
yes

**Comment by skv-headless** [comment]
Just use Image component https://facebook.github.io/react-native/docs/images.html

**Comment by ajoshdee** [comment]
Yes, I already did that. like this 
![screen shot 2016-07-05 at 4 34 44 pm](https://cloud.githubusercontent.com/assets/7309782/16578679/6cf28d74-42ce-11e6-9a57-b95284329ecb.png)

**Comment by skv-headless** [comment]
Cool. And what is wrong?

**Comment by ajoshdee** [comment]
my tabIcons are empty. And Where did you get the source for your icons? I don't see it anywhere in your code.

**Comment by ajoshdee** [comment]
`'use strict';

var React = require('react');
var ReactNative = require('react-native');
var {View, Text, StyleSheet, Image, ScrollView, TouchableOpacity} = ReactNative;
var Constants = require('../../Constants');
var Button = require('react-native-button');
import {Actions} from "react-native-router-flux";

class ProfileTabBar extends React.Component {
  constructor(props) {
    super(props);
    this.tabIcons = [];
  }
  componentDidMount() {
    console.log(this.tabIcons);
   this._listener = this.props.scrollValue.addListener(this.setAnimationValue);
  }

  setAnimationValue({ value, }) {
    this.tabIcons.forEach((icon, i) => {
      const progress = (value - i >= 0 && value - i <= 1) ? value - i : 1;
      icon.setNativeProps({
        style: {
          color: this.iconColor(progress),
        },
      });
    });
  }

  iconColor(progress) {
    const red = 59 + (204 - 59) * progress;
    const green = 89 + (204 - 89) * progress;
    const blue = 152 + (204 - 152) * progress;
    return `rgb(${red}, ${green}, ${blue})`;
  }

  render() {
    return <View style={[styles.tabs, this.props.style, ]}>
      {this.props.tabs.map((tab, i) => {
        return <TouchableOpacity key={tab} onPress={() => this.props.goToPage(i)} style={styles.tab}>
          <Image ref={(icon) => { this.tabIcons[i] = icon; }} 
          source={require('image!exam')} style={this.props.activeTab === i ? styles.iconSelect : styles.iconDeselect}/>
        </TouchableOpacity>;
      })}
    </View>;
  }
}

ProfileTabBar.propTypes = {
  goToPage: React.PropTypes.func,
  activeTab: React.PropTypes.number,
  tabs: React.PropTypes.array,
}

const styles = StyleSheet.create({
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 10,
  },
  tabs: {
    height: 45,
    flexDirection: 'row',
    paddingTop: 5,
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  iconSelect: {
    width: 25,
    height: 25,
    tintColor: '#00A025'
  },
  iconDeselect: {
    width: 25,
    height: 25,
    tintColor: '#C3C3C3'
  }
});
module.exports = ProfileTabBar;
`

**Comment by ajoshdee** [comment]
Can you provide simpler example using image? And where to pass my image source. As you can see in my code it has only one source. Thanks in advance.

**Comment by skv-headless** [comment]
I'm not sure that such notation ```require('image!exam')``` works. Example from doc ```<Image source={require('./my-icon.png')} />```

**Comment by ajoshdee** [comment]
yes that works. I've been using it throughout my app.
Just don't know how to render icons in tabs

**Comment by skv-headless** [comment]
Again don't understand you. Like here https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabBar.js#L46 ?

**Comment by ajoshdee** [comment]
Again I'm using Image instead of Icon. I just want to know how to implement it.

**Comment by skv-headless** [comment]
Does ```View``` rendered ```TouchableOpacity```? Try to make red view instead of Image. Ask on stackoverflow. I don't see a problem in ```react-native-scrollable-tab-view```

**Comment by ajoshdee** [comment]
Again there's no problem, I'm just asking how to implement it using Image instead of Icon, Cuz Icon implementation doesn't work on Image.
