### ISSUE TITLE
TabBarUnderline not showing when using renderTabBar

### ISSUE THREAD

**Issue by ajoshdee** [skv-headless/react-native-scrollable-tab-view#350]
```
<ScrollableTabView
          style={styles.container}
          tabBarUnderlineColor='#00A025'
          renderTabBar={() => <ProfileTabBar />}
 >
```
this doesn't work. How do I make tabBarUnderline appear?

**Comment by ajoshdee** [comment]
```
icon.setNativeProps({
        style: {
          color: this.iconColor(progress),
        },
      });
```
this doesn't work since i'm using Image instead of Icon. I get error `icon.setNativeProps is not a function. (In 'icon.setNativeProps({
style:{
color:_this2.iconColor(progress)}})', 'icon.setNativeProps' is undefined)`
when using that.

**Comment by ajoshdee** [comment]
Animated one hopefully.

**Comment by skv-headless** [comment]
It should be inside ProfileTabBar

**Comment by ajoshdee** [comment]
how?

**Comment by skv-headless** [comment]
What is ProfileTabBar? something like here https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/DefaultTabBar.js#L75

**Comment by ajoshdee** [comment]
uhm no, I tweaked your FacebooktabBar.js example
