### ISSUE TITLE
Tinder Like Tab Bar

### ISSUE THREAD

**Issue by angel3509268** [skv-headless/react-native-scrollable-tab-view#352]
Hello
I am developing a tinder-style app using React native now.
I have swiper-cards page, settings page, chating page like Tinder, and want to navigate through these pages by swipe.
Is it possible to implement this using this component?
If so, please let me know how

Thanks

**Comment by skv-headless** [comment]
I don't use tinder. Could you make gif how navigation works there?

**Comment by angel3509268** [comment]
![tinder](https://cloud.githubusercontent.com/assets/17146038/16680825/6e9d6a8e-44bf-11e6-8089-cac2ccc9ece4.gif)
This looks like navigation bar.
But I think I think we can implement this using your tab-bar component

**Comment by skv-headless** [comment]
Cool. You can write https://github.com/skv-headless/react-native-scrollable-tab-view#injecting-a-custom-tab-bar and Animated. When you finish feel free to create PR. I would like to have such tab bar available with ```react-native-scrollable-tab-view```

**Comment by ChauVV** [comment]
You can try this
[https://github.com/ChauVV/React-Native-Tinder-Tabbar](url)
![demo](https://user-images.githubusercontent.com/16476877/60660769-a43e6380-9e82-11e9-85e9-010c21d59c45.gif)

**Comment by recepkocur** [comment]
> You can try this
> https://github.com/ChauVV/React-Native-Tinder-Tabbar
> ![demo](https://user-images.githubusercontent.com/16476877/60660769-a43e6380-9e82-11e9-85e9-010c21d59c45.gif)

wow amazing!!!!
