### ISSUE TITLE
prerenderingSiblingsNumber does not seem to work

### ISSUE THREAD

**Issue by NishanthShankar** [skv-headless/react-native-scrollable-tab-view#353]
I added the prerenderingSiblingsNumber (which is misspelled in README.md btw) to the ScrollableTabView. It does not seem to have any effect.

I am logging componentWillMount on all the children and only the first child sends out a log even if the value is Infinite

**Comment by NishanthShankar** [comment]
here is my code snippet for reference

    <ScrollableTabView prerenderingSiblingsNumber={Infinite}
        onChangeTab={()=>console.warn("changed")}
        renderTabBar={() => <ScrollableTabBar />} >
        <DummyView tabLabel={"1"}/>
        <DummyView tabLabel={"2"}/>
        <DummyView tabLabel={"3"}/>
        <DummyView tabLabel={"4"}/>
    </ScrollableTabView>

    var DummyView = React.createClass({
      componentWillMount: function() { 
        console.warn("Mounted Dummy");
      },
      render: function() {
        return ( <View style={{flex:1}}/> );
      }
    });

**Comment by skv-headless** [comment]
Thanks 👍 I have not tried yet. If you make PR it would be awesome.

**Comment by skv-headless** [comment]
In your code snippet there is a typo. I tried ```Infinity``` and it works. Docs are also fixed.

**Comment by NishanthShankar** [comment]
Actually the problem is that nam install does not install the latest code. It pull 0.5.2 and the prerenderSiblings does not seem to part of the code there

**Comment by skv-headless** [comment]
Ok. I'll publish a little bit later

**Comment by NishanthShankar** [comment]
Thank you

**Comment by rameshvishnoi90904** [comment]
Still prerenderingSiblingsNumber functionality not working.

**Comment by AdarshJais** [comment]
Using prerenderingSiblingsNumber  cause jerk with active tab and also while with changing tab.
