### ISSUE TITLE
ScrollableTabView inside view not rendering tab  content

### ISSUE THREAD

**Issue by rangeshgupta-altair** [skv-headless/react-native-scrollable-tab-view#354]
Is it possible to do something like this? Its not rendering the tab content. Also I need to tab twice to change the tab.
```
<View>
         <View><Text> Header </Text></View>
         </ScrollableTabView>
                    <Text tabLabel='tab1'>tab1</Text>
                    <Text tabLabel='tab2'>tab2</Text>
        </ScrollableTabView>
</View>
```

**Comment by skv-headless** [comment]
You can pass ```renderTabBar={null}``` if you don't want tabs at all? Or do you want to have tabs in another place?

**Comment by mateoKaradza** [comment]
Same issue here - when ScrollableTabView is within the View, it doesnt render any of the tab's content.
Tab labels are display and clicking/switching works but no tab content(text) is displayed.

**Comment by rangeshgupta-altair** [comment]
@mateoKaradza : Issue has been resolved for me. Not sure because of the below changes on the code or I restarted the services and app because of that.

`<View style={{flex:1}}>
         <View><Text> Header </Text></View>
         <View style={{flex:1}}>
         </ScrollableTabView>
                    <Text tabLabel='tab1'>tab1</Text>
                    <Text tabLabel='tab2'>tab2</Text>
        </ScrollableTabView>
        </View>
</View>`

**Comment by damathryx** [comment]
flex:1 solved it for me. thanks
