### ISSUE TITLE
Update react native scrollable tab view to es6

### ISSUE THREAD

**Issue by smhatre59** [skv-headless/react-native-scrollable-tab-view#356]
Please update the node module to support es6 specifications

**Comment by skv-headless** [comment]
what exactly do you mean?

**Comment by smhatre59** [comment]
Some changes like those mentioned in this blog:
http://cheng.logdown.com/posts/2015/09/29/converting-es5-react-to-es6

**Comment by skv-headless** [comment]
1) imports: If users use require syntax it won't work for them. If you prove that I'm wrong we can migrate to them
2) classes: no way to use mixins(without additional packages), no autobinding to this
In other cases I will accept pull requests.
