### ISSUE TITLE
Horizontal Scrolling could not disable in android by locked (True).  Any help ?

### ISSUE THREAD

**Issue by Arwiz** [skv-headless/react-native-scrollable-tab-view#360]
Horizontal Scrolling could not disable in android by locked (True).  Any help ?

**Comment by skv-headless** [comment]
what react-native version do you use? I works since 28

**Comment by skv-headless** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/issues/95
feel free to reopen if it doesn;t work in newer versions

**Comment by Arwiz** [comment]
react-native-cli: 1.0.0
react-native: 0.25.1
