### ISSUE TITLE
Jumping to view without pressing the tab

### ISSUE THREAD

**Issue by ajoshdee** [skv-headless/react-native-scrollable-tab-view#363]
Hi, is it possible to have an alternate button inside a child view? Instead of pressing tabs, a button is placed inside the child view, then if the button is pressed it will jump to the next child view?

**Comment by skv-headless** [comment]
https://gist.github.com/skv-headless/3a1391d3b52736e7367eb33c3bc1a52b#file-gistfile1-js-L30 something like this
