### ISSUE TITLE
prerenderingSiblingsNumber is not working

### ISSUE THREAD

**Issue by shukerullah** [skv-headless/react-native-scrollable-tab-view#364]
I have two ScrollableTabView and if I use prerenderingSiblingsNumber in both than the second ScrollableTabView is not rendering the content. But its working fine if I remove prerenderingSiblingsNumber from any ScrollableTabView.

**Comment by skv-headless** [comment]
Please attach your code. What react-native and react-native-scrollable-tab-view version do you use?

**Comment by skv-headless** [comment]
Please reopen with answer. I don't know how to reproduce this issue

**Comment by prabhaav** [comment]
@skv-headless I am also seeing this issue with nested ScrollableTabViews. Interestingly, it pre-renders fine on iOS, but fails on Android.

RN: 0.36
OS: Android (works on iOS)
Scrollable Tab View: 0.6.0

In my App.js:

`  <ScrollableTabView
        tabBarPosition="bottom"
        page={this.props.page.index}
        locked={locked}
        onChangeTab={this.handleChangeTab.bind(this)}
        prerenderingSiblingsNumber={1}
        renderTabBar={() =>
          <ScrollableTabBar
            backgroundColor='black'
            style={{height: 0}}
          />
        }
      >
        <Media />
        <Home />
      </ScrollableTabView>`

In Home.js:

` <ScrollableTabView
        ref="scrollableTabView"
        tabBarPosition="bottom"
        prerenderingSiblingsNumber={3}
        renderTabBar={() => <HomeTabBar />}
      >
        {tabs}
      </ScrollableTabView>`

**Comment by HiralBarot1512** [comment]
Any solution for this issue?
