### ISSUE TITLE
issue: Inconsistent state when both page and children prop are changed.

### ISSUE THREAD

**Issue by renderless** [skv-headless/react-native-scrollable-tab-view#365]
Ref to https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/index.js#L68

When page and children are both changed, L74 would modify current page number back to previous page due to queued setState call. This caused page is actually scrolled but activeTab is still stay in original page.

Simply switch the calling sequence seems able to fix this issue,

```javascript
componentWillReceiveProps(props) {
    if (props.children !== this.props.children) {
      this.updateSceneKeys({ page: this.state.currentPage, children: props.children, });
    }
    
    if (props.page >= 0 && props.page !== this.state.currentPage) {
      this.goToPage(props.page);
    }
  },
```

**Comment by skv-headless** [comment]
Would you like to send a pull request?
