### ISSUE TITLE
initial tab doesn't load

### ISSUE THREAD

**Issue by peterhn** [skv-headless/react-native-scrollable-tab-view#366]
When the scrollable tab view is loaded for the first time the initial tab view doesn't load. I have to select another tab and then go back in order for the initial tab to load.

I had tried setting the prerenderingSiblingsNumber, initialPage, and page and none of these load the initial tab. 

The issue is similar to: https://github.com/skv-headless/react-native-scrollable-tab-view/issues/321

Am I missing something?

**Comment by skv-headless** [comment]
What react-native and react-native-scrollable-tab-view do you use? Is your ScrollableTabView inside scroll view?

**Comment by MirGhojam** [comment]
same issue here. My react-native is v0.24.1 and latest react-native-scrollable-tab-view.
My ScrollableTabView is inside a View.

**Comment by MirGhojam** [comment]
and my ScrollableTabView  is in a ScrollableTabView , it is the child ScrollableTabView's initialPage that aren't loading content.

**Comment by skv-headless** [comment]
My fault. For react-native <0.28 switch to 0.5.2 version.

**Comment by peterhn** [comment]
@skv-headless I downgrading didn't work. It is not in scrollview. But the children in SrollableTabView are.

**Comment by MirGhojam** [comment]
I've got react-native 0.30 and scrollableTabView "master" branch, and still have the issue.

I've got nested scrollableTabView, the father one is working perfectly, but have issue on the child scrollableTabView.

For android it's not loading the initial tab, and scrollableTabView's tabbar is not showing on the first install.

For ios, child scrollabe tabview's tabbar is not showing on the first install. 


the tabbar issue is  gone when i restart the app.

plz give me any advice to fix the problem.


Thanks in advance.

**Comment by peterhn** [comment]
@skv-headless Actually my scrollable tab view is in a scrollview

**Comment by windhost** [comment]
I upgrade to react native 0.33, but I met the same problem. The ScrollableTabBar doesn't load the initialPage in android

**Comment by MirGhojam** [comment]
@windhost you pass your initial page as prop in your ScrollableTabView's renderTabBar prop(which I am assuming you are using one component to render child component), then in your renderTabBar component's componentDidMount() function add something like this:

```javascript
this.goToPage(-1);
setTimeOut ( () => this.goToPage(this.props.initialPage), 0 );
```
The thought is pre-render something then jump to initial page.

**Comment by windhost** [comment]
@MirGhojam Thank you for your solution, it works well. But the cpu run to 145%.

**Comment by MirGhojam** [comment]
@windhost I don't know if the the newly added content affected your app's performance or simply you have to much to do on your initial page. If you haven't tried RN's InteractionManager, you may try that to improve the app's performance.

PS: avoid logging something like this.props on your console which affects performance deeply.

**Comment by windhost** [comment]
@MirGhojam Thanks a lot.
