### ISSUE TITLE
this is a brilliant component and it's useful.but in my Android phone ,it cannot work smoothly,maybe its speed is slow,how can i can the speed of animation?

### ISSUE THREAD

**Issue by monkingxue** [skv-headless/react-native-scrollable-tab-view#370]

**Comment by skv-headless** [comment]
Please make a gif I'm not sure what are you talking about.
You can check profiler. As I know scroll speed cannot be increased.

**Comment by sriraman** [comment]
I'm also facing the same issue. JS fps is going up to 14  when I'm switching from one tab to another. I can clearly see that the line animation speed is varying when I'm scrolling. It is not smooth. Check the following gif

http://i.makeagif.com/media/7-30-2016/nhua1d.gif

**Comment by skv-headless** [comment]
Please read this https://facebook.github.io/react-native/docs/performance.html
switch to ```dev=true``` it should help.

**Comment by danielbh** [comment]
This worked great. Thanks.
