### ISSUE TITLE
how to hide the tabbar when push to new page?

### ISSUE THREAD

**Issue by cocfident** [skv-headless/react-native-scrollable-tab-view#372]
how to hide the tabbar when push to new page?

**Comment by skv-headless** [comment]
Please make a video or gif. I don't understand what do you mean.

**Comment by gventuri** [comment]
I'm facing the same problem: I'm using both the React Native navigator and your react-native-scrollable-tab-view (which is great), and I have a structure like this:


`  <ScrollableTabView
        ref="appContainer"
        initialPage={0}
        renderTabBar={() => <BottomTabBarSchema />}
        prerenderingSiblingsNumber={1}
        tabBarPosition='overlayBottom'>
          <Navigation
            tabLabel='tab1'
            initialRoute={{page:'Home'}}
          />
          <Navigation
            tabLabel='tab2'
            initialRoute={{page:'Flow'}}
          />
          <Navigation
            tabLabel='tab3'
            initialRoute={{page:'News'}}
          />
          <Navigation
            tabLabel='tab4'
            initialRoute={{page:'Messages'}}
          />
          <Navigation
            tabLabel='tab5'
            initialRoute={{page:'Profile'}}
          />
      </ScrollableTabView>`

Now, using the Navigator, there will be certain pages that require the bar to be hidden or the bar "locked" attribute to be switched. Any suggestions on how to do that?

**Comment by artiestie** [comment]
```
<ScrollableTabView
        ref="appContainer"
        initialPage={0}
        renderTabBar={() => <BottomTabBarSchema />}
        prerenderingSiblingsNumber={1}
        tabBarPosition='overlayBottom'
        locked={this,props.locked /*(or whatever variable you use)*/}>
          <Navigation
            tabLabel='tab1'
            initialRoute={{page:'Home'}}
            setLocked={this.props.locked} // and so on
          />
          <Navigation
            tabLabel='tab2'
            initialRoute={{page:'Flow'}}
          />
          <Navigation
            tabLabel='tab3'
            initialRoute={{page:'News'}}
          />
          <Navigation
            tabLabel='tab4'
            initialRoute={{page:'Messages'}}
          />
          <Navigation
            tabLabel='tab5'
            initialRoute={{page:'Profile'}}
          />
</ScrollableTabView>
```

**Comment by gventuri** [comment]
Thank you very much! That's what I was afraid of. Thing is I have to change it with a 6-level child, and I was hoping there was a better way via ref. Thank you very much anyway!!
