### ISSUE TITLE
  在0.21版本下 运行出错了 Error running in version 0.21

### ISSUE THREAD

**Issue by mvpdream** [skv-headless/react-native-scrollable-tab-view#373]
![image](https://cloud.githubusercontent.com/assets/16203724/17323288/2e797672-58d4-11e6-8c78-af70ca6770ce.png)

**Comment by skv-headless** [comment]
According to the log I don't see ```react-native-scrollable-tab-view``` fault

**Comment by skv-headless** [comment]
close for no answer

**Comment by appbeijing** [comment]
你这是json的错误吧，json在535行有一个错误
