### ISSUE TITLE
[iOS] native event on status bar tap is suppressed by ScrollableTabBar <ScrollView> 

### ISSUE THREAD

**Issue by lenkavon** [skv-headless/react-native-scrollable-tab-view#375]
When you have another scrollview in tabs the native event - scroll-to-top on status bar tap - is suppressed because there are more scrollviews on screen: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIScrollView_Class/index.html#//apple_ref/occ/instp/UIScrollView/scrollsToTop

The ScrollView inside ScrollableTabBar.js should have set the `scrollsToTop={false}`.

**Comment by skv-headless** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/index.js#L170
Or do you mean another ScrollView?

**Comment by lenkavon** [comment]
the one in `index.js` is ok, I mean the one in `ScrollableTabBar.js`  https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/ScrollableTabBar.js

around line 170:
```
    <ScrollView
        ref={(scrollView) => { this._scrollView = scrollView; }}
        horizontal={true}
        showsHorizontalScrollIndicator={false}
        showsVerticalScrollIndicator={false}
        directionalLockEnabled={true}
        bounces={false}
      >
```

**Comment by skv-headless** [comment]
Would you like to send a pull request?

**Comment by lenkavon** [comment]
Sure, I can, I guess that for this one, its not necessary/expected to have possibility to set it `true`

**Comment by skv-headless** [comment]
In this case I see no sense to keep scrollsToTop=true
