### ISSUE TITLE
Fast sliding is not smooth on iOS 

### ISSUE THREAD

**Issue by talisk** [skv-headless/react-native-scrollable-tab-view#376]
When I slide the content view fastly, the ScrollableTabView's tabLabels scroll not fluently.
The problem happens on all of iOS simulators and iOS devices.

**Comment by talisk** [comment]
Yep, left or right swipe the contentView, some low levels devices such as iPhone 4s is obvious.
I have tried `dev=true` or `dev=false`.

**Comment by skv-headless** [comment]
What about profiler?

**Comment by skv-headless** [comment]
I've tested on iphone 4s and it is working good.

**Comment by gviligvili** [comment]
Sorry to say, I came here to check about android perspective.
In my android, without dev and debugger, the first slide is stuttering (very noticeable), but after the first one, it's awesome :).

**Comment by Jasper2016** [comment]
I have the same problem,when  swipe  left or right the contentView,the ScrollableTabView's tabLabels scroll not fluently.

**Comment by calclavia** [comment]
I'm encountering similar problems. This seems to only happen on iOS. On Android the swipes are smooth.

**Comment by roysG** [comment]
Same foe me, when the list is long there is delayed on change button, but the swipe effect is smooth.

**Comment by PressEsc** [comment]
Same for me

**Comment by calclavia** [comment]
Ok, so I solved this problem by removing some animation in one of my tabs. It seems like if there's a decent amount of animation in one of the tabs, it lags

**Comment by skv-headless** [comment]
Nothing I can do with react-native animations. I hope one day it will become better.

**Comment by talisk** [comment]
Maybe it's the performance issue on React Native animations.

**Comment by gviligvili** [comment]
Anyone has a bypass?
