### ISSUE TITLE
How can I change Active-state Text's fontFamily?

### ISSUE THREAD

**Issue by maestrolsj** [skv-headless/react-native-scrollable-tab-view#377]
Hello guys~ can I have a question?
I am using this module.
I tried to assign 'fontFamily' to tabBarTextStyle props.
like this

```
             <ScrollableTabView tabBarUnderlineColor="#94000f" tabBarActiveTextColor="#94000f"
            tabBarTextStyle={{fontFamily:'bmdohyeon'}}>

                <ScrollView tabLabel="날씨상황" style={styles.tabView}>
                    <WeatherPage/>
                </ScrollView>
                <ScrollView tabLabel="즐겨찾기" style={styles.tabView}>
                    <FavoritePage/>
                </ScrollView>

                <ScrollView tabLabel="샾랭킹" style={styles.tabView}>
                    <ShopPage/>
                </ScrollView>
            </ScrollableTabView>
```

At the result, 'bmdohyeon' font style is applied to InActive-state Text on the tabBar but not applied to Active-state Text.

can you advice me about this problem?
here is my github address.
thank you so much!!

refer index.android.js 
☞ https://github.com/WindFinderTeam/WindFinder.git

**Comment by skv-headless** [comment]
According to the code tabBarTextStyle passed correctly only difference with inactive that it is bold. Maybe when your font is bold it looks the same way as default?

**Comment by maestrolsj** [comment]
Actually TextStyle only applied to inActive Text
If I type  like this  tabBarTextStyle={{fontFamily:'roboto' fontSize:'15'}}>
It applyed only to the inActive Text.
InActive Text is still same size and stlyle  as before
I wonder you could clone my Git code and check this out.
You can also change the fontStlye and test 
I appreciated your effort
refer index.android.js 
☞ https://github.com/WindFinderTeam/WindFinder.git

**Comment by walidvb** [comment]
In my case, only android stops applying the `fontFamily`, but does apply `fontSize`. iOS is working as expected

**Comment by jasongaare** [comment]
Similar issue, wishing to explicitly declare the `tabBarActiveTextStyle` separately from the `tabBarTextStyle`, specifically for `fontWeight` unfortunately cannot do this in current implementation

**Comment by povtasci** [comment]
The same issue I have fonts `Montserrat-Light`, `Montserrat-Regular` and  `Montserrat-Bold`. 
So just set `{fontWeight: 'bold'}` can't work for this kind of cases.

**Comment by hose314** [comment]
Same for me, any updates?

**Comment by skv-headless** [comment]
You can use `renderTab` property like here https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/DynamicExample.js#L61 or create custom tab bar. I think API is flexible enough.

**Comment by devvlop** [comment]
Same for me, please update!

**Comment by brenohq** [comment]
same here

**Comment by FlavioNascimento10** [comment]
Same here

**Comment by IronLady** [comment]
Looks like the active text state style use bold fontWeight. 
If you use custom font you just need to "force" fontWeight: 'normal' in the tabBarTextStyle props
