### ISSUE TITLE
Swiping is smooth but the changing of tabs is very slow

### ISSUE THREAD

**Issue by KakarN** [skv-headless/react-native-scrollable-tab-view#382]
I am on android, and testing in my physical device. I have two tabs inside **ScrollableTabView** (Following and Recommended).
```
<View style={styles.container}>
    <HeaderMain/>
    <ScrollableTabView
        tabBarPosition='overlayBottom'
        tabBarUnderlineColor='#2ec76e' 
        tabBarBackgroundColor='white' 
        tabBarActiveTextColor='#2ec76e'
        tabBarInactiveTextColor='#99e3b8' 
        scrollWithoutAnimation={true}
        tabBarTextStyle={{fontFamily: 'Roboto', fontSize: 15, fontWeight: 'bold'}}>
        <FollowingPostPage tabLabel="Following" />
        <RecommendedPostPage tabLabel="Recommended" />
    </ScrollableTabView>
</View>
```
Inside the FollowingPostPage I have a ScrollView which has list of posts (each post has a picture and some text).
```
export default class FollowingPostPage extends Component {
    render() {
        return(
            <ScrollView style={styles.container}>
                <PostCard/>
                <PostCard/>
                ...
                ...
                <PostCard/>
                <View style={styles.toolbar_height}/>
            </ScrollView>
        )
    }
}
```
Inside the RecommendedPostPage there's just a text. 
```
export default class RecommendedPostPage extends Component {
    render() {
        return(
            <View style={{flex:1, backgroundColor: '#ecf0f1'}}>
                <Text>I am from SuggestedPage!</Text>
            </View>
        )
    }
}
```
The swiping between the tabs is smooth. However, the changing of tabs if very slow.

If I press the Recommended tab, or if I swipe from Following to Recommended, the swiping is smooth, and also the tabs change as soon as the page changes.
However, when I am on Recommended, and press the Following tab or swipe from Recommended to Following,  the swiping is very smooth, but the tab change takes a long time, as you can see in the below GIF:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/9060759/17455552/de86af9c-5bd8-11e6-89d7-4a780caa8794.gif)

Is it possible to solve this?

**Comment by skv-headless** [comment]
Inside ```react-native-scrollable-tab-view``` I can't do anything for you but I encourage you to read https://facebook.github.io/react-native/docs/performance.html.
Exactly 
https://facebook.github.io/react-native/docs/performance.html#development-mode-dev-true
and
https://facebook.github.io/react-native/docs/performance.html#slow-navigator-transitions
should help.
