### ISSUE TITLE
Typechecking with flow fails with react-native@0.31

### ISSUE THREAD

**Issue by laat** [skv-headless/react-native-scrollable-tab-view#384]
## Steps to reproduce

```sh
react-native init foobar
cd foobar
npm install react-native-scrollable-tab-view --save
npm i -D flow-bin@^0.29.0
./node_modules/.bin/flow
```

Output:

```
Launching Flow server for /Users/sigurd/test/foobar
Spawned flow server (child pid=53295)
Logs will go to /private/tmp/flow/zSUserszSsigurdzStestzSfoobar.log
node_modules/react-static-container/lib/StaticContainer.react.js:0
StaticContainer.react. Duplicate module provider
current provider. See: node_modules/react-native/Libraries/Components/StaticContainer.js:0


Found 1 error
```

## dependencies

```json
  "dependencies": {
    "react": "15.2.1",
    "react-native": "0.31.0",
    "react-native-scrollable-tab-view": "^0.5.3"
  },
  "devDependencies": {
    "flow-bin": "^0.29.0"
  }
```

**Comment by skv-headless** [comment]
In react native there is a component https://github.com/facebook/react-native/blob/bd60d828c5fc9cb066e5f647c87ecd6f70cb63a5/Libraries/Components/StaticContainer.js but I don't know how to import it. If someone knows how to do it I would like to remove ```react-static-container```

**Comment by laat** [comment]
Adding `.*/node_modules/react-static-container/.*` to `[ignore]` in `.flowconfig` solves the issue for me. Perhaps that is good enough.

**Comment by vonovak** [comment]
@skv-headless you can import the `StaticContainer` like this in your sceneComponent: `const StaticContainer = require('react-native/Libraries/Components/StaticContainer')` but the absolute path seems unavoidable

**Comment by skv-headless** [comment]
Cool 👍  Would you like to send a pull request?

**Comment by vonovak** [comment]
#416
