### ISSUE TITLE
Componnent not working as excptected in android when inside View , (but working excellent in ios)

### ISSUE THREAD

**Issue by roysG** [skv-headless/react-native-scrollable-tab-view#386]
import React from 'react';
import {
    Text,
    View,
    AppRegistry,
    StyleSheet
} from 'react-native';

import ScrollableTabView, {DefaultTabBar } from 'react-native-scrollable-tab-view';

const styles = StyleSheet.create({
    btn:{
        width:100,
        height:100,
        backgroundColor:'red'
    }
})

var AwesomeProject  = React.createClass({
    render() {
        return (

            <View>
                <Text>xx1</Text>

                <ScrollableTabView
                    style={{marginTop: 20, }}
                    renderTabBar={() => <DefaultTabBar />}
                    >

                    <View tabLabel='Tab #1'>
                        <Text tabLabel='Tab #1'>IS fdfs</Text>
                        <Text tabLabel='Tab #1'>yyy</Text>

                        <ScrollableTabView
                            style={{marginTop: 20, }}
                            renderTabBar={() => <DefaultTabBar />}
                            >
                            <Text style={styles.btn} tabLabel='Tab #1'>x1</Text>
                            <Text style={styles.btn} tabLabel='Tab #2'>x2</Text>

                        </ScrollableTabView>

                    </View>

                    <Text tabLabel='Tab #2'>favorite</Text>
                    <Text tabLabel='Tab #3'>project</Text>
                </ScrollableTabView>

            </View>
        );
    },
});

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);

Why does the scroll are stack?

**Comment by roysG** [comment]
any news?

**Comment by skv-headless** [comment]
There are few issues about nesting ViewPager into scrollview not sure that I need to keep one more.
