### ISSUE TITLE
Recognize velocity of swipe

### ISSUE THREAD

**Issue by oschade** [skv-headless/react-native-scrollable-tab-view#387]
The React Native ScrollView-Component recognized the velocity of the swipe if you use the "pagingEnabled"-property. For me, this feels a lot more native. Is there a chance, you could implement this behavior?

**Comment by skv-headless** [comment]
Are you talking about android?

**Comment by oschade** [comment]
Yes, android.

**Comment by oschade** [comment]
I bundled my app once again and this time everything work as expected. Probably it was my fault.
