### ISSUE TITLE
How can I do the pages like the example?

### ISSUE THREAD

**Issue by Talkwondo** [skv-headless/react-native-scrollable-tab-view#388]
With the pictures as you did.

Thanks,

**Comment by skv-headless** [comment]
Sorry, don't understand you. What examples and what pages do you mean?

**Comment by Talkwondo** [comment]
This Example exactly! perfect for my need:
[
<img width="369" alt="screen shot 2016-08-17 at 10 37 19 am" src="https://cloud.githubusercontent.com/assets/20122139/17728437/e2cb7ffa-6467-11e6-8b29-5cfdf83f0f71.png">
](url)

**Comment by skv-headless** [comment]
smth like this https://github.com/skv-headless/react-native-scrollable-tab-view/blob/1ad2e214a5e00dbfec9932b18322a9ed389a659b/examples/FacebookTabsExample/FacebookTabsExample.js#L18

**Comment by Talkwondo** [comment]
Hi,
It gives me this error:
<img width="370" alt="screen shot 2016-08-17 at 5 52 19 pm" src="https://cloud.githubusercontent.com/assets/20122139/17741036/776afd94-64a3-11e6-962e-924dbbd07e85.png">

**Comment by skv-headless** [comment]
Sorry wrong link. https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/SimpleExample.js#L10 just instead of Text use images or any other component which you need
