### ISSUE TITLE
Can we add icon to the tabs?

### ISSUE THREAD

**Issue by kagalenitin** [skv-headless/react-native-scrollable-tab-view#390]
Has anyone tried adding icons to the tab instead of text?
Original implementation: 
<ScrollableTabView>
  <Tab1 tabLabel="Taber" />
  <Tab2 tabLabel="Label" />
</ScrollableTabView>

Expected:
I want to add icon:
<ScrollableTabView>
  <Tab1 icon_src="image1.png" />
  <Tab2 icon_src="image1.png" />
</ScrollableTabView>

I know there is no property called icon_src, but I want to know if this is something that I can achieve?

**Comment by skv-headless** [comment]
You probably need custom tab bar https://github.com/skv-headless/react-native-scrollable-tab-view#injecting-a-custom-tab-bar.

**Comment by roysG** [comment]
As i see you implement in on the parent ScrollableTabView,
But how can i specific different icon for separate tab?
