### ISSUE TITLE
Error while updating property 'nativeBackgroundAndroid' of a view managed by:RCTView

### ISSUE THREAD

**Issue by DesignerTime** [skv-headless/react-native-scrollable-tab-view#396]
`import React,{Component} from 'react';
import {View,Text} from 'react-native';
import FirstPage from './../firstpage/FirstPage';
import ScrollableTabView from 'react-native-scrollable-tab-view';
import KebiaoPage from './../kebiao/KebiaoPage';
export default class MainPage extends Component{

	render(){

		console.log("ScrollableTabView");

		try{
			console.log("try");
		return (
			<ScrollableTabView style={{marginTop: 20, }} initialPage={0}>
      <Text tabLabel='Tab #1'>My</Text>
      <Text tabLabel='Tab #2 word word'>favorite</Text>
      <Text tabLabel='Tab #3 word word word'>project</Text>
      <Text tabLabel='Tab #4 word word word word'>favorite</Text>
      <Text tabLabel='Tab #5'>project</Text>
    </ScrollableTabView>
		);
		}catch(e){
			console.log(e);
		};
	}

}`

When I add those,the app shows 

`Error while updating property 'nativeBackgroundAndroid' of a view managed by:RCTView`

**Comment by reyesr** [comment]
Seems the same than #397 ?

**Comment by skv-headless** [comment]
close for #397
