### ISSUE TITLE
Crash on Android <= 4.4

### ISSUE THREAD

**Issue by reyesr** [skv-headless/react-native-scrollable-tab-view#397]
I have this issue with react-native-scrollable-tab-view (tested with 0.5.3 and 0.5.4) 
- works fine on Android >=5, 
- but crashes on Android <= 4.4

Error message displayed on screen:
![error_scrollabletabview_android44](https://cloud.githubusercontent.com/assets/2188620/17929801/3efa5580-6a03-11e6-8b76-78c216702be9.jpg)

I reproduced the issue on this minimal code below (which is basically the same as the examples, on which it happens too)
````
class TestTab extends React.Component {
  render() {
    return <ScrollableTabView
      style={{marginTop: 20, }}
      initialPage={0}
      renderTabBar={() => <ScrollableTabBar />}
    >
      <Text tabLabel='Tab1'>tab1</Text>
      <Text tabLabel='Tab2'>tab2</Text>
    </ScrollableTabView>;
  }
}
````

- API 23 / Emulator: ok
- API 22 / Emulator: ok
- **API 19 / Emulator: CRASH**
- **API 18 / Samsung S3: CRASH**

**Comment by DesignerTime** [comment]
Oh,It's so bad.....Do you have other component to replace it?or solutions?

**Comment by reyesr** [comment]
It was pretty trivial actually, I pushed #398 that fixes it

@DesignerTime You can fork and apply the fix, or use my fork repo reyesr/react-native-scrollable-tab-view in the meantime if you need a fix urgently

**Comment by DesignerTime** [comment]
Thank you for your reply. I am a novice,so I unfamiliar to these...

**Comment by skv-headless** [comment]
fixed here https://github.com/skv-headless/react-native-scrollable-tab-view/commit/18c4c8ef6703d9046d0fbfbeac6362a91d2e0db0
