### ISSUE TITLE
Problem in rendering ListView after navigator.pop()

### ISSUE THREAD

**Issue by gventuri** [skv-headless/react-native-scrollable-tab-view#399]
Hello there,
I'm having a problem with react-native-scrollable-tab-view and navigator. 
Infact, when I stay in the same tab, the navigator.pop() works properly, but if I load a new scene in tab1, than I switch to tab2, than I came back to tab1 and I use the navigator.po(), it won't render the listView, while it will render everything else, like in the example:

![ezgif-1260863220](https://cloud.githubusercontent.com/assets/15671184/17933593/fd59d54e-6a14-11e6-894c-cade021ac3fe.gif)

Another thing that might be helpful: if I scroll slightly, it will render again.
Any idea of why I'm having this issue? Thank you very much!

P.S. This is my constructor:

```javascript
constructor(props){
    super(props)

    var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 != r2})
    this.state = {
      pogDataSource: ds.cloneWithRows(pogs)
    }
  }
```

**Comment by MacKentoch** [comment]
I have similar issue, still investigating...

**Comment by MacKentoch** [comment]
@gventuri I found another interesting fix in my case.

Could you please try to add `scrollRenderAheadDistance` property to your ListView and tell if it does have influence.


As an example (*I have a fixed little list*):
```javascript 
          <ListView
            enableEmptySections={true}
            scrollRenderAheadDistance={100} // fixes Listview row to appear on navigation
            contentContainerStyle={styles.list}
            dataSource={this.state.dataSource}
            renderRow={this.renderRow}
          />
```

**Comment by gventuri** [comment]
@MacKentoch No, it seems it doesn't work even in this way. 
I'm keep trying, but even the jumpBack doesn't work.
The best method I found at now is to push the previous scene, but it's good only when the route is very short.
Another method could be to simulate a very small scroll, since it seems that when I scroll, the listview gets rendered correctly again.
I'll let you know if I make any progress with that!

**Comment by MacKentoch** [comment]
In fact `scrollRenderAheadDistance` is not 100% effective fix (*when I restart react-native dev server it does no more work*).

But on my side only removing `InteractionManager.runAfterInteractions` works.
But I don't understand that and I dislike this fix....

**Comment by gventuri** [comment]
Thank you so much! Now it's working properly, but I tested it like 2 days ago and it wasn't working. Maybe is a combination with something else. This is the final result, in case someone has a similar issue:

```
<ListView
                dataSource={this.state.pogDataSource}
                onEndReached={() => this.loadPage()}
                onEndReachedThreshold={1000}
                scrollRenderAheadDistance={100}
                renderRow={(pog) => {return this.renderSinglePog(pog)}}
                renderFooter={() => {return this.renderFooter()}}
                removeClippedSubviews={false}/>
```

@MacKentoch  Could you upload a gif of your problem and your code?

**Comment by MacKentoch** [comment]
@gventuri gad to read it is solved.

My app is open source and ListView (grid layout) where I encounter issue is here [jsair app](https://github.com/MacKentoch/jsair-mobile/blob/master/ReactNativeApp/ios/scenes/sponsors/sponsor/Sponsor.js#L124).

This version on github has no problem.
**But my local (*just updated dependencies and not RN*) started to have problem on this ListView only.**

*I will update github repo after having submitted to appStore and playStore the new version.*

Anyway, I guess *grid layout* does not help. 
I will just apply an ugly fix I really dislike (the time RN ListView is fixed):

```javascript 
  componentDidMount() {
    const { dataSource } = this.state;
    const { sponsors } = this.props;

    this.uglyListViewfix = setTimeout(
      () => {
        this.setState({
          isReady: true,
          dataSource: dataSource.cloneWithRows(sponsors)
        });
      },
      300
    );
}

  componentWillUnmount() {
    clearTimeout(this.uglyListViewfix);
    this.uglyListViewfix = null;
  }
```

Yes absolutely horrible... But I hope it is tempory.

I guess we can close this issue?
React Native one is still opened and more relevant to our issues.

**Comment by gventuri** [comment]
Yes, I think that's the best choice, until they fix it.
Again, thank you very much for your help. 

@skv-headless I guess we can close

**Comment by ethan6077** [comment]
<ListView
  scrollRenderAheadDistance={100}
  removeClippedSubviews={false} />

Solved my problem!

**Comment by abuammar** [comment]
<ListView
scrollRenderAheadDistance={100}
        removeClippedSubviews={false} />

solved my issue also
