### ISSUE TITLE
how can I place the tab bar in the bottom?

### ISSUE THREAD

**Issue by wzy535** [skv-headless/react-native-scrollable-tab-view#403]
Hi, when I use the tab bar it display in top of the screen .
How can I display it in the bottom ,and when touch the tab display in above?

Thank you !

**Comment by kyle-ssg** [comment]
Hey, just had a look at the source for this.

Just add tabBarPosition="bottom" as a prop

**Comment by skv-headless** [comment]
Not sure that understood "and when touch the tab display in above" that part of the question. If answer above didn't help reopen with explanations.

**Comment by wzy535** [comment]
OK ,Thank you very much!
