### ISSUE TITLE
How to put the content fill in the middle of the two tabbar

### ISSUE THREAD

**Issue by wzy535** [skv-headless/react-native-scrollable-tab-view#404]
Please see: https://stackoverflow.com/questions/39207354/how-to-put-the-content-fill-in-the-middle-of-the-two-tabbar  
I got 2 tabview ,one is in top,and the other is in bottom. when I click one item of the .I want to get something display in all of the space between the two tabview. any ideas?
Thank you very much and thank you for your time!

**Comment by skv-headless** [comment]
Just put what you need in between. Is there some problems?

**Comment by wzy535** [comment]
Thank you for your comments. on top ,there are 5 ,on bottom there 3, when I click the first one in top menu, it's only display half of the screen.  please see： http://i.stack.imgur.com/mlZ6c.png 。in this picture I want is the whole white space it display only one view. now it display 2.

**Comment by skv-headless** [comment]
When you choose 6-th tab you want to hide bottom ```ScrollableTabView```?

**Comment by wzy535** [comment]
yes, and when I click one of the bottom tab ,I want to hide the top ScrollableTabView.

**Comment by skv-headless** [comment]
1) There is ```onChangeTab``` property where you can find what tab has been selected
2) when certain tab is selected put in a state variable that shows that you don't want to see bottom ```ScrollableTabView``` anymore

**Comment by wzy535** [comment]
OK,Thank you very much. I will try!

**Comment by skv-headless** [comment]
Reopen if you don't get succeed on this

**Comment by wzy535** [comment]
hi, I studied onChangeTab, And I don't know how to hide the the the '2' in the photo:, bellow is the photo, please help! Rellay thank you for your help!!! please!
[https://thumbnail0.baidupcs.com/thumbnail/9d351ea638fd5f27a5e4649e13d77c88?fid=3089772612-250528-745772849839775&time=1472565600&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-PTea%2blj%2fgjfaBiyqGtWjGaPwhSw%3d&expires=8h&chkbd=0&chkv=0&dp-logid=5634164522977394568&dp-callid=0&size=c1366_u768&quality=90](url)

bellow is the code:
`import React from 'react';
import {
  Text,
  View,
} from 'react-native';

import ScrollableTabView, { ScrollableTabBar, } from 'react-native-scrollable-tab-view';
import PopularityView from './PopularityView.js';
import PView from './PView.js';
import PpView from './PpView.js';
import PtestView from './PtestView.js';

export default React.createClass({
  render() {
    return (
<View style={{flex:1}}>
      <ScrollableTabView
      style={{marginTop: 20, }}
      initialPage={0}
      renderTabBar={() => <ScrollableTabBar />}
    >
    <PView tabLabel="menu1" />
    <PopularityView tabLabel="menu2" />
     
    </ScrollableTabView>

    <ScrollableTabView
      style={{marginTop: 20, }}
      initialPage={0}
      renderTabBar={() => <ScrollableTabBar />}
      tabBarPosition='bottom'
    >
    <PpView tabLabel="menu3" />
    <PtestView tabLabel="menu4" />
     
    </ScrollableTabView>
</View>
    )
  },
});`

**Comment by skv-headless** [comment]
```onChangeTab={() => this.setState({bottomTabBarVisible: false})}```
and below

```
{this.state.bottomTabBarVisible &&
 <ScrollableTabView
      style={{marginTop: 20, }}
      initialPage={0}
      renderTabBar={() => <ScrollableTabBar />}
      tabBarPosition='bottom'
    >
    <PpView tabLabel="menu3" />
    <PtestView tabLabel="menu4" />

    </ScrollableTabView>
}
```
or if you don't want to delete you can make ```height={0}```

**Comment by wzy535** [comment]
Sorry. I think I write wrong. I don't want to delete or hide the bottomTabBar.  I mean when I click the top menu 1 ,between the top and bottom tab bar ,It only display menu1's conent <img src="http://www.saitio.com/images/22.jpg" />. when I click bottom menu3, between the top and bottom tab bar it only display menu3's content.<img src="http://www.saitio.com/images/11.jpg" />;
current between it display menu1's content and menu3's content.

**Comment by wzy535** [comment]
@skv-headless  hi,Could you help me ? Thank you very much!! Thank you!!
