### ISSUE TITLE
Disable prop

### ISSUE THREAD

**Issue by marcosinigaglia** [skv-headless/react-native-scrollable-tab-view#405]
Hi, is there a prop to disable the tabs?

**Comment by skv-headless** [comment]
```renderTabBar={() => null}``` or ```renderTabBar={() => <View/>}```. Reopen if it doesn't work

**Comment by marcosinigaglia** [comment]
With this method the tabs disapperas but i need only to disable it.

**Comment by skv-headless** [comment]
Ok. What do you mean by disabling?

**Comment by marcosinigaglia** [comment]
Disable the "goToPage" on tab press.

**Comment by skv-headless** [comment]
For now I can suggest only write [custom tab bar](https://github.com/skv-headless/react-native-scrollable-tab-view#injecting-a-custom-tab-bar). After #402 you will be able to customize tab rendering. In your case render ```Text``` instead of ```TouchableOpacity```.

**Comment by marcosinigaglia** [comment]
Ok, thank you.
