### ISSUE TITLE
Crashes when using with react native 0.32

### ISSUE THREAD

**Issue by lukaswelte** [skv-headless/react-native-scrollable-tab-view#407]
It crashes with `Cannot read property 'props' of undefined` in ViewPagerAndroid.android.js in `_childrenWithOverridenStyle`. 
It appeared only with react native 0.32 (might probably caused by https://github.com/facebook/react-native/commit/5f41769485e72570e94dd95fdfa46b8f446f788d)

**Comment by skv-headless** [comment]
Is there an issue in react-native?

**Comment by lukaswelte** [comment]
I have not found one.

**Comment by RishiAnkush** [comment]
I am also using this package with 0.32 version and getting this error: `Unable to resolve module react-native-scrollable-tab-view`

**Comment by skv-headless** [comment]
Please check master. For now there is no ViewPager any more.
