### ISSUE TITLE
I have a problem with scroll

### ISSUE THREAD

**Issue by Shangyunliang** [skv-headless/react-native-scrollable-tab-view#409]
i put 5 pages into  react-native-scrollable-tab-view . when i scroll . i can see this background color. That is not i wanted . does anyone can help me ?  how can i put a picture under my question? my god

**Comment by skv-headless** [comment]
Please give a little bit more information. Video or gif, code snippet. Also as I understood stackoverflow is more suitable place for this question.

**Comment by Jasper2016** [comment]
give more information.

**Comment by skv-headless** [comment]
I close for now. Please reopen with steps to reproduce.
