### ISSUE TITLE
tabBarUnderlineColor not working

### ISSUE THREAD

**Issue by mihaben** [skv-headless/react-native-scrollable-tab-view#417]
Hi,

I coudn´t changed the color of the underline tab following the instructions of the documentation, after investigate the code I used **tabBarUnderlineStyle** instead of **tabBarUnderlineColor**:

`tabBarUnderlineStyle={{backgroundColor:'white'}}` instead of `tabBarUnderlineColor="white"`

It fixes problem.

**Comment by zhanbst** [comment]
Try this
`<ScrollableTabView
                renderTabBar={() => <DefaultTabBar backgroundColor="#a9a9a9" ackgroundColor activeTextColor="white" inactiveTextColor="rgba(255,255,255,0.8)" underlineColor="white" />}
            ></ScrollableTabView>`

**Comment by skv-headless** [comment]
@mihaben you are write. It tabBarUnderlineColor was removed in 0.6.0.

**Comment by AndrewHenderson** [comment]
For anyone looking, here are a list of properties you can target: https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/index.js#L239-L260
