### ISSUE TITLE
Change tabStyle / tabContainerStyle in the default tab bar ?

### ISSUE THREAD

**Issue by mpinter** [skv-headless/react-native-scrollable-tab-view#418]
When I look into `ScrollableTabBar.js` or `DefaultTabBar.js` source there are props such as

```javascript
propTypes: {
    ...
    tabStyle: View.propTypes.style,
    tabsContainerStyle: View.propTypes.style,
   ...
  },
```

Yet, these can't be changed from the ScrollableTabView component as only following props are passed onto tabBar

```javascript
    if (this.props.tabBarUnderlineColor) {
      tabBarProps.underlineColor = this.props.tabBarUnderlineColor;
    }
    if (this.props.tabBarBackgroundColor) {
      tabBarProps.backgroundColor = this.props.tabBarBackgroundColor;
    }
    if (this.props.tabBarActiveTextColor) {
      tabBarProps.activeTextColor = this.props.tabBarActiveTextColor;
    }
    if (this.props.tabBarInactiveTextColor) {
      tabBarProps.inactiveTextColor = this.props.tabBarInactiveTextColor;
    }
    if (this.props.tabBarTextStyle) {
      tabBarProps.textStyle = this.props.tabBarTextStyle;
    }
```

Is there a reason for this ? I'd like to change some minor styling in default tab bar (like changing padding in the tab buttons), this seems like a comfortable way to do so, instead of writing a custom tabBar from scratch.

Or am I doing something wrong ?

**Comment by skv-headless** [comment]
I suppose people to use like this
```<ScrollableTabView  renderTabBar={() => <DefaultTabBar tabStyle={{color: 'red'}} />} />```
Probably we need to update documentation
