### ISSUE TITLE
 tabBarUnderlineStyle  defined "String" in reademe,is that right?

### ISSUE THREAD

**Issue by X-FAN** [skv-headless/react-native-scrollable-tab-view#419]
![image](https://cloud.githubusercontent.com/assets/8476747/18335611/2c1d2c42-75b3-11e6-95c1-0b88e6c18f0a.png)
not "Object"?

**Comment by skv-headless** [comment]
It is View.propTypes.style like style property. Would you like to send a pull request?

**Comment by X-FAN** [comment]
![image](https://cloud.githubusercontent.com/assets/8476747/18373589/fcb4bb8a-7677-11e6-97e9-f6ff24572a81.png)
I read the source code. Why tabBarUnderlineStyle  is defined  as View.propTypes.style,tabBarTextStyle is defined as Object? How describe them exactly? I am just  a beginner for RN.

**Comment by X-FAN** [comment]
I mean they are described in readme not in source code.

**Comment by skv-headless** [comment]
Fixed
