### ISSUE TITLE
tabBarUnderlineStyle not working ?

### ISSUE THREAD

**Issue by cjmling** [skv-headless/react-native-scrollable-tab-view#420]
I have this  ( I tried some random style too :S ) 

```
<ScrollableTabView
				      style={{marginTop: 50}}
				      tabBarUnderlineStyle={{backgroundColor:'red' , borderColor : 'red' , borderBottomWidth : 0.1 , borderBottomColor : 'red'}}
				      tabBarActiveTextColor="#FFF"
				      tabBarInactiveTextColor="#FFF"
				      tabBarTextStyle={{fontWeight : '200'}}
```

And i still seeing this . 

1. How I can change that blue border ?  
2. And anyway I could add border top , right , left to each tab menu ?

![screen shot 2559-09-08 at 6 09 51 pm](https://cloud.githubusercontent.com/assets/1612187/18347410/864c65de-75ef-11e6-99d1-0ff629875a91.png)

Thanks

**Comment by cjmling** [comment]
Ok it seems like the version 0.5.3 which I'm using is too old and it didn't support.

**Comment by jsantana90** [comment]
Hey @cjmling I'm using "react-native-scrollable-tab-view": "^0.7.0" but I can't seem to use `<ScrollableTabView tabBarUnderlineStyle={{borderBottomColor: 'aqua'}}>` still shows default color.

**Comment by mikearche** [comment]
Some people may still have this issue if they are using version ^0.7.3. Updating to ^0.7.4 fixed it for me.

**Comment by bunnapanhchakrith** [comment]
<ScrollableTabBar style={{borderBottomColor: 'white'}}/>

**Comment by toanluongnhu1709** [comment]
<ScrollableTabView  tabBarUnderlineStyle={ {backgroundColor:'red', height:3} } />
