### ISSUE TITLE
Not working with relay/router

### ISSUE THREAD

**Issue by pt-br** [skv-headless/react-native-scrollable-tab-view#423]
Hey Guys, 

Did someone have already implemented this using relay as RootContainer?

I'm getting this:

`TypeError: undefined is not an object (evaluating '_this.props')`

**Comment by skv-headless** [comment]
I don't use relay 😞 
What is the line number?

**Comment by pt-br** [comment]
Hi @skv-headless:

react-native version: 0.32.0
react-native-scrollable-tab-view version: 0.5.5

![Imgur](http://i.imgur.com/NmDSjDH.png)

Boilerplate I'm using: [https://github.com/relayjs/relay-examples/tree/master/TodoMVC](https://github.com/relayjs/relay-examples/tree/master/TodoMVC)

PS: I don't know how to get the exactly line number from the module, all I have is on the screenshot

**Comment by pt-br** [comment]
Hey @skv-headless or someone else trying to implement this plugin with Relay:

This was the same issue of #155. So I did a fork removing the usage of ViewPagerAndroid. Now it's working fine with a Relay container:

https://github.com/pt-br/react-native-scrollable-tab-view

Regards.
