### ISSUE TITLE
Custom Design for Tab View

### ISSUE THREAD

**Issue by sajjidakr** [skv-headless/react-native-scrollable-tab-view#424]
Isn't it possible to Have completely custom design for Scrollable tabs Below is attached an image
![checkout-shipping](https://cloud.githubusercontent.com/assets/11532857/18385447/2d93866e-76aa-11e6-9383-7d0e1d1ba682.png)

**Comment by skv-headless** [comment]
I'm afraid react-native-scrollable-tab-view wont help you. Only if you want swiping. And you can customize tab bar https://github.com/skv-headless/react-native-scrollable-tab-view#injecting-a-custom-tab-bar
