### ISSUE TITLE
Error while updating 'nativeBackgroundAndroid' of a view managed by: RCTView

### ISSUE THREAD

**Issue by xristos3490** [skv-headless/react-native-scrollable-tab-view#425]
When i run-android on API 23 everything works fine, but when i try to test in API 19 i get this strange error message:

Error while updating 'nativeBackgroundAndroid' of a view managed by: RCTView

I cant figure out what is causing this type of error, specially on specific API level

Thank you

![error](https://cloud.githubusercontent.com/assets/1105590/18390919/b9a3ee28-76b4-11e6-9a23-fa78da93b512.png)

###Code Used
```
<ScrollableTabView
                      tabBarUnderlineColor="white"
                      tabBarBackgroundColor="#078ee7"
                      tabBarActiveTextColor="white"
                      tabBarInactiveTextColor="#e1e1e1"
                      tabBarTextStyle={{fontSize: 11}}
                      onChangeTab={(tab) => {
                        GoogleAnalytics.trackScreenView(tabNames[tab.i]);
                      }}>

                        <TipsList tabLabel="Προγνωστικά"/>
                        <KouponiTable deviceWidth={deviceWidth} tabLabel="Κουπόνι"/>
                        <PreviewList tabLabel="Αναλύσεις"/>
                        <StandingsList tabLabel="Βαθμολογίες"/>

                    </ScrollableTabView>
```

###Additional Information

React Native version: 0.29.0
Platform: Android
Operating System: Windows

**Comment by ubatin** [comment]
fixed  [18c4c8e](https://github.com/skv-headless/react-native-scrollable-tab-view/commit/18c4c8ef6703d9046d0fbfbeac6362a91d2e0db0)

**Comment by ubatin** [comment]
close #397

**Comment by skv-headless** [comment]
Try to update and reopen if it is not working
