### ISSUE TITLE
Nesting Horizontal ScrollView Inside TabView

### ISSUE THREAD

**Issue by matthewwoop** [skv-headless/react-native-scrollable-tab-view#428]
Is there any way to give precedence to a ScrollView nested inside a ScrollableTabView? Whenever I swipe within the ScrollView, the tab begins to change, so I would like to lock the ScrollableTabView when someone scrolls within the ScrollView horizontally.

For example,

```
<ScrollableTabView>
  <View>
    <Text>Page 1</Text>
  </View>
  <View>
    <Text>Main Page</Text>
    <ScrollView>
      Recognize touch event that occurs here, and lock the scrollable tab view accordingly
    </ScrollView>
  </View>
  <View>
    <Text>Page 3</Text>
  </View>
</ScrollableTabView>
```

**Comment by skv-headless** [comment]
try ```locked``` property. zIndex may help. Try to find on stackoverflow how to hanle scroll inside scroll.
