### ISSUE TITLE
[HowTo] Display a part of next and previous tabs

### ISSUE THREAD

**Issue by Brokray** [skv-headless/react-native-scrollable-tab-view#429]
Hi guys,

It is not a real issue but I didn't knew where to post this.

I'm currently trying to create a component like the facebook demo (https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/demo_images/demo-fb.gif) except that I would like to show on the current page : the current page, a bit of the previous page and a bit of the next page.
That way the user understand right away that he can swipe (I hid the tab bar). 

Any idea of how to do this ?

Thank you guys, I hope my bad english does not harm you too much.

**Comment by skv-headless** [comment]
I've never tried to do this. Probably it won't be easy.

**Comment by skv-headless** [comment]
I don't have plan to implement it. I can create next issue with gif showing what you want maybe someone will make it.

**Comment by Brokray** [comment]
I tried to dive in your code and find a way to implement it, but without success neither. It seems like it would be a direct change to ViewPagerAndroid, nah ? That would be great, here is a [.gif](http://gph.is/2cgFzOu) of what I meant. :)

**Comment by skv-headless** [comment]
Good luck. I wanted to write something like this. Also I think it should be separate package for that. If you get succeed please inform me I would love to have such package in my toolbox.
