### ISSUE TITLE
Get some kind of information or inject and index into the card

### ISSUE THREAD

**Issue by robertmylne** [skv-headless/react-native-scrollable-tab-view#430]
I want to trigger something when a card is in view, is there a way to set a property on the views so I can log out the card id that I create. So if for example card 3 is displayed I can then trigger an alert to say "card 3 active".

Thanks for any help. Great package btw :)

**Comment by robertmylne** [comment]
Worked it out by adding a ref to the view and the an onChangeTab to the ScrollableTabView

**Comment by skv-headless** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/DynamicExample.js#L41
Is that what are you looking for?

**Comment by skv-headless** [comment]
Please reopen if link above didn't help
