### ISSUE TITLE
Problem with onPress event

### ISSUE THREAD

**Issue by sOstrovsky** [skv-headless/react-native-scrollable-tab-view#431]
How can I handle onPress event when clicking on Tabs?

```
<ScrollableTabView
      style={{marginTop: 20, }}
      initialPage={0}
      renderTabBar={() => <ScrollableTabBar />}
    >
      <ListView tabLabel='Tab #1' onPress={()={this.function()}}>My Tab</ListView>


    </ScrollableTabView>;
```

Thank you before hand

**Comment by skv-headless** [comment]
Please describe what exactly do you want

**Comment by sOstrovsky** [comment]
I've got an Array with objects inside. These objects have props of id and name. So I want to make scrollable tabs with tabLabel of each with my object name props. 
How can I bind onPress event with each tabLabel to do some manipulation with content inside it?

**Comment by skv-headless** [comment]
you can try ```onChangeTab``` property.

**Comment by skv-headless** [comment]
Reopen if it is not solved.
