### ISSUE TITLE
listview not working

### ISSUE THREAD

**Issue by wj495175289** [skv-headless/react-native-scrollable-tab-view#432]
1.listview in not working ,can not scroll,
2.Android can not working,should config build.gradle?

**Comment by skv-headless** [comment]
Not sure what do you mean. Everything is working for me please give more information.

**Comment by wj495175289** [comment]
render() {
    return(
        <View>
          <ScrollView>
            <ScrollableTabView
                style={{marginTop: 20, }}
                renderTabBar={() => <DefaultTabBar />}
            >
              <Text tabLabel='Tab #1'>My</Text>
              <Text tabLabel='Tab #2'>favorite</Text>
              <Text tabLabel='Tab #3'>project</Text>
            </ScrollableTabView>
          </ScrollView>
        </View>
    );

1.like this can not scroll in android ,and the content must set height;
if set the view like
<View><Scrollview><ScrollableTabView><ListView>   the listview can not scroll

thank you

**Comment by skv-headless** [comment]
still don't understand
1) make a video or gif
2) put your code snippet and please format it

**Comment by wj495175289** [comment]
`export default React.createClass({
    render() {
        return(
            <View>
                <ScrollView>
                    <ScrollableTabView
                        style={{marginTop: 20, }}
                        renderTabBar={() => <DefaultTabBar />}
                    >
                        <Text tabLabel='Tab #1'>My</Text>
                        <Text tabLabel='Tab #2'>favorite</Text>
                        <Text tabLabel='Tab #3'>project</Text>
                    </ScrollableTabView>
                </ScrollView>
            </View>
        );

    },
});`

1.you can run this code  in android 4.4
the content can not display;
2. the Text Switch to the listview,look in android and ios ,can not scroll

**Comment by skv-headless** [comment]
I see. probably because it is inside of scrollview. There are few issues about it. I think they cover that case
