### ISSUE TITLE
tabBarBackgroundColor override doesn't work in 0.6.0

### ISSUE THREAD

**Issue by bsy** [skv-headless/react-native-scrollable-tab-view#434]
In version 0.6.0, the `tabBarBackgroundColor`prop doesn't override properly.  I confirmed by rolling back to 0.5.5 and it works fine.

**Comment by skv-headless** [comment]
What do you mean properly? I tried on example and it works

**Comment by bsy** [comment]
Sorry, to be more specific, the color is always set to `navy`, and I can't override it like you should be able to.

**Comment by skv-headless** [comment]
Since I can't to reproduce can you please make a pull requests showing this bug on examples?

**Comment by skv-headless** [comment]
Close for now. Reopen when I reproduce this bug on example otherwise I cant solve it
