### ISSUE TITLE
Add different icon for each tab

### ISSUE THREAD

**Issue by roysG** [skv-headless/react-native-scrollable-tab-view#436]
As i see in the custom option, you implement the component on ScrollableTabView,
But how can i specific different icon for separate tab?

**Comment by skv-headless** [comment]
Sorry. I don't understand what do you mean?

**Comment by roysG** [comment]
I just want to replace icons instead of text

**Comment by skv-headless** [comment]
Just make custom tab bar https://github.com/skv-headless/react-native-scrollable-tab-view#injecting-a-custom-tab-bar - custom tab bar. Here is an example https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookExample.js

**Comment by saeed2402** [comment]
I can't see any picture being imported in the facebook example, can you please elaborate how to specify different icons for each tab?

Thanks.

**Comment by skv-headless** [comment]
There is a tab bar https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookExample.js#L9
and here https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabBar.js#L46 is an icon. Reopen if it doesn't make sense.

**Comment by saeed2402** [comment]
Thanks, but how can I use an icon that I have designed? It seems like this is limited to what is available on  "react-native-vector-icons/Ionicons", although even those icons do not load for me:
<img width="449" alt="screen shot 2016-11-20 at 2 16 32 pm" src="https://cloud.githubusercontent.com/assets/19387505/20460077/0901c60c-af2c-11e6-8a9d-d2920586bf4f.png">

**Comment by joanne1130** [comment]
Hello, please help!

I am using exactly this method "https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookExample.js#L9" , and it works perfectly. But how can i replace my own designed image with HOME ICON?

![untitled-2](https://cloud.githubusercontent.com/assets/26322876/23789313/4d7286e8-05b5-11e7-8bd2-cc354b5827c9.jpg)
