### ISSUE TITLE
undefined is not an object(evaluating '_this.props') on android

### ISSUE THREAD

**Issue by liubiggun** [skv-headless/react-native-scrollable-tab-view#437]
It happened When I render a simple ScrollableTabView.

**Comment by skv-headless** [comment]
Can you reproduce this bug on examples?

**Comment by liubiggun** [comment]
I try my best to reproduce this bug but nothing accomplished.When I start a new project, it go well. I just can explain how my project at which the bug occur render:

`

render () {

    const {currentUser, tab, navigator, logout} = this.props
    const labelStrings = ['聊天', '联系人', '我']
    const title =
      tab === 'ChatListPage'
      ? labelStrings[0]
      : tab === 'ContactListPage'
        ? labelStrings[1]
        : labelStrings[2]

    return (
      <View style={styles.container}>
        <HeaderComponent
          title={title}
          hasReturnButton={false}
          rightButton='null'
          navigator={navigator}
        />
        <ScrollableTabView
          onChangeTab={this.onChangeTab}
          renderTabBar={() =>
            <CustomTabBar
              iconNames={[
                'ios-chatboxes',
                'ios-people',
                'ios-person',
              ]}
              labelStrings={labelStrings}
            />
          }
          scrollWithoutAnimation={true}
          tabBarPosition="bottom">

          <ChatListPage
            tabLabel="ChatListPage"
            navigator={navigator}
          />
          <ContactListPage
            tabLabel="ContactListPage"
            currentUser={currentUser}
            navigator={navigator}
          />
          <MyselfPage
            tabLabel="MyselfPage"
            currentUser={currentUser}
            navigator={navigator}
            logout={logout}
          />
        </ScrollableTabView>

      </View>
    )
  }

`
The styles.container is just {flex: 1}, the HeaderComponent is just a header menu View and has fixed height, so the rest space of container View is assigned to ScrollableTabView. The children of ScrollableTabView are three simple Views.In ios, it ran well but did not in android and prompt an error "undefined is not an object(evaluating '_this.props')". After that I try to modify source code and use ScrollView whether platform is ios or not , it run well both in ios and android! Maybe there is some problem in ViewPagerAndroid?

**Comment by skv-headless** [comment]
Please try version from master. Now there is no ViewPager.

**Comment by liubiggun** [comment]
OK, thanks a lot!
