### ISSUE TITLE
Load on click

### ISSUE THREAD

**Issue by rainbowhat** [skv-headless/react-native-scrollable-tab-view#442]
Hi,

Is there anyway I could load the tab only when I navigate towards it?
& Is pull to refresh possible with this?

**Comment by skv-headless** [comment]
It is working this way. What you don't like in current behaviour?

**Comment by tuandt** [comment]
Hi @skv-headless,

Thank you very much for great module.

Could we support that when we open a tab then it's content loaded? If not, the tab's content will not be loaded?

**Comment by skv-headless** [comment]
It should work this way. Please reopen with explanation of what you dont like
