### ISSUE TITLE
Ask - How to Pass the props 

### ISSUE THREAD

**Issue by yogieputra8** [skv-headless/react-native-scrollable-tab-view#450]
So I'm working with React Native,

This is my Main Menu Codes. From here, everytime user click the button SOURS, I want to navigate to Sours page and pass the props amount: '50'. (From here everythings work as I expected):

    import React, { Component } from 'react';
    import {
      View,
      Text, 
      Alert,
      TouchableOpacity,
      TouchableHighlight,
      StyleSheet, 
      Image
    } from 'react-native';
    import { Container, Header, Title, Button, Icon, Content, Thumbnail } from 'native-base';
    
    
    module.exports = React.createClass({ 
      render() {
            return (
              <View style={styles.background}>
                <Container> 
                  <Content>
                    <View style={styles.buttonWrapper}> 
                        <View style={styles.center}>
                          <TouchableHighlight
                            onPress={() => {this.props.navigator.push({name: 'Sours', amount: '50'})}}
                            style={styles.buttonMain_}
                            underlayColor="#c5e29e" > 
                          </TouchableHighlight>
                          <Text style={styles.BtnMainText_}>SOURS</Text>
                        </View>
                    </View>  
                  </Content>
              </Container>
              </View>
            );
        }
    })

 <br/> 
This is my SOURS - Codes. In this section I'm using **react-native-scrollable-tab-view** Component, I tried to log **{this.props.amount}** and it gives me result **50**. (From here everythings work as I expected).<br/>
Then I tried to pass the **{this.props.amount}** to TabOne page in **'./sours_comp/sours'**

    import React, { Component } from 'React';
    import {
      Image,
      View, 
      StyleSheet, 
    } from 'react-native';  
    import Swiper from 'react-native-scrollable-tab-view'
    
    import TabOne from './sours_comp/sours'
    import TabTwo from './sours_comp/history'
     
    module.exports = React.createClass({
      componentDidMount(){
        console.log(this.props.amount);
      },
    
      render(){
        return(
          <View>
            <Container>
              <Header>
                <Button transparent onPress={() => this.props.navigator.pop()}>
                  <Icon name='ios-arrow-back' />
                </Button>
                <Title>Sours</Title>
              </Header>
    
              <Content>
                <Swiper>
                  <TabOne tabLabel='Sours' >
                    <TabOne amount={this.props.amount} />  // I tried to pass the amount props
                  </TabOne>
                  <TabTwo tabLabel='History' />
                </Swiper>
              </Content>
            </Container>
          </View>
        )
      }
    }) 

 <br/> 
In this TabOne code section, I tried to log **{this.props.amount}** and it gives me result **undefined**.<br/>

    This is my TabOne - Codes. 
    import React, { Component } from 'React';
    import { 
      View,
      Text,  
      Alert
    } from 'react-native'; 
    
    module.exports = React.createClass({
      componentDidMount(){
        console.log(this.props.amount);
      },
     
      render(){ 
        return(
          <View>
          	<Text>Hallo {this.props.amount}</Text>
          </View>
        )
      }
    }) 

Can you guys help me how to solve this issue?

**Comment by yogieputra8** [comment]
SOLVED - I realise that I made mistake in this lines (SOURS.js code):<br/>
```
<TabOne tabLabel='Sours' >
 <TabOne amount={this.props.amount} />  // I tried to pass the amount props
</TabOne>
```
<br/>

This is how I fix this issue:
```
<TabOne tabLabel='Top Up' 
 navigator={this.props.navigator} 
 topupAmount={this.props.amount} > 
</TabOne>
```

**Comment by dev** [comment]
Thank you @yorgieputra8. This solved my issue as well. :+1:

**Comment by dev** [comment]
Thank you @yogieputra8. This solved my issue as well. 👍
