### ISSUE TITLE
Passing Props Between Tabs

### ISSUE THREAD

**Issue by Mousserlane** [skv-headless/react-native-scrollable-tab-view#452]
Hello, 
How can i pass props between tabs?
For instance, i have a message menu that have 3 sub menu: Inbox, Compose, and Sent Items.
In Inbox menu, if I press the reply button, I want to pass the inbox props to the Compose menu.
I'm using react-native-router-flux Actions to pass the props but when i scroll to Compose menu, my props is undefined. is there any other way to pass props between tabs?

Thank You

P.S: Your project is really awesome

**Comment by skv-headless** [comment]
Put it in a state or store/reducer above the component and pass it as a state. Stackoverflow is much better place for such questions.
