### ISSUE TITLE
Can I add a right slip response event to tab1

### ISSUE THREAD

**Issue by jinleli** [skv-headless/react-native-scrollable-tab-view#453]
I have a PanResponder as below：
![image](https://cloud.githubusercontent.com/assets/20489071/19231590/6b3f9a68-8f0d-11e6-987e-1c92294f4add.png)
Now I'm joining these events on Tab1 as below:
![image](https://cloud.githubusercontent.com/assets/20489071/19231669/e52b379c-8f0d-11e6-920a-e44c3cd2299b.png)
My problem is that I can't slide  to Tab2 now.

**Comment by skv-headless** [comment]
I'm not sure how to handle this. Maybe ```onPanResponderGrant``` or ```onPanResponderTerminate```. Better to ask on stackoverflow
