### ISSUE TITLE
Call tab from react-native-drawer

### ISSUE THREAD

**Issue by shawnpanda** [skv-headless/react-native-scrollable-tab-view#459]
I am hoping to integrate react-native-scrollable-tab-view with react-native-drawer by storing the same tab labels in the drawer since I will have quite a few tabs. As a result, I hope that when the user clicks on a tab label within the drawer, the user will be directed to the corresponding tab in the react-native-scrollable-tab-view. I have dug through the examples and don't see any top action that I could use to call the ScrollableTabView instance. Thus, I am curious whether the action is possible?

Thanks for the great work and would appreciate any advice!

**Comment by skv-headless** [comment]
https://gist.github.com/skv-headless/3a1391d3b52736e7367eb33c3bc1a52b#file-gistfile1-js-L30 is that what are you looking for? If no please make a video describing what are you trying to achieve. I'm very bad in understanding ui explained in words 😞

**Comment by skv-headless** [comment]
@shawnpanda ping

**Comment by skv-headless** [comment]
Close for no answer.
