### ISSUE TITLE
why change tab will render a new instance of child component 

### ISSUE THREAD

**Issue by aqnaruto** [skv-headless/react-native-scrollable-tab-view#463]
>children  (ReactComponents) - each top-level child component should have a  tabLabel  prop that can be used by the tab bar component to render out the labels. The default tab bar expects it to be a string, but you can use anything you want if you make a custom tab bar.

when i change tab , the child component doesnot run 

```
componentWillUnmount(){

        Alert.alert("ddd");

    }
```
this always render a new instance ,so ,it caused many problem,such as this 
![image](https://cloud.githubusercontent.com/assets/9067159/19958795/e2116342-a1dc-11e6-8906-2984e8927a93.png)
the old instance is still not be released,how  to fix it?

**Comment by aqnaruto** [comment]
close

**Comment by KevKo1990** [comment]
@aqnaruto How did you solve this?
Thanks, because I have the same problem right now...!
