### ISSUE TITLE
Not working in Android when placed inside View/ScrollView

### ISSUE THREAD

**Issue by khloukrada** [skv-headless/react-native-scrollable-tab-view#466]
In Android, ScrollableTabView not showing the content of the page and the tab click works incorrectly when it is placed inside another <View> or <ScrollView>. In iOS, it works super fine.

**Comment by messense** [comment]
What is the fix for Android?

**Comment by 9024647467** [comment]
give tabStyle in ScrollableTabView tabStyle,  it work IOS and android....
