### ISSUE TITLE
is it possible to disabling tabBar?

### ISSUE THREAD

**Issue by fakhrishahab** [skv-headless/react-native-scrollable-tab-view#482]
Can i disabling a spesific tabbar?

**Comment by skv-headless** [comment]
Do you mean tab?
Could you describe behaviour what you want (for example how swipe should behave)?

**Comment by skv-headless** [comment]
Close for no response.

**Comment by wesleyvandevoorde** [comment]
I'm currently looking for a way to disable the whole tabbar. So it still shows up but you can't select the tabs nor can swipe between them. Is there any way I can achieve this? Swiping can be disabled with the locked property but I can't find a way to disable taps.
