### ISSUE TITLE
initialPage option - page not rendering - In Android

### ISSUE THREAD

**Issue by edelworksgithub** [skv-headless/react-native-scrollable-tab-view#483]
Hi I am using RN version 0.36.1
I need the second page (or a specific page) to be shown at first. 
While using "InitialPage" props, TabBar position is correct, but the page is not showing... and when I swipe the first page is displaying.

Code is as below
`var Page = React.createClass({
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Page {this.props.num}</Text>
      </View>
    );
  }
});`

`<ScrollableTabView initialPage={2} locked={false}>
        <Page num="1" tabLabel="React" />
        <Page num="2" tabLabel="Flow"/>
        <Page num="3" tabLabel="Jest" />
      </ScrollableTabView>`

Screenshots

![screen shot 2016-11-30 at 8 59 53 pm](https://cloud.githubusercontent.com/assets/8638256/20759280/838a37ec-b742-11e6-838e-c72d11cc9877.png)

![screen shot 2016-11-30 at 9 02 00 pm](https://cloud.githubusercontent.com/assets/8638256/20759298/8d0002ca-b742-11e6-9bf2-41d9d3fc3b18.png)

**Comment by edelworksgithub** [comment]
Kindly help on this issue.

**Comment by skv-headless** [comment]
Can you reproduce this bug on example?

**Comment by edelworksgithub** [comment]
@skv-headless  I don't know to show you live example. Please suggest me an online tool.

The code is as below

`var Page = React.createClass({
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Page {this.props.num}</Text>
      </View>
    );
  }
});`

`<ScrollableTabView initialPage={2} locked={false}>
        <Page num="1" tabLabel="React" />
        <Page num="2" tabLabel="Flow"/>
        <Page num="3" tabLabel="Jest" />
      </ScrollableTabView>`

**Comment by skv-headless** [comment]
I can't reproduce this bug.
I mean in repository there are few examples https://github.com/skv-headless/react-native-scrollable-tab-view/tree/master/examples/FacebookTabsExample . If you can reproduce bug there you can send pull request showing a the problem.

**Comment by edelworksgithub** [comment]
@skv-headless This issue is coming only in Android and working fine in IOS

**Comment by skv-headless** [comment]
What react-native-scrollable-tab-view version do you use? Please try the latest one

**Comment by edelworksgithub** [comment]
0.7.0
installed using  npm install react-native-scrollable-tab-view --save
so I think the latest will be installed.

**Comment by edelworksgithub** [comment]
@skv-headless I used the same code as 
https://github.com/skv-headless/react-native-scrollable-tab-view/tree/master/examples/FacebookTabsExample

**Comment by zhoujuanjuan** [comment]
@edelworksgithub I also have this issue,do you have handled this issue

**Comment by edelworksgithub** [comment]
@zhoujuanjuan not yet.. might be the problem is with ScrollView.

**Comment by gullitmiranda** [comment]
same problem

work for me: https://github.com/skv-headless/react-native-scrollable-tab-view/compare/v0.6.0...v0.7.0#commitcomment-20063817

**Comment by zhoujuanjuan** [comment]
@skv-headless  I use RN version 0.29.2,react-native-scrollable-tab-view version 0.7.0 ,and I put SimpleExample.js to my project , when I set initialPage = 2,the current page not show 
please help me to solve this issue...
may i improve  RN version...

**Comment by leoJFeng** [comment]
me too...

**Comment by zhoujuanjuan** [comment]
change react-native-scrollable-tab-view to version 0.6.0,it works

**Comment by skv-headless** [comment]
`contentOffset` is not supported for android. Please use version `0.6.0` for now.
I will try to make fix that.
https://productpains.com/post/react-native/content-offsetinset-for-scrollview

**Comment by messense** [comment]
Same issue.

**Comment by skv-headless** [comment]
If someone wants to make pr https://facebook.github.io/react-native/docs/scrollview.html#methods you can try `scrollTo` somewhere in `componentDidMount`

**Comment by skv-headless** [comment]
Guys, please try version from master. After some feedback I'll release new version.

**Comment by nezaidu** [comment]
Not working for me. Had to add time out.

**Comment by ranjithkumar8352** [comment]
@skv-headless Now It works with the version from master but there's a slight delay of 500ms. Tab is blank for half a second if initalPage is > 0

**Comment by skv-headless** [comment]
It works for example project. Please provide code snippet. We can continue discussion here #510

**Comment by messense** [comment]
Works for me.

**Comment by kubilaytural** [comment]
Try this. It worked. Ideal for changing first pages.

componentDidMount() {
setTimeout(() => this.scrollableTabView.goToPage(1), 300);
}
...
.....
...
<ScrollableTabView
ref={(ref) => { this.scrollableTabView = ref; }}

**Comment by devilyard** [comment]
> Try this. It worked. Ideal for changing first pages.
> 
> componentDidMount() {
> setTimeout(() => this.scrollableTabView.goToPage(1), 300);
> }
> ...
> .....
> ...
> <ScrollableTabView
> ref={(ref) => { this.scrollableTabView = ref; }}

this works
