### ISSUE TITLE
Does this work for long lists like ListView does?

### ISSUE THREAD

**Issue by adremalin** [skv-headless/react-native-scrollable-tab-view#485]
If it does not work with long lists, could I use only the scrollable tab view:
https://www.npmjs.com/package/react-native-scrollable-tab-view
with a swiper based on ListView?

Thanks!

**Comment by skv-headless** [comment]
Don't understand you. What do you mean that it doesn't work with long lists?

**Comment by skv-headless** [comment]
I get it. No it doesn't work as listview with long lists. But It won't render all your tabs on load.

**Comment by adremalin** [comment]
Ok, gotcha! Can I replace ScrollView with ListView? I need to be able to render very very long lists of items, with images etc, for each tab.  Any other way to customise this to work with very long lists?
