### ISSUE TITLE
How to setup react-native-scrollable-tab-view?

### ISSUE THREAD

**Issue by adremalin** [skv-headless/react-native-scrollable-tab-view#487]
Hi!

I don't understand how to setup react-native-scrollable-tab-view, is there a guide somewhere?

Thanks!

**Comment by skv-headless** [comment]
What exactly doesn't work if follow readme?
https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/README.md

**Comment by skv-headless** [comment]
Close for no answer. Please reopen with additional information.
