### ISSUE TITLE
_clearer is not a function. (In '_clearer(id)', '_clearer' is undefined)

### ISSUE THREAD

**Issue by alexkendall** [skv-headless/react-native-scrollable-tab-view#488]
Getting this error when I press a tab. Oddly, this error only shows up when I'm not debugging remotely.

react-native 0.39
react-native-scrollable-tab-view 0.7.0

**Comment by skv-headless** [comment]
I don't know what is clearer. Can you reproduce this bug on example inside this repository?

**Comment by alexkendall** [comment]
Clo

**Comment by alexkendall** [comment]
Closed. This error was being caused by a different dependency.

**Comment by arunshan** [comment]
@alexkendall Is this because of firestack? If so, how did you resolve the issue?

**Comment by alexkendall** [comment]
@arunshan Yes; use the master version of react-native-firestack to fix the error.
