### ISSUE TITLE
Horizontal scroll broken in 0.7.0

### ISSUE THREAD

**Issue by DavidE2000** [skv-headless/react-native-scrollable-tab-view#489]
Hi, I upgraded this project to the latest version (0.7.0) and my horizontal ListViews and ScrollViews stopped working.
Going back to version 0.6.0 fixed this issue.

In my project i have a scrollable tab view and within it I have ListView.  Trying to scroll though the ListView will just change the page.  

`<ListView
                                dataSource={this.state.dataSource}
                                renderRow={this.renderFavoritePeople}
                                enableEmptySections={true}
                                initialListSize={2}
                                scrollRenderAheadDistance={100}
                                initialListSize={1}
                                horizontal={true}
                            />`

I had this issue on React Native 28 and 29.

Currently fine on React Native 29 with version 0.6.0

Thanks

**Comment by skv-headless** [comment]
Can you reproduce this bug on example project?

**Comment by DavidE2000** [comment]
I will take a look sometime this week.

**Comment by skv-headless** [comment]
Thanks

**Comment by skv-headless** [comment]
Is it only for android? or ios too?

**Comment by DavidE2000** [comment]
I had a play on iOS and it is fine as I have disabled swiping to change pages.  Tomorrow i will remove that flag and see if it plays up.

**Comment by DavidE2000** [comment]
I re-enabled it and it was fine. Horizontal list views and swiping functionality on the tab view. 
React 38 
V 0.7.0

**Comment by skv-headless** [comment]
Cool 👍
