### ISSUE TITLE
My text cuts

### ISSUE THREAD

**Issue by kfir91** [skv-headless/react-native-scrollable-tab-view#493]
Hello, when i use this component
and i insert 4 tabs my last tab text is cutting...

![whatsapp image 2016-12-11 at 12 28 37](https://cloud.githubusercontent.com/assets/11144887/21079538/77d629de-bf9d-11e6-8d54-810f4825d57a.jpeg)

this is my code:

```
			<ScrollableTabView
				initialPage={0}
				renderTabBar={() => <ScrollableTabBar />}>
				{tabs}
			</ScrollableTabView>

```

**Comment by skv-headless** [comment]
use `ScrollableTabBar ` like in https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/ScrollableTabsExample.js
