### ISSUE TITLE
Swipe to the next page, blank before render next page

### ISSUE THREAD

**Issue by naivehhr** [skv-headless/react-native-scrollable-tab-view#498]
![111](https://cloud.githubusercontent.com/assets/5243456/21216884/3a1471ce-c2e4-11e6-9091-f26175ec74d2.gif)

**Comment by skv-headless** [comment]
That is an lazy loading optimization you can try `prerenderingSiblingsNumber`

**Comment by naivehhr** [comment]
thanks, it is my fault. :-)

**Comment by skv-headless** [comment]
You are welcome 🙂
