### ISSUE TITLE
Use of icons

### ISSUE THREAD

**Issue by Marcelrama** [skv-headless/react-native-scrollable-tab-view#499]
If they are going to implement the use of icons in their project managing this way the tab,

Where to use `<tab1 tabLabel = 'Tab 1'  #/>` and the tab they are importing has an icon that will throw an error for future projects and someone can solve it I would thank you to leave here the solution

`import React from 'react';
import {
  Text,
} from 'react-native';
import ScrollableTabView, {DefaultTabBar, } from 'react-native-scrollable-tab-view';
import {Tab1 ,Tab2, Tab3} from './MyTabFolder';

    export default React.createClass({
      render() {
    return <ScrollableTabView
      style={{marginTop: 20, }}
      renderTabBar={() => <DefaultTabBar />}>
      <Tab1 tabLabel='Tab 1' />
       <Tab2 tabLabel='Tab 2' />
       <Tab3 tabLabel='Tab 3' />
    </ScrollableTabView>
  },
});`

**Comment by skv-headless** [comment]
@Marcelrama not sure that I understood the problem 😞

**Comment by skv-headless** [comment]
Close since I'm not fully understand the issue. Probably you can use renderTab property https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/DynamicExample.js#L61
