### ISSUE TITLE
cannot scroll

### ISSUE THREAD

**Issue by leechance** [skv-headless/react-native-scrollable-tab-view#500]
alter--->

`render() {
return (
<ScrollableTabView>
</ScrollableTableview>
)
}`

to--->
`render() {
return (
<View>
<ScrollableTabView>
</ScrollableTableview>
</View>
)
}`

ScrollableTabView use as child component cannot scroll 

did you designed ScrollableTabView had to be used as root compoent???
@skv-headless

**Comment by leechance** [comment]
<img width="370" alt="4ef19742-5004-41cf-988a-baea908945ff" src="https://cloud.githubusercontent.com/assets/16054165/21248346/6a6faa86-c371-11e6-8e6f-03bed6a2d6bd.png">
 
i want to add a navbar at top but the ScrollableTabView cannot scroll

**Comment by skv-headless** [comment]
@leechance I pretty sure that I used it inside another view. Did you find solution? Try to play with flex property.

**Comment by leechance** [comment]
i used it  inside another view ,but it cannot scroll
can you give me the demo that you used it as child component ? thanks you very much

**Comment by skv-headless** [comment]
Can you reproduce this bug on example? It would be much easier to fix for me. You can make pull request which shows this behaviour. Sorry can't give you a demo it was on previous project where I don't have access already.

**Comment by leechance** [comment]
on my example, this bug will  appear
Thanks for your reply;
I'll try again to fix the bug! @skv-headless

**Comment by CaptainVincent** [comment]
The view up level from ScrollableTabView should add style about flex: 1.

**Comment by skv-headless** [comment]
@leechance reopen if setting `flex: 1` doesn't work for you
