### ISSUE TITLE
v0.7.0: cannot set anymore underlineColor to DefaultTabBar

### ISSUE THREAD

**Issue by MacKentoch** [skv-headless/react-native-scrollable-tab-view#502]
**I used to customize `defaultTabBar`:**
```javascript
class ScrollableTabBar extends PureComponent {
  render() {
    return (
      <DefaultTabBar
        backgroundColor={AppColor.white}
        underlineColor={AppColor.mainBlue}
        activeTextColor={AppColor.mainBlue}
        inactiveTextColor={AppColor.darkGrey}
        textStyle={styles.textStyle}
        {...this.props}
      />
    );
  }
};
```

But it seems like previously used `underlineColor` property disappeared and should be replaced now by `underlineStyle`.

Problem is `underlineStyle` is not used.

My fix for now is just to rewrite my own DefaultTabBar just to apply the custom color:
```javascript
  render() {
    const containerWidth = this.props.containerWidth;
    const numberOfTabs = this.props.tabs.length;
    const tabUnderlineStyle = {
      position: 'absolute',
      width: containerWidth / numberOfTabs,
      height: 4,
      backgroundColor: AppColor.mainBlue, // ==> tempory fix /hack
      bottom: 0,
    };
```

**Comment by xwartz** [comment]
They removed `underlineHeight ` and `underlineColor `.

https://github.com/skv-headless/react-native-scrollable-tab-view/commit/811515d2489c887be26eede1409d49e4398df1cc

**Comment by skv-headless** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/blob/ee5d99950fad9c4c1129d029d7bfaea130df72d1/DefaultTabBar.js#L78 it used here
