### ISSUE TITLE
Override tab press?

### ISSUE THREAD

**Issue by kayson** [skv-headless/react-native-scrollable-tab-view#506]
I have been trying to figure out a way to override the behaviour of pressing a **tab item**. So instead of "sliding" to that content I want to be able to call a function. More specifically I want to open a modal screen when pressing a certain tab and have a back (close) button to hide it and go back to where I previously were.

Thanks for any help or advice regarding this!

**Comment by skv-headless** [comment]
You can use `renderTab` property like here https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/DynamicExample.js#L61.
