### ISSUE TITLE
Using page props, but the content doesn't show

### ISSUE THREAD

**Issue by windhost** [skv-headless/react-native-scrollable-tab-view#507]
`				<ScrollableTabView
					style={styles.container}
					renderTabBar={()=><DefaultTabBar backgroundColor='rgba(255, 255, 255, 0.7)'/>}
					tabBarActiveTextColor='#3092F8'
					tabBarUnderlineStyle={{backgroundColor:'#3092F8'}}
					tabBarTextStyle={{fontSize:18}}
					//initialPage={this.state.runCount == 0 ? 1 : 0}
					page={this.state.count == 0 ? 1 : 0}
					tabBarPosition='overlayTop'>`
I use page props in my app, but when count= 0, page=1, ScrollableTabView goto page(1), but it doesn't render the content

**Comment by windhost** [comment]
I have solved it.

**Comment by Calvin92** [comment]
How did u solve it ? If the initialPage does not equal to 0, the content will not show~

**Comment by windhost** [comment]
Set initialPage to 0, but only when count = 1 , render it.
