### ISSUE TITLE
scrollView.scrollTo not working on Android

### ISSUE THREAD

**Issue by gmlion** [skv-headless/react-native-scrollable-tab-view#509]
Hi,

react-native 0.39.2
react-native-scrollable-tab-view at master branch

the scrollTo function doesn't seem to be working for me. I'm using the initialPage property to set the scroll position.

In componentDidMount() of index.js, **using a setTimeout() with 0 delay instead of InteractionManager.runAfterInteractions() seems to be working**, but I'm not sure what the problem may be.

**Comment by skv-headless** [comment]
You can send PR. I don't know actually what should be here.

**Comment by skv-headless** [comment]
Probably fixed in master.

**Comment by Dictory** [comment]
I have same issue. 
I had react-native 0.45.1 but was extremely slow on android. I downgrade to 0.38 lags gone, but now have that problem: null is not object (evaluating this._scrollView.scrollTo)

**Comment by moniquealtero** [comment]
There is an available method called goToPage, you can use like this:

`if(this._scrollTab) this._scrollTab.goToPage(2)`.

Hope it helps.
