### ISSUE TITLE
RefreshControl ListView not working

### ISSUE THREAD

**Issue by trongan** [skv-headless/react-native-scrollable-tab-view#515]
I use ListView component inside ScrollableTabView, but the RefreshControl not working ok. If i set  locked  property is true then RefreshControl working OK. 
I need help, thanks.

**Comment by skv-headless** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/issues/179#issuecomment-192723122 ?

**Comment by vonovak** [comment]
related [https://github.com/skv-headless/react-native-scrollable-tab-view/commit/5d8aeb1f8cc13cdfbb1bf75ea12866548f872edd](https://github.com/skv-headless/react-native-scrollable-tab-view/commit/5d8aeb1f8cc13cdfbb1bf75ea12866548f872edd)

**Comment by skv-headless** [comment]
close as duplicate
