### ISSUE TITLE
Error when run 'FacebookTabBar'

### ISSUE THREAD

**Issue by tranquang7979** [skv-headless/react-native-scrollable-tab-view#516]
Error message: `'undefined is not an object (evaluating 'this.props.tabs.map') `
I got that message after I try to run 'FacebookTabBar'
<img width="1019" alt="screenshot at jan 02 10-10-02" src="https://cloud.githubusercontent.com/assets/2139635/21584249/22d1054c-d0d4-11e6-8261-92b866004b51.png">

**Comment by skv-headless** [comment]
Just need to add default value for tabs. Would you like to make pull request?

**Comment by skv-headless** [comment]
FacebookTabBar is just an example. If you make PR it would be great.

**Comment by kkho** [comment]
is this solved? I get the same problem too.
