### ISSUE TITLE
Unknown named module 'react-native-scrollable-tab-view'

### ISSUE THREAD

**Issue by uragecz** [skv-headless/react-native-scrollable-tab-view#517]
After installing react-native-scrollable-tab-view locally, i am still getting this error, even if i tried to install it globally. I am writing in ES6, and i tried to import this component via - `var ScrollableTabView = require('react-native-scrollable-tab-view');` and via `import ScrollableTabView  from 'react-native-scrollable-tab-view';` too. Any tips what can cause this ? I am using:
   ```
 "react": "15.4.1",
    "react-native": "0.39.2",
    "react-native-scrollable-tab-view": "^0.7.0"
```

**Comment by uragecz** [comment]
When I try again,it works
react-native run-android

**Comment by earthWo** [comment]
i have the same problem and still not work
