### ISSUE TITLE
RefreshControl swipe bug

### ISSUE THREAD

**Issue by vance-liu** [skv-headless/react-native-scrollable-tab-view#519]
hey, guys, [here](http://makeagif.com/Q9cK7x) is the point, how to fix that?
Ios is ok, but Android. The version is v0.7.0, react-native is 0.39. By the way, my app work fine after roll back v0.6.0

**Comment by vonovak** [comment]
related [https://github.com/skv-headless/react-native-scrollable-tab-view/commit/5d8aeb1f8cc13cdfbb1bf75ea12866548f872edd](https://github.com/skv-headless/react-native-scrollable-tab-view/commit/5d8aeb1f8cc13cdfbb1bf75ea12866548f872edd)
and [https://github.com/skv-headless/react-native-scrollable-tab-view/pull/490](https://github.com/skv-headless/react-native-scrollable-tab-view/pull/490)

 best for now is to use your own fork I guess. Or my [fork](https://github.com/vonovak/react-native-scrollable-tab-view/tree/viewPagerAndButton), but I dont guarantee anything :D

**Comment by skv-headless** [comment]
Close as duplicate
