### ISSUE TITLE
Five tab view is error.

### ISSUE THREAD

**Issue by lin493369** [skv-headless/react-native-scrollable-tab-view#520]
Scrollable-tab-view is great for me.And it work fine in most scene.
But i find in android 6.0.1,when I have five tab,it shows not right.
Version:
    "react-native": "0.38.0",
    "react-native-scrollable-tab-view": "^0.7.0",

![image](https://cloud.githubusercontent.com/assets/8255169/21711684/2b244646-d42b-11e6-977c-b1b2150bb8c0.png)

Could someone tell me how to fix it.
@skv-headless

**Comment by skv-headless** [comment]
Just third tab? What if replace text or change tabs order? If you reproduce this bug on examples I will be able to take a look.

**Comment by lin493369** [comment]
Four and third tab is correct.Only five is incorrect,and five tab is fine in iOS and some other Android version.

My code is dynamic generate scroll-tab.
````
render(){
        var scrollSubViews = []
        var pageArray = this.props.pageArray

        for(var page of pageArray){
            scrollSubViews.push(<ScrollSubView tabLabel={page.name} dataName={page.name+'量'} chartData={{'data':this.props.chartData,'key':page.key}}/>)
        }
        return(
            <View style={styles.upView}>
                <ScrollableTabView tabBarUnderlineStyle={{backgroundColor:'#37b0e4'}}
                                   style={{backgroundColor:'#1a2940'}}
                                   tabBarInactiveTextColor="rgba(255,255,255,0.5)"
                                   tabBarActiveTextColor="#37b0e4"
                                   onChangeTab={()=>(this.setState({isChange:true}))}
                >
                    {scrollSubViews}
                </ScrollableTabView>
            </View>
        )
    }
````

Thank you for help.

**Comment by skv-headless** [comment]
According to the screenshot I cant say what is wrong with fifth tab, sorry.

**Comment by lin493369** [comment]
I just try to set the tabLabel from '到达' to '到达率',and it show correct.

**Comment by lin493369** [comment]
![image](https://cloud.githubusercontent.com/assets/8255169/21712165/fc41b72a-d42d-11e6-9ed0-c3a82adc4ce6.png)
/cry...

**Comment by lin493369** [comment]
I solve it by add a Blank Character after tabLabel.
/facepalm
Thanks for you Inspiration.

**Comment by skv-headless** [comment]
You are welcome 👍 😄
