### ISSUE TITLE
if initialPage value not default , the content will not show? 

### ISSUE THREAD

**Issue by tinylpc** [skv-headless/react-native-scrollable-tab-view#521]

**Comment by skv-headless** [comment]
Do you mean your custom tab bar?

**Comment by tinylpc** [comment]
```
<ScrollableTabView initialPage={0} tabBarUnderlineStyle={{backgroundColor: '#11cab0'}}
                               tabBarActiveTextColor="#991cbf" tabBarInactiveTextColor="#11cfa5">
         <Text tabLabel="React" style={{fontSize: 30}}>1111</Text>
         <Text tabLabel="Flow" style={{fontSize: 40}}>222222</Text>
         <Text tabLabel="Jest" style={{fontSize: 50}}>333333</Text>
</ScrollableTabView>
```

when the initialPage's value is 1,the Text value 222222 will not show。

**Comment by skv-headless** [comment]
android?

**Comment by tinylpc** [comment]
yes。

**Comment by skv-headless** [comment]
Try to install from master if it doesn't work there is issue for that.

**Comment by tioback** [comment]
Installing from master solved this for me. Is there a chance you can tag it, @skv-headless ?

**Comment by Calvin92** [comment]
Same issue~   what is the meaning of "install from master"?

**Comment by tioback** [comment]
Put this in your package.json:

    "react-native-scrollable-tab-view": "git+https://github.com/brentvatne/react-native-scrollable-tab-view.git#50145bf"

**Comment by antoinerousseau** [comment]
Is https://github.com/skv-headless/react-native-scrollable-tab-view/pull/534 solving this?
If so, it would be cool to have it tagged on npm :)

**Comment by antoinerousseau** [comment]
This bug happens on Android for me but not on iOS, fyi.

**Comment by antoinerousseau** [comment]
And yes, `npm i --save react-native-scrollable-tab-view@skv-headless/react-native-scrollable-tab-view#2d8213f`does fix it.
