### ISSUE TITLE
How do I center a fixed width underline on ScrollableTabView?

### ISSUE THREAD

**Issue by booboothefool** [skv-headless/react-native-scrollable-tab-view#525]
It's a dynamic style, so I'm not sure what to do. I'd like to set it to 40px no matter how long the label is.

**Comment by skv-headless** [comment]
Create custom tab bar like here https://github.com/skv-headless/react-native-scrollable-tab-view#injecting-a-custom-tab-bar and use https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/ScrollableTabBar.js .
Try set 40 here https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/ScrollableTabBar.js#L118 . 
Not sure that I can help somehow.

**Comment by samsonroy** [comment]
Could you please tell how to  set  the underline dynamic to text width.?
