### ISSUE TITLE
Android scrollabletabbar is slow and not centered

### ISSUE THREAD

**Issue by Amurmurmur** [skv-headless/react-native-scrollable-tab-view#527]
On iOS by removing:

`newScrollX = newScrollX >= 0 ? newScrollX : 0;`
and
```
const rightBoundScroll = this._tabContainerMeasurements.width - (this._containerMeasurements.width);
newScrollX = newScrollX > rightBoundScroll ? rightBoundScroll : newScrollX;
```
Tabs are centered and pretty fast on scroll, however on android they are not centered and laggy.
Please see the difference below:
iOS:
![tabs_fast_ios mov](https://cloud.githubusercontent.com/assets/8608333/21965236/e6732b86-db6c-11e6-97cf-9d971e595296.gif)

Android:
![tabs_slow mov](https://cloud.githubusercontent.com/assets/8608333/21965237/e6737d2a-db6c-11e6-988a-0b729b91cc15.gif)

I would be very kind for any support!

**Comment by skv-headless** [comment]
1) Android js engine much slower in general. In production mode it may be quite good. But one thing I guess we can do. We can migrate to native animation.
2) I like how it behave on android in the end more that iOS

**Comment by Amurmurmur** [comment]
@skv-headless Could you give a hint how to do number 1 ?
Or do you plan to implement it in the next version of the scrollable-tab component.

**Comment by skv-headless** [comment]
@Amurmurmur it would be awesome if you could do that. I've just upgraded an example so now it has native animations. Please check this post. https://facebook.github.io/react-native/docs/animations.html#input-events if you need help I will help. We definitely need this.

**Comment by skv-headless** [comment]
close for #533

**Comment by jasan-s** [comment]
Any progress on conversion  to native
