### ISSUE TITLE
ActiveTabBarText and InActiveBarText loses its color after multiple taps.

### ISSUE THREAD

**Issue by imbudhiraja** [skv-headless/react-native-scrollable-tab-view#529]
ActiveTabBarText remains same after multiple tap both active and inactive tab.

Here is my Code to reproduce the issue :  

<ScrollableTabView
          style={styles.tabGroup}
          initialPage={0}
          tabBarTextStyle={{fontSize:18}}
          tabBarActiveTextColor={"white"}
          tabBarInactiveTextColor={"gray"}
          scrollWithoutAnimation={true}
          locked={false}
          renderTabBar={() => <ScrollableTabBar />}>
            <Signup />
            <Signin />
        </ScrollableTabView>

**Comment by skv-headless** [comment]
@imbudhiraja suddenly I failed to reproduce this bug. Could you please provide video or even better if you can reproduce this bug on one of the examples.

**Comment by skv-headless** [comment]
Please reopen with separate project or pull request to examples showing this bug otherwise I cant take a look at it.
