### ISSUE TITLE
How can I free up memory ?

### ISSUE THREAD

**Issue by Calvin92** [skv-headless/react-native-scrollable-tab-view#530]
HI, I am confused about how to release memory.  When I render more than 10 tabs, and under every tab, there are hundreds of items and each item contains an image and some text. However, along with a growing number of items，My phone gets frozen～～！～

So, my question is how can I unmount the component behind the current view?  Or, can u give me some other solutions to solve my problem?

Thanks~

**Comment by skv-headless** [comment]
I actually never used with such big number of tabs. You can try to set handle `onChangeTab` like here https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/DynamicExample.js#L62.
But it should work fine by default I think. If you can investigate what is the problem it would be awesome.

**Comment by Calvin92** [comment]
Oh,  many thanks for your reply. I am now using Samsung Galaxy S3 (Android 4.3) to test my app that shows a lot of news items. However, after I loaded more than about 100 items,  image view fail to render, but text is okay.I am not sure the problem cause by react-native-scrollable-tab-view, but when I check the memory usage, it is not very satisfactory(200MB/1GB).

Looking forward to your reply, thank u~

**Comment by skv-headless** [comment]
Cant say anything. Will be waiting for your progress.

**Comment by philberg** [comment]
@skv-headless I too would like to understand if this is possible.

In my case, I have a `react-native-camera` view inside of one of the tabs.  Once the tab is mounted, the camera stays on regardless of which tab you're one.  I tried to add a prop that changed `onChangeTab` and caused a conditional render, but it doesn't seem to be working

**Comment by philberg** [comment]
@skv-headless 

#### UPDATE
I was able to get it to work by using a `setState` within the child tab to conditionally render the camera component.

The biggest issue was that I'm using `react-redux` with the `connect` method, requiring me to use 
`{ withRef: true }` in the connect options, and also 
`ref={(child) => (this.children[1] = child.getWrappedInstance())}` for the ref

How much work would it be to add an option to this component to only keep the visible tab in memory?  I realize this means you do lose the scrolled position of each tab

**Comment by skv-headless** [comment]
Probably it is doable but I guess most of users don't need this behaviour. Also as you said you can do it manually. So I'm afraid to implement it. So if you not working on it I will close issue.

**Comment by booboothefool** [comment]
@philberg Could you explain like I'm 5 how you got this to work? I'm going to see if it helps my performance (lots of tabs with lists).

https://github.com/aksonov/react-native-router-flux/issues/1659#issuecomment-284635385
