### ISSUE TITLE
initial scroll value always 0

### ISSUE THREAD

**Issue by br4nnigan** [skv-headless/react-native-scrollable-tab-view#531]
seems to be that this scroll event in renderScrollableContent() is initially fired with an offsetX value of 0 causing the scroll view to render at 0 position despite initialPage being set and all:

    onScroll={(e) => {
        const offsetX = e.nativeEvent.contentOffset.x;
        this._updateScrollValue(offsetX / this.state.containerWidth);
    }}

It's also not being fired on scroll, so it's basically only breaking the component. I'm having this on ios, android not tested.

**Comment by skv-headless** [comment]
Can you reproduce this on examples? It is working fine there.

**Comment by Kaishley** [comment]
I am having the same problem on **android only**.

I have 2 tabs.
When setting initialPage to 1,
- In the TabBar, tab 1 is selected. (correct)
- In the 'content' page, page 0 is displayed. (wrong)

When I try to scroll horizontally, the TabBar snaps to tab 0.

![initialpage android issue](https://cloud.githubusercontent.com/assets/7120747/22235608/112b8de2-e21a-11e6-9f22-67b7f55456d5.gif)

**Comment by shahen94** [comment]
+1

**Comment by skv-headless** [comment]
Hope it is fixed https://github.com/skv-headless/react-native-scrollable-tab-view/commit/fc7b1c40c38e1c41f0bc6d47eb9cafb8171af77e
