### ISSUE TITLE
Migrate to native animation

### ISSUE THREAD

**Issue by skv-headless** [skv-headless/react-native-scrollable-tab-view#533]
It would be awesome if you could do that. I've just upgraded an example so now it has native animations. Please check this post. https://facebook.github.io/react-native/docs/animations.html#input-events if you need help I can help. We definitely need this.

**Comment by krailler** [comment]
Up!

**Comment by krailler** [comment]
@skv-headless How you use native animation?

**Comment by adriansoghoian** [comment]
@skv-headless Can you please share an example where you updated it to use native animations? Thanks!

**Comment by jasan-s** [comment]
what does it use for animation currently?

**Comment by sangotaro** [comment]
I have implemented a native animation version similar to the example.
https://github.com/sangotaro/react-native-scrollable-tab-view/commit/c400d295f3cfe24b632004359b90e1e6f0e2c4fd

**Comment by skv-headless** [comment]
@sangotaro looks good. Could you please make a pull request?

**Comment by sangotaro** [comment]
@skv-headless Thanks for the reply. I sent PR.

**Comment by jasan-s** [comment]
Is this change  to animated for performance reasons?

**Comment by skv-headless** [comment]
@jasan-s yes, just performance reason. Now in master, thanks for @sangotaro
