### ISSUE TITLE
How can I eliminate this line

### ISSUE THREAD

**Issue by wujunchuan** [skv-headless/react-native-scrollable-tab-view#539]
When I  use react-native-scrollable-tab-view component,i can't deal this annoying line

![one pixel height](https://cloud.githubusercontent.com/assets/7511631/22397793/64c074d4-e5b4-11e6-9e5b-72db5f4c6687.png)

I don't have any border in styles.what cause like this?

```jsx
            <ScrollableTabView
                style={{marginTop: 64}}
                initialPage={0}
                tabBarBackgroundColor="#75A5F6"
                tabBarTextStyle={{color:'#FFFFFF',fontSize:14}}
                tabBarUnderlineStyle={{backgroundColor:'#FFFFFF',height:2}}
                renderTabBar={() => <DefaultTabBar tabStyle={{paddingBottom:0}}/>}
            >
                .....
            </ScrollableTabView>

```

**Comment by skv-headless** [comment]
Stackoverflow is better place for this question. Personally I think it is not from `react-native-scrollable-tab-view`. You can try inspector to find that out.

**Comment by jchesne** [comment]
This line is in react-native-scrollable-tab-view  : 
https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/DefaultTabBar.js#L102
You can remove it from your custom tabBar **DefaultTabBar**
