### ISSUE TITLE
Tab underline doesn't stick with the previously clicked tab on ScrollableTabBar

### ISSUE THREAD

**Issue by Yogi1994** [skv-headless/react-native-scrollable-tab-view#540]
On ScrollableTabBar when I tap on the tab the underline is visible on the previously tapped tab. 
This is happening on the non-debug mode. but when I am trying to debug line by line it is working correct.

**Comment by skv-headless** [comment]
Can you record the video? I've never met such problem.

**Comment by Yogi1994** [comment]
sorry man it was due to some code change now i fixed it. not an issue of your plugin. thanks for the quick response.
