### ISSUE TITLE
Need tap twice in order to change focus on Button or TextInput inside scrollabletabview

### ISSUE THREAD

**Issue by fadlifebriansyah** [skv-headless/react-native-scrollable-tab-view#544]
Hi guys, 

What I have done : 

adding 
keyboardShouldPersistTaps={true} keyboardDismissMode='on-drag'
inside ScrollView

and also I adding keyboardShouldPersistTaps={true} keyboardDismissMode='on-drag'
inside ScrollableTabView

<ScrollableTabView
		  keyboardShouldPersistTaps={true}
		  keyboardDismissMode='on-drag'
		  style={{marginTop: 65}}
		  renderTabBar={()=><DefaultTabBar />}
		  tabBarPosition='bottom'
		  onChangeTab={this.refreshListView.bind(this)}>

<ScrollView keyboardShouldPersistTaps={true} keyboardDismissMode='on-drag' tabLabel='Create Invoice' style={{flex: 1}}>

but it really seems not working at all, didnt get any change. I still should tap twice, any idea?

**Comment by dgruseck** [comment]
Hi,

you can add props to the ScrollableTabView with contentProps.
`contentProps={{ keyboardShouldPersistTaps: 'always',  keyboardDismissMode: 'on-drag' }}`

always for RN >= 0.40 true for RN < 0.40

David

**Comment by fadlifebriansyah** [comment]
Thanks David! It works really nice

**Comment by luis080791** [comment]
Thanks David! It works nice !

**Comment by sfdux** [comment]
good! It works nice!
