### ISSUE TITLE
Update badge in tab from children

### ISSUE THREAD

**Issue by quangtruong16994** [skv-headless/react-native-scrollable-tab-view#546]
I have badge in CustomTabbar, how can I update badge from ListChat or ListComment? tabNoti is the list of badge show in Tab

`<ScrollableTabView
                locked={false}
                ref={(tabs) => this.tabList = tabs}
                initialPage={0}
                tabBarPosition="bottom"
                renderTabBar={() => <CustomTabBar tabName={["Chat", "Comment", "Setting"]} tabNoti={[this.state.chatNoti, this.state.commentNoti, 0]} />}
                tabBarActiveTextColor="#ffaa00"
                tabBarUnderlineStyle={[{ backgroundColor: "#ffaa00" }]}>
                <ListChat tabLabel='comment'  navigator={this.navigator} />
                <ListComment tabLabel='comments' navigator={this.navigator}  />
                <Setting tabLabel='gears' navigator={this.navigator} />
            </ScrollableTabView>`

![screen shot 2017-02-09 at 5 14 52 pm](https://cloud.githubusercontent.com/assets/16751293/22778996/95248e7c-eeeb-11e6-9f48-8ea00c02a848.png)

Sorry for my English

**Comment by leizard** [comment]
Hi @quangtruong16994, do you have any solution for this yet ?
