### ISSUE TITLE
initialPage={this.state.tabNum},when I change this.state.tabNum,page not rendering

### ISSUE THREAD

**Issue by jinleli** [skv-headless/react-native-scrollable-tab-view#547]
Hi I am using RN version 0.41.2,react-native-scrollable-tab-view 0.7.2
I want to achieve when the user login  initialPage={2},If the user is not logged in initialPage={0}.I set initialPage={this.state.tabNum},then I  use componentWillMount() to change this.state.tabNum,but page not rendering

**Comment by Amurmurmur** [comment]
Hi, make sure you set `prerenderingSiblingsNumber` prop for the `scrollabletabview` accordingly.
Try to set `prerenderingSiblingsNumber` to 2 for instance, if you have 3 tabs and want user to access 2nd tab upon successful login.

**Comment by jinleli** [comment]
@Amurmurmur  I set prerenderingSiblingsNumber={2},Nothing happened，Do I use the wrong way?

**Comment by sksahil030** [comment]
@skv-headless can you please help regarding this issue

**Comment by skv-headless** [comment]
If you want to change tab programmatically you can do like this https://gist.github.com/skv-headless/3a1391d3b52736e7367eb33c3bc1a52b#file-gistfile1-js-L30

**Comment by sksahil030** [comment]
@skv-headless it worked..thanks alot

**Comment by jinleli** [comment]
@sksahil030  @skv-headless thanks alot

**Comment by kubilaytural** [comment]
Try this. It worked. Ideal for changing first pages.

componentDidMount() {
setTimeout(() => this.scrollableTabView.goToPage(1), 300);
}
...
.....
...
<ScrollableTabView
ref={(ref) => { this.scrollableTabView = ref; }}
