### ISSUE TITLE
Underline color doesn't change

### ISSUE THREAD

**Issue by davidgit75** [skv-headless/react-native-scrollable-tab-view#548]
Hello, I am using this component, and it is great, but I have tried some times change underline color but I haven't did it fine.
I have used on ScrollableTabView.

tabBarUnderlineColor="#FFFFFF"
tabBarUnderlineStyle={{ color: "#FFFFFF" }}
tabBarUnderlineStyle={{ borderBottomColor: "#FFFFFF" }}

And underline color keep with default color.
Excuse me if this is a stupid question but I haven't found the option.
Thanks

**Comment by skv-headless** [comment]
`tabBarUnderlineStyle={backgroundColor: 'black' }` I think should work.

**Comment by davidgit75** [comment]
@skv-headless Thanks for the help, this worked perfectly.
