### ISSUE TITLE
tabBarTextStyle not working in Android?

### ISSUE THREAD

**Issue by darrenchiu** [skv-headless/react-native-scrollable-tab-view#549]
I was able to customize the font of tabBar by passing in the props to tabBarTextStyle. However, this doesn't apply to android. Is this intended or because of other limitation on react native?

Thanks a lot.

**Comment by skv-headless** [comment]
It should work the same way. What exact style doesn't work?

**Comment by darrenchiu** [comment]
i am trying font family...

**Comment by skv-headless** [comment]
It is pretty straightforward https://github.com/skv-headless/react-native-scrollable-tab-view/blob/ee5d99950fad9c4c1129d029d7bfaea130df72d1/DefaultTabBar.js#L50. If it is working for text it should work here.

**Comment by sergiulucaci** [comment]
I confirm the same issue, @skv-headless are you open to review a PR that might fix this?
