### ISSUE TITLE
Android top space

### ISSUE THREAD

**Issue by jjamet** [skv-headless/react-native-scrollable-tab-view#550]
On the android emulator, I have a blank top space. How can I remove it ?

![top_space](https://cloud.githubusercontent.com/assets/9111072/23061510/7bd8b994-f502-11e6-9c99-e48306aa2a6f.png)

**Comment by Parrryy** [comment]
Have you tried using the inspector to see if it's a padding or margin issue?

**Comment by skv-headless** [comment]
Please reopen with separate project or pull request to examples showing this bug otherwise I cant take a look at it.
