### ISSUE TITLE
Very slow transition on IOS when clicking on Tab

### ISSUE THREAD

**Issue by anahitsk123** [skv-headless/react-native-scrollable-tab-view#551]
Don't know if anyone experiencing the same issue or not. Animation transition from on tab to another on click is extremely slow.

I am using react-native 0.40, if that makes any change.

**Comment by skv-headless** [comment]
I guess you enabled slow animations in simulator http://stackoverflow.com/a/8624549/1410905

**Comment by anahitsk123** [comment]
Thanks. I was that. Really appreciate.

**Comment by skv-headless** [comment]
You are welcome.
