### ISSUE TITLE
Refrain from using StaticContainer

### ISSUE THREAD

**Issue by coodoo** [skv-headless/react-native-scrollable-tab-view#552]
According to [this discussion here](https://github.com/skv-headless/react-native-scrollable-tab-view/blob/ee5d99950fad9c4c1129d029d7bfaea130df72d1/SceneComponent.js#L6), `StaticContainer` was renamed and it was never meant to be used directly, just confirmed it's now breaking the app with the latest react native build (from `master`).

Maybe it's a good time to find a replacement for it?

**Comment by skv-headless** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/pull/545

**Comment by coodoo** [comment]
Nice to know there's a fix in place, good job!

**Comment by skv-headless** [comment]
Thanks anyway. Please ping me if I forget to merge after release.

**Comment by f0rr0** [comment]
@skv-headless I think it's completely removed in 43. Why not use the implementation directly https://github.com/skv-headless/react-native-scrollable-tab-view/pull/587

**Comment by joshfriend** [comment]
@f0rr0 `StaticContainer` is [still present in 0.43](https://github.com/facebook/react-native/blob/v0.43.0-rc.4/Libraries/Components/StaticContainer.react.js), but it's now private (which is the problem here). I do like your solution much better, use of private APIs == bad.

**Comment by nehvaleem** [comment]
ummm, after updating to 0.43 it seems to doesnt work for me. I've got an error about StaticContainer. 

Could someone please tell me what is going on?

**Comment by f0rr0** [comment]
@nehvaleem it should work on master. Wait till https://github.com/skv-headless/react-native-scrollable-tab-view/commit/23b3a32761e1be7be6760e7f6a71e54095acbe15 is released
