### ISSUE TITLE
Dynamic tab change rendering blank view.

### ISSUE THREAD

**Issue by svallen** [skv-headless/react-native-scrollable-tab-view#556]
I have a dynamic tab change from one level to another.  When the new tab system changes over the tab updates itself using page={0} however, the content associated is not loading itself.

<ScrollableTabView renderTabBar={() => <MaskTabBar showMask={false} maskMode='light'  />} tabBarBackgroundColor='#f8f8f8' tabBarActiveTextColor='#397de6' tabBarUnderlineStyle={{backgroundColor:'#397de6'}} page={0} >
	< Test tabLabel="Test 1" />
	< Test tabLabel="Test 2" />
	< Test tabLabel="Test 3" />
</ ScrollableTabView>

Using latest master version as on this mornings download. using iOS simulator to test.

When I click on the tabs the show the data.

Any help would be great! Thanks!

![screen shot 2017-02-27 at 9 18 18 am](https://cloud.githubusercontent.com/assets/6169781/23364605/b4845ffa-fccd-11e6-8b07-d3f559ae7b32.png)

**Comment by skv-headless** [comment]
O would not recommend to use `page` property please try https://github.com/skv-headless/react-native-scrollable-tab-view#changing-between-tabs

**Comment by svallen** [comment]
Awesome. I think that worked. I thought I had tried that before and it hadn't functioned as I wanted it to, but seems to be working correctly now.  Appreciate the help.

**Comment by skv-headless** [comment]
You are welcome 🙂
