### ISSUE TITLE
border bottom width/color not working

### ISSUE THREAD

**Issue by dsah** [skv-headless/react-native-scrollable-tab-view#557]
There is a border between tab and its content. No matter what I do, border colour and BorderBottomWidth never get changed.

**Comment by skv-headless** [comment]
try `tabBarUnderlineStyle={{backgroundColor: 'red', height: 10}}`

**Comment by dsah** [comment]
not exactly, please check the border bottom in screenshot, i want to change this border color.
![menu](https://cloud.githubusercontent.com/assets/7278917/23485606/4493ff10-ff30-11e6-8e9a-1c5f7716217c.png)

**Comment by Parrryy** [comment]
Is that not a padding or margin on the overall border?

**Comment by skv-headless** [comment]
maybe `style={{borderWidth: 0}}`?

**Comment by dsah** [comment]
neither padding nor margin worked also style={{borderWidth: 0}} didnt worked.

**Comment by dsah** [comment]
i have container background black and haven't set padding or margin on tabbar and even setting borderWidth 0 doesn't work.

**Comment by brandensilva** [comment]
@skv-headless @dsah 

This is still an issue. It's right here:

```
container: {
    height: 50,
    borderWidth: 1,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderColor: '#ccc',
  },
```

Either we should remove those default colors or we should add an option to change it. This gray color looks terrible on certain color combinations.

**Comment by elios264** [comment]
You need to style the default tabbar:

```
import ScrollableTabView, { DefaultTabBar } from 'react-native-scrollable-tab-view';
const renderTabBar = props => (<DefaultTabBar {...props} style={{ borderBottomWidth: 0 }} />);

        <ScrollableTabView
          renderTabBar={renderTabBar} />
```
