### ISSUE TITLE
Use images instead of tab titles

### ISSUE THREAD

**Issue by yantakus** [skv-headless/react-native-scrollable-tab-view#563]
I tried to use my own `renderTab` method and pass image path as `tabLabel` property, then `<Image source={require(name)} />` inside the `renderTab` method. But what I get is just white screen and the following error in the console:

```
Warning: Failed prop type: The prop `title` is marked as required in `Button`,
but its value is `undefined`.
```

When I specify the title, it is rendered as text inside the button and there's no image at all.

Also tried to pass `tabLabel={require('../../assets/images/icon-binoculars.png'})` and just `<Image source={name} />` but then I get the following error:

```
(node:19551) UnhandledPromiseRejectionWarning:
Unhandled promise rejection (rejection id: 24000):
SyntaxError: SyntaxError /Users/yan/Projects/6March/assets/images/icon-binoculars.png:
Unexpected character '�' (1:0)
```

Seems it treats the image as regular file, not as binary. Any ideas?

**Comment by skv-headless** [comment]
Can you make separate project showing your problem?

**Comment by yantakus** [comment]
Sorry for not closing the issue before. I've already resolved it.

**Comment by eduarifrahmanhakim** [comment]
@yantakus how u can closing the issue? I face the issue and not yet solved
