### ISSUE TITLE
Adding badge or Icon after tabLabel

### ISSUE THREAD

**Issue by saudpunjwani101** [skv-headless/react-native-scrollable-tab-view#568]
So is there a way to add a badge or Icon with the tabLabel?

<ScrollableTabView style={{backgroundColor:'#fafafa', marginTop:30}}
                            tabBarTextStyle={{fontSize:13}}
                            tabBarActiveTextColor="black"
                            tabBarUnderlineStyle={{backgroundColor:"black"}}>

          <ShowStats tabLabel={"Stats"}
                    data={this.props.data}/>
          <Notifications tabLabel={"Notifications"}
                          navigator={this.props.navigator}
                          userID={this.props.userID}/>

        </ScrollableTabView>

Is there a way I can add those components on a tab like this

          <Notifications tabLabel={"Notifications" + <Icon name="iso-people"/>}
                                   navigator={this.props.navigator}
                                   userID={this.props.userID}/>

**Comment by juanmanuelarze** [comment]
With tab label no, but i do that:

See the FacebookTabExample in this repo.
There you have a way to customize the tabBar.
First i suggest you reproduce the facebook tabbar example, next clean what do you dont need.

For Icons i set the tab label like this 
`tabLabel="home:Inicio"`
home is the icon name of material icons and Inicio is the tab name below icon

Then in the render method of your custom tab component, split the tab label
`var nameIcon = tab.split(":");`

And use it like this

`return(
            <TouchableOpacity key={tab} onPress={() => this.props.goToPage(i)}>
              <Icon
                name={nameIcon[0]}
                size={30}
                color={color}
                ref={(icon) => { this.tabIcons[i] = icon; }}
              />;
            <Text>
              {nameIcon[1]}
            </Text>
          </TouchableOpacity>
        );`

and for the badge use 
https://github.com/yanqiw/react-native-icon-badge
this

and in your code with a `if` set the badge to respective icon.

I dont like this method, but i was need do it for the job.

**Comment by skv-headless** [comment]
or you can use `renderTab` property like here https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/DynamicExample.js#L61

**Comment by linigithub** [comment]
tried this renderTab - cannot read property  foreach of undefined error
