### ISSUE TITLE
How to pass data to the next tab?

### ISSUE THREAD

**Issue by huangxiaohao** [skv-headless/react-native-scrollable-tab-view#569]
hello! There are some problems in my project. I have two tab in my view, and I want to pass data to my on of tab like this:
![image](https://cloud.githubusercontent.com/assets/13390763/23979959/bd0c4bde-0a37-11e7-8d19-3ff0a6977c22.png)

I want to pass a data to the CheckProjectDescribe tab, 
How to do that? thank you very much!!!

**Comment by huangxiaohao** [comment]
![image](https://cloud.githubusercontent.com/assets/13390763/23980138/f14e9090-0a38-11e7-9bd7-a7f1254a7d8f.png)

**Comment by juanmanuelarze** [comment]
In the parent component of the tabs you must make the state changes, example:
`
myFunction(){
     this.setState({
        myVar: true
     });
}

...
<CheckProjectDescribe tabLabel="aaa" myVar={this.state.myVar}>
...
`

then in your tab component

`
componentWillReceiveProps(nextProps) {

//doSomething

  }

`

**Comment by huangxiaohao** [comment]
@juanmanuelarze Thank you so much!!!  I got this data in my tab component, but when I first enter into the tab component ,the view is empty, unless when I enter into the tab "bbb" then into "aaa" ,
the data show! like this

In the parent component
`    constructor(props) {
        super(props);
        this.state = {
            describeContent:''
        };
    }

    componentWillMount() {
        const { content } = this.props;
        this.setState({
            describeContent: content
        });
    }`
`<ScrollableTabView
                    tabBarUnderlineStyle={{backgroundColor: '#3af',height:2}}
                    tabBarBackgroundColor='#FFFFFF'
                    tabBarActiveTextColor='#3af'
                    tabBarInactiveTextColor='#666'
                    tabBarTextStyle={{fontSize: 14,marginTop:5}}
                >
                    <CheckProjectDescribe tabLabel="aaa" describeContent={this.state.describeContent}/>
                    <CheckProjectFile tabLabel="bbb" />
                </ScrollableTabView>`

in tab component:
`constructor(props) {
        super(props);
        this.state = {
            containerTxt:''
        };
    }

    componentWillReceiveProps(describeContent) {
        console.log(describeContent.describeContent);
        this.setState({
            containerTxt:describeContent.describeContent
        });
    }


    render() {
        return (
            <View style={styles.container}>
                <Text>{this.state.containerTxt}</Text>
            </View>
        );
    }`

I think maybe is the`componentWillReceiveProps` problem
I want to know how to show the data when I first enter into the tab component
thank you  soooo much!!!

**Comment by juanmanuelarze** [comment]
ComponentWillReceiveProps does not run the first time, only when a change in the value of a parameter occurs, use componentDidMount for the first time.

ComponentWillMount is executed before the render, do not use setState there, setState calls to re-render on a (in this case) on a non-rendered component yet.

ComponentDidMount is executed after the render, there you can use a setState

I suggest you read the lifecycle of reacting the native components
Https://facebook.github.io/react/docs/react-component.html

:dango:

**Comment by huangxiaohao** [comment]
@juanmanuelarze I have already try it with  `componentDidMount`  before I reply you ,and  I try it again just now, but it have a problem in there 
`Cannot read property 'describeContent' of undefined`
![image](https://cloud.githubusercontent.com/assets/13390763/23982725/3c65cfe2-0a4a-11e7-965a-5d9cfb37b841.png)

and I change my code like this

In the parent component:
`constructor(props) {
        super(props);
        this.state = {
            describeContent: ''
        };
    }`
`componentDidMount() {
        const { content } = this.props;
        this.setState({
            describeContent: content
        });
    }`

in tab component:
`constructor(props) {
        super(props);
        this.state = {
            containerTxt: ''
        };
    }`

`componentDidMount(describeContent) {
        this.setState({
            containerTxt:describeContent.describeContent
        });
    }`

**Comment by huangxiaohao** [comment]
@juanmanuelarze I have change my code like this 

In the parent component:
`constructor(props) { super(props); this.state = { describeContent: '' }; }`
`componentDidMount() { const { content } = this.props; this.setState({ describeContent: content }); }`

in tab component:
```
componentWillReceiveProps(describeContent) {
        this.setState({
            containerTxt:describeContent.describeContent
        });
    }
```

It works!!! strangely!!!!!
And  thank you soooo much !!!!!

**Comment by juanmanuelarze** [comment]
It is a pleasure 😁
