### ISSUE TITLE
StaticContainer is part of the internal API

### ISSUE THREAD

**Issue by sangotaro** [skv-headless/react-native-scrollable-tab-view#570]
Latest master of react-native has StaticContainer.react.js instead of StaticContainer.js. 
So StaticContainer will be unusable soon, it is necessary to modify the relevant part. https://github.com/facebook/react-native/issues/12395

**Comment by skv-headless** [comment]
Thanks. https://github.com/skv-headless/react-native-scrollable-tab-view/pull/545. Just waiting for stable version.
