### ISSUE TITLE
Consider adding `disabled` prop for children

### ISSUE THREAD

**Issue by GlebkaF** [skv-headless/react-native-scrollable-tab-view#577]
Right now only one children's property being handling by scrollable-tab-view it is `tabLabel`.
Consider adding `disabled` prop which would prevent child and it's tab from render. 
We could just change _children method a bit:
```js
_children(children = this.props.children) {
    return React.Children.map(children, (child) => child).filter(({props}) => !props.disabled);
}
```

**Comment by jasongaare** [comment]
You could rather wrap the child like this:

    { !disabled && <ChildComponent /> }

Then it won't be based as a child to the ScrollableTabView. Perhaps cumbersome if you wanted to wrap all of your components like that.

Alternatively, you could use a `.map` function in a similar way to create an array of components in your render method, then pass that array as the sole child of the ScrollableTabView

**Comment by skv-headless** [comment]
@GlebkaF reopen if @jasongaare answer doesn't work for you.
