### ISSUE TITLE
react-native-swiper in react-native-scrollable-tab-view cant scroll

### ISSUE THREAD

**Issue by KurenaiKami** [skv-headless/react-native-scrollable-tab-view#581]
`<ScrollableTabView
				tabBarPosition= "top"
				renderTabBar={ () =>  <DefaultTabBar   /> }
				tabBarUnderlineStyle = {styles.underline}
				tabBarTextStyle = {styles.tabText}
			>

			<View tabLabel='home'>
				<Swiper style={styles.wrapper} >
					<View style={styles.slide1}>
						<Text style={styles.text}>Hello Swiper</Text>
					</View>
					<View style={styles.slide2}>
						<Text style={styles.text}>Beautiful</Text>
					</View>
					<View style={styles.slide3}>
						<Text style={styles.text}>And simple</Text>
					</View>
				</Swiper>
			</View>

			</ScrollableTabView>`
just like this. when i scroll the screen, swiper is not work.  i dont know how to change

**Comment by KurenaiKami** [comment]
react-native version is 0.42.3

**Comment by skv-headless** [comment]
you can try to lock `react-native-scrollable-tab-view` on the tab with a swiper. also there is an issue for that #361

**Comment by KurenaiKami** [comment]
thanks
