### ISSUE TITLE
Don't trigger onChangeTab when change the page prop ?

### ISSUE THREAD

**Issue by KGALLET** [skv-headless/react-native-scrollable-tab-view#582]
Hi, 

In my app, I've got a vertical ScrollView which scroll to a pre-calculated position using the `onChangeTab` props when I press tabs.
This works well and as I want. It called the `goToPage` function and do the job.

I also wanted to change the active tab when I scroll on the same vertical scrollview, and to do that, I planned to use the `page` prop. When I reach the position on my scrollview, I update the state :
```
this.setState({ activeTab: xxx})
```
And I pass it to the prop page `page={ this.state.activeTab }`
The fact is, when the `page` prop is updated, the onChangeTab is triggered, even if you don't want to.

Is there a way to update the activeTab (using the page prop?) without triggering the `onChangeTab` function? 

I think its possible by modifying code here (goToPage function):
```
this.updateSceneKeys({
      page: pageNumber,
      **callback: this._onChangeTab.bind(this, currentPage, pageNumber),**
    });
```

Thx

**Comment by KGALLET** [comment]
Ok I created 
```
  goToPageAndDontTriggerOnChangeTab(pageNumber, animated = !this.props.scrollWithoutAnimation) {
    const offset = pageNumber * this.state.containerWidth;
    if (this.scrollView && this.scrollView._component && this.scrollView._component.scrollTo) {
      this.scrollView._component.scrollTo({x: offset, y: 0, animated, });
    }

    const currentPage = this.state.currentPage;
    this.updateSceneKeys({
      page: pageNumber,
    });
  },
```

then in my component : 
```
    <ScrollableTabView
                tabBarBackgroundColor="white"
                tabBarActiveTextColor={ MAIN_COLOR }
                tabBarUnderlineStyle={ styles.underlineStyle }
                style={ styles.scrollableTabContainer }
                onChangeTab={ this._handleChangeTab }
                ref={ (tabView) => { this.tabView = tabView } }
              >
```
then I only do 
```
  this.tabView.goToPageAndDontTriggerOnChangeTab({
        page: 1,
      })    
```

**Comment by skv-headless** [comment]
Did you solve it?

**Comment by KGALLET** [comment]
@skv-headless I didn't manage to. In fact, I modified your code and create a goToPageAndDontTriggerOnChangeTab function.
```

goToPageAndDontTriggerOnChangeTab(pageNumber, animated = !this.props.scrollWithoutAnimation) {
    const offset = pageNumber * this.state.containerWidth;
    if (this.scrollView && this.scrollView._component && this.scrollView._component.scrollTo) {
      this.scrollView._component.scrollTo({x: offset, y: 0, animated, });
    }

    const currentPage = this.state.currentPage;
    this.updateSceneKeys({
      page: pageNumber,
      callback: () => console.log('do nothing'),
    });
  },
```

So the animation of the underline, and the activeTab was well configured.
But now, the behavior is that, when the <Animated.ScrollView> scroll, then `_onMomentumScrollBeginAndEnd` function is called and then the `_updateSelectedPage`.

And this last function call ```
 this.updateSceneKeys({
      page: localNextPage,
      callback: this._onChangeTab.bind(this, currentPage, localNextPage),
    });
```

If I change the callback, then component is totally broken.

**Comment by KGALLET** [comment]
Any ideas ? @skv-headless
