### ISSUE TITLE
swiper is not work 

### ISSUE THREAD

**Issue by KurenaiKami** [skv-headless/react-native-scrollable-tab-view#584]
<ScrollableTabView
				tabBarPosition= "top"
				renderTabBar={ () =>  <DefaultTabBar   /> }
				tabBarUnderlineStyle = {styles.underline}
				tabBarTextStyle = {styles.tabText}
			    locked={true}
			>
			<Swiper style={styles.wrapper} height={60} >
				<View style={styles.slide1}>
					<Text style={styles.text}>Hello Swiper</Text>
				</View>
				<View style={styles.slide2}>
					<Text style={styles.text}>Beautiful</Text>
				</View>
				<View style={styles.slide3}>
					<Text style={styles.text}>And simple</Text>
				</View>
			</Swiper>
			<View tabLabel='OCG'>
			</View>
			<View tabLabel='视频'>
			</View>

i set locked is ture, tabview cant scroll swiper can, but  if is false Swiper cant scroll tabview cant .

**Comment by skv-headless** [comment]
dup #361
