### ISSUE TITLE
ScrollableTabBar jumps when transitioning

### ISSUE THREAD

**Issue by jarnell** [skv-headless/react-native-scrollable-tab-view#588]
When using ScrollableTabBar and selecting a tab while the active tab label is not on the screen, the tab bar jumps to the active tab before starting the transition.

Example: (I activated slow animations to make it clearer)

![tabbar](https://cloud.githubusercontent.com/assets/1726633/24506439/cbd940b4-155d-11e7-8ae4-71dde862a6dc.gif)

Transition from Dogs -> Frogs -> Elephants looks good, but back to Dogs from Elephants makes the tab bar jump.

**Comment by valeriik** [comment]
The same...

**Comment by skv-headless** [comment]
It is the same in youtube app so I don't think that it is critical. If you create a pull request I will take a look

**Comment by jarnell** [comment]
Are you sure? I just checked the YouTube app on iOS and the only place I could find a tab bar was on channel pages where the transition doesn't jump like this. I'll look into it and create a PR if I find a simple solution.

**Comment by valeriik** [comment]
On android in YouTube apk "bug" exists but as the component is a part of native OS it's almost imperceptible, but here (react native + javascript) it looks more like a bug :)
