### ISSUE TITLE
With Redux

### ISSUE THREAD

**Issue by diegorodriguesvieira** [skv-headless/react-native-scrollable-tab-view#592]
Hello friends, I would like to know if anyone has any examples of how to connect-native-scrollable-tab-view with redux, I have no idea how to start... would be very grateful if someone can help me...

Thank you

**Comment by nmquebb** [comment]
Slap a `ref={(tabView) => { this.tabView = tabView; }}` on the <ScrollableTabView /> then inside `componentDidUpdate` look at a redux store that corresponds with the tab and `this.tabView.goToPage(this.props.reduxStore.tab)`

**Comment by skv-headless** [comment]
@diegorodriguesvieira I don't know how to help. I would love to answer to more specific question. Try to ask on stackoverflow.
@nmquebb thanks again 👍
