### ISSUE TITLE
Component only works when is the root element

### ISSUE THREAD

**Issue by aferrerallu** [skv-headless/react-native-scrollable-tab-view#593]
Hi, I was able to create a simple app that have 5 tabs and worked perfectly.
Then I wanted to put a header with a title and a search button. The idea is that it works outside scrollable tab view. Then I realized that if a put it as a child element I got a blank screen.

```
<View>
    <ScrollableTabView tabBarPosition="bottom">
        <Component4 tabLabel="tab1" />           
        <Component4 tabLabel="tab2" />
        <Component4 tabLabel="tab3" />
        <Component4 tabLabel="tab4" />
        <Component4 tabLabel="tab5" />
      </ScrollableTabView>
</View>
```

If I put the View tags I have a blank screen, removing them works perfect but I cannot put the header bar I want.
So, is there a way of using this component inside another View?

**Comment by nmquebb** [comment]
```
<View style={{ flex: 1 }}>
    <ScrollableTabView tabBarPosition="bottom">
        <Component4 tabLabel="tab1" />           
        <Component4 tabLabel="tab2" />
        <Component4 tabLabel="tab3" />
        <Component4 tabLabel="tab4" />
        <Component4 tabLabel="tab5" />
      </ScrollableTabView>
</View>
```

**Comment by skv-headless** [comment]
@nmquebb thanks.

**Comment by aferrerallu** [comment]
Thank you @nmquebb
