### ISSUE TITLE
UNMET PEER DEPENDENCY react

### ISSUE THREAD

**Issue by EmrahKK** [skv-headless/react-native-scrollable-tab-view#596]
hi, 
When I try to install with: "npm install react-native-scrollable-tab-view --save" 

I got an error;

UNMET PEER DEPENDENCY react@^0.13.0 || ^0.14.0 || ^15.0.0

I'am using;

react-native-cli: 2.0.1
react-native: 0.43.0

**Comment by skv-headless** [comment]
It is because of `react-static-container` dependency.
I guess we should do like this
https://github.com/skv-headless/react-native-scrollable-tab-view/pull/587/
and remove `react-static-container` dependency
Would you like to make a pull request?

**Comment by RailtonMatthew** [comment]
I am getting the same error.  Is there a fix yet?

**Comment by skv-headless** [comment]
fixed in master and in 0.6.4 version

**Comment by GiacomoK** [comment]
I still got the error.
