### ISSUE TITLE
UnableToResolveError in react native v0.43.1

### ISSUE THREAD

**Issue by imajean** [skv-headless/react-native-scrollable-tab-view#597]
got this after upgrading to rn 0.43.1

UnableToResolveError: Unable to resolve module `react-native/Libraries/Components/StaticContainer`

StaticContainer file is now named StaticContainer.react.js

**Comment by skv-headless** [comment]
fixed in master

**Comment by mrjoseph** [comment]
How did you fix this issue? I'm having the same problem

**Comment by skv-headless** [comment]
Just update to 0.7.4 version.
