### ISSUE TITLE
Is it possible to load Component one by one on active tab

### ISSUE THREAD

**Issue by bbhighrock** [skv-headless/react-native-scrollable-tab-view#599]
Hi,

I need to load 3 components instead of the 3 texts in the ScrollableTabView (as above src code) and I am wondering if I can load one component by one depending on the active tab. Is it possible and how to do it ?
```
<ScrollableTabView style={{ marginTop: 20, }} initialPage={1} renderTabBar={() => <ScrollableTabBar />}
            >
                <Text tabLabel='Profile'>Profile</Text>
                <Text tabLabel='Outings'>Outings</Text>
                <Text tabLabel='MyOutings'>MyOutings</Text>
              
            </ScrollableTabView>
```

**Comment by skv-headless** [comment]
Not sure that understood you? Can you be more specific about what are you going to do?

**Comment by ben-snaize** [comment]
I believe @bbhighrock wants to know if pre-load is possible and configurable. This is achieved with `prerenderingSiblingsNumber`

**Comment by bbhighrock** [comment]
Okay, I read my first comment and Indeed I wasn't that clear. So actually when tab1 is active, I want the associated component displayed but the components of tab2 and tab3 not loaded to prevent big delay in answer from the database. So I need to load components one by one depending on which tab is active.  Do you know what I mean ?

**Comment by skv-headless** [comment]
@bbhighrock  I think so. Then @ben-snaize comment is relevant and `react-native-scrollable-tab-view` should work as you described. What made you think that it is working differently?

**Comment by skv-headless** [comment]
Close for no response.
