### ISSUE TITLE
Multiple scenes in a tab

### ISSUE THREAD

**Issue by iiitmanikanta** [skv-headless/react-native-scrollable-tab-view#600]
How to navigate to multiple scenes in a tab? How to maintain multiple scenes of tabs using react native router flux?

**Comment by skv-headless** [comment]
I have no experience with react native router flux. Most likely I can't help. Sorry. But you can try to ask on stackoverflow or in react native router flux repo

**Comment by iiitmanikanta** [comment]
How to navigate through multiple scenes in a tab?
