### ISSUE TITLE
Missing tabStyle setting in index.js file

### ISSUE THREAD

**Issue by SnapluDJ** [skv-headless/react-native-scrollable-tab-view#604]
In index.js file, missing 'tabStyle' property, which will cause user can not set tabStyle.

Should add there lines:

`if (this.props.tabStyle) {
      tabBarProps.tabStyle = this.props.tabBarTabStyle;
    }`

<img width="846" alt="screen shot 2017-04-13 at 6 08 03 pm" src="https://cloud.githubusercontent.com/assets/13940065/25000584/7619020a-2074-11e7-8889-46c077f9f7ba.png">

**Comment by skv-headless** [comment]
I don't want to pass all props through main component. I would recommend to use renderTabBar.
```
<ScrollableTabView
      renderTabBar={() => <DefaultTabBar />}
      ref={(tabView) => { this.tabView = tabView; }}
 >
```

**Comment by SnapluDJ** [comment]
Thank you for your tips
