### ISSUE TITLE
UnableToResolveError: Unable to resolve module `React` from  ....../StaticContainer.js

### ISSUE THREAD

**Issue by LeesinYasuo** [skv-headless/react-native-scrollable-tab-view#615]
Hi,
how to resolve this problem?
UnableToResolveError: Unable to resolve module `React` from `/home/neal/WebstormProjects/GitHub/node_modules/react-native-scrollable-tab-view/StaticContainer.js`: Module does not exist in the module map or in these directories:

 "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-native-scrollable-tab-view": "git+https://github.com/skv-headless/react-native-scrollable-tab-view.git",
    "react-native-tab-navigator": "^0.3.3"
  },

**Comment by skv-headless** [comment]
Sorry for that.
