### ISSUE TITLE
UNMET PEER DEPENDENCY react@16.0.0-alpha.6

### ISSUE THREAD

**Issue by GiacomoK** [skv-headless/react-native-scrollable-tab-view#617]
Hi,
I am not able to install the component cause I get this error:

    +-- UNMET PEER DEPENDENCY react@16.0.0-alpha.6
    `-- react-native-scrollable-tab-view@0.7.4
        `-- UNMET PEER DEPENDENCY react@^0.13.0 || ^0.14.0 || ^15.0.0

Any help?

Thanks.

**Comment by skv-headless** [comment]
Fixed in master
