### ISSUE TITLE
Page reload on scroll

### ISSUE THREAD

**Issue by ABYARTH** [skv-headless/react-native-scrollable-tab-view#618]
Hello, 
I am building an app (android version) that requires user to send data in one page and resulting data on another page.
However after submitting the input, i am unable to view the new data on the result page without refreshing the page. The page still shows the older data and user has to refresh the page or reload the page to view latest data. 

How can i implement auto refresh while scrolling to new page. 
react-native version : 0.42.0

**Comment by skv-headless** [comment]
I can suggest few options
1) use `prerenderingSiblingsNumber={Infinity}` it will render all tab eagerly and it probably will solve your problem
2) you can handle `onEnter` event like in this example
https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/DynamicExample.js#L41
Feel free to reach me if it doesn't work.
