### ISSUE TITLE
使用了react-native-tab-navigator来做底部导航栏，然后在首页又使用了react-native-scrollable-tab-view来做tab切换   然后在tab页的第一行就使用了react-native-swiper来做图片轮播  轮播图怎么也出不来

### ISSUE THREAD

**Issue by lixiaobin0303** [skv-headless/react-native-scrollable-tab-view#620]
//react-native-scrollable-tab-view 做的tab页
    return (
      <View style={styles.container}>
        <ScrollableTabView renderTabBar={(props) => <DefaultTabBar/>}>
          <View tabLabel='热门' style={styles.center}><Hot navigator={this.props.navigator}/></View>
          <View tabLabel='专家' style={styles.center}></View>
          <View tabLabel='康复' style={styles.center}></View>
          <View tabLabel='饮食' style={styles.center}></View>
        </ScrollableTabView>
      </View>
   );

//Hot页面
return (
      <View style={styles.container}>
          <Swiper style={{height:235}} showsButtons={false} horizontal={true} loop={true} index={0} autoplay={true}>
            <View style={styles.slide1}>
              <Image source={require('./img/微信图片_20170419134307.png')} style={styles.icon}/>
            </View>
            <View style={styles.slide2}>
              <Image source={require('./img/微信图片_20170419134333.jpg')} style={styles.icon}/>
            </View>
            <View style={styles.slide3}>
              <Image source={require('./img/微信图片_20170419134342.jpg')} style={styles.icon}/>
            </View>
          </Swiper>
      </View>
    );

轮播图不显示，也不报错

**Comment by skv-headless** [comment]
Please translate to english. It doesn't work with react-native-swiper and there is issue for that.
