### ISSUE TITLE
How to add tabIcons in ScrollableTabBar

### ISSUE THREAD

**Issue by hyd00** [skv-headless/react-native-scrollable-tab-view#621]
I have just begun learning ReactNative and trying to implement ScrollableTabBar. Succussfully implemented it with tabLabels but I want to show Icons above labels so I have gone through the issues and even tried implementing [DynamicExample.js](https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/DynamicExample.js#L61) as mentioned in some of the issues, but can't get it working.

My code is:

```
'use strict';

import React, { Component } from 'react';
import {
  	Image,
    StyleSheet,
    Text,
    View,
    ListView,
    TouchableHighlight,
    ActivityIndicator,
    ReactPage,
    FlowPage,
    JestPage,
    ScrollView
} from 'react-native';

import ScrollableTabView, { ScrollableTabBar, } from 'react-native-scrollable-tab-view';
import TimerMixin from 'react-timer-mixin';

var BookListNew = require('./BookListNew');

const Child = React.createClass({
  onEnter() {
    console.log('enter: ' + this.props.i); // eslint-disable-line no-console
  },

  onLeave() {
    console.log('leave: ' + this.props.i); // eslint-disable-line no-console
  },

  render() {
    const i = this.props.i;
    return <Text key={i}>{`tab${i}`}</Text>;
  },
});

export default class BookList extends Component {

  mixins: [TimerMixin, ],  // This is line 88 where error is pointing. no idea what error means.
  children: [],

  getInitialState() {
    return {
      tabs: [1, 2],
    };
  },

  componentDidMount() {
    this.setTimeout(
      () => { this.setState({ tabs: [1, 2, 3, 4, 5, 6, ], }); },
      100
    );
  },

  handleChangeTab({i, ref, from, }) {
    this.children[i].onEnter();
    this.children[from].onLeave();
  },

  renderTab(name, page, isTabActive, onPressHandler, onLayoutHandler) {
    return <TouchableHighlight
      key={`${name}_${page}`}
      onPress={() => onPressHandler(page)}
      onLayout={onLayoutHandler}
      style={{flex: 1, width: 100, }}
      underlayColor="#aaaaaa"
    >
      <Text>{name}</Text>
    </TouchableHighlight>;
  },

   	render() {

    return (

    <ScrollableTabView
      style={{marginTop: 20, }}
      renderTabBar={() => <ScrollableTabBar renderTab={this.renderTab}/>}
      onChangeTab={this.handleChangeTab}
    >
      {this.state.tabs.map((tab, i) => {
        return <Child
          ref={(ref) => (this.children[i] = ref)}
          tabLabel={`tab${i}`}
          i={i}
          key={i}
        />;
      })}
    </ScrollableTabView>;
    }

}
 
module.exports = BookList;
```

error is coming when i run : `SyntaxError: Unexpected token, expected , (88:24)`

Please help!
Thanks

**Comment by skv-headless** [comment]
What is in line 88?

**Comment by hyd00** [comment]
Line 88 has `mixins: [TimerMixin, ],`

I have commented in the code as well above.

**Comment by skv-headless** [comment]
change
`export default class BookList extends Component {`
`export default const BookList = React.createClass({`

and good luck

**Comment by hyd00** [comment]
Thanks @skv-headless  but now error says `unexpected token (86:15)` :(

**Comment by linigithub** [comment]
Hi all ,

Just fixed adding icon + text in tab bar using below steps after googling

https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabBar.js

Add the above class as one separate class in your js file and refer this as below in render function

  <ScrollableTabView renderTabBar={() => <FacebookTabBar/>}>
      <Home tabLabel=“home”/>
      <Bank tabLabel="bank"/>
    </ScrollableTabView>
It works 💯 % :)

**Comment by hungdev** [comment]
@linigithub but i want to use image.png replace vector icon. how must i do?
