### ISSUE TITLE
ScrollableTabView renders each time route is changed

### ISSUE THREAD

**Issue by igorarkhipenko** [skv-headless/react-native-scrollable-tab-view#624]
Each new click on component which goes to another route, creates new `ScrollableTabView` component. And after several iterations of these actions I have the same component rendered _n_ times which leads incredible lags. How to prevent behavior like this? 

`<ScrollableTabView renderTabBar={() => <ScrollableTabBar />} page={viewSettings} onChangeTab={this.onChangeTab.bind(this)}>`
`        <Settings tabLabel="settings" key="settings" />`
`        <Vacancy tabLabel="vacancy" key="vacancy" /> `
`</ScrollableTabView>`

**Comment by skv-headless** [comment]
By routes you mean tabs? Could you please make example project to show your problem because it is not the way that it works in my projects. Or could you reproduce it on one of the examples https://github.com/skv-headless/react-native-scrollable-tab-view/tree/master/examples/FacebookTabsExample ?

**Comment by igorarkhipenko** [comment]
Issue has been resolved with `type="reset"` as property for route with scrollable tab.
@skv-headless I'm sorry for late answer, it can be closed now I guess.
