### ISSUE TITLE
ScrollTabView: ONLY lock beyond last tab

### ISSUE THREAD

**Issue by dylanrhodius** [skv-headless/react-native-scrollable-tab-view#629]
Hey hey lovely people!

I currently have 2 tabs in a ScrollTabView. I'm trying to disable horizontal dragging ONLY beyond the final tab (either the final tab towards the left or right). 
When I set the prop "locked" to true, it disables all kinds of horizontal dragging. I only would like to not allow users to drag beyond the last tab but not between the two tabs.

Any help with this would be greatly appreciated! (Using both android and iOS but currently testing on iOS)

**Comment by skv-headless** [comment]
Try something like this 
`<ScrollableTabView locked={this.state.activeTab === 1} onChangeTab={({i}) => this.setState({activeTab: i})}>`
Does that make sense?

**Comment by dylanrhodius** [comment]
Hmm I tried it and didn't seem to work, it did not seem to recognise the "activeTab" for some reason.. Just to explain what I need and my code better, I am posting 2 screenshots and 1 gif. Thank you for your time!!
[gif](blob:http://imgur.com/a1d6893b-9ef5-4c36-8d73-64c9478bbbe3)
[picture 1](http://i.imgur.com/EtbOd40.png)
[picture 2](http://i.imgur.com/r4BJGJg.png)

**Comment by skv-headless** [comment]
Do you mean that you don't like bounce effect?

**Comment by dylanrhodius** [comment]
Basically, when it is on the left tab (the cat tab) I want to stop the user from trying to scroll towards the left. And when it is on the right tab (the dog tab) I want to stop the user from trying to scroll towards the right. The user should not be able to try to scroll past the LAST tab. So, on the edges, the tab should not even move at all, they should stay locked towards one side. Does this make sense?

**Comment by skv-headless** [comment]
try `contentProps={{bounces: false}}`

**Comment by dylanrhodius** [comment]
Oh, that is called the bounce effect. That was exactly what I needed, thank you so much man!

**Comment by skv-headless** [comment]
Good luck 😉

**Comment by AndsteLyc** [comment]
> try contentProps={{bounces: false}} @skv-headless 
That was exactly what I needed t0o0o0o0o0o, Thanks!

**Comment by AndsteLyc** [comment]
> contentProps={{bounces: false}} 

@skv-headless 
That was exactly what I needed, Thanks!

**Comment by windydang26** [comment]
@skv-headless, contentProps={{bounces: false}} but i can't swip to open drawer. Have you resolve ?
