### ISSUE TITLE
结合react-navigation的tabbar使用时，android启动呈现空白页

### ISSUE THREAD

**Issue by ZHT131** [skv-headless/react-native-scrollable-tab-view#630]
结合react-navigation的tabbar使用时，android
![_20170511114324](https://cloud.githubusercontent.com/assets/22323594/25931478/0c869074-363f-11e7-88aa-582aee48c65b.png)

启动呈现空白页，必须打开新页面后返回才显示出来

**Comment by skv-headless** [comment]
Please create issue in english.

**Comment by linzhiyu** [comment]
@skv-headless react-native-scrollable-tab-view can not work well in android with react-navigation tabbar. It works well in ios, not android.you can see the picture. 
![androdddd](https://cloud.githubusercontent.com/assets/18454779/26147409/0b7d0f8c-3b26-11e7-93ab-3eeb1bc37895.png)

**Comment by fatsoon** [comment]
I also have this problem.

**Comment by valeriaabo** [comment]
Same problem, Any solution?

**Comment by shiyunsheng** [comment]
Same problem, please help me !

**Comment by linzhiyu** [comment]
I forgot how to fixed it. 
But now I doesn't have this problem anymore.
I use: "react-native-scrollable-tab-view": "^0.7.4".
I hope this can help you.

**Comment by YanfangLi248** [comment]
How to solve this problem？
