### ISSUE TITLE
Undefiend is not an object (evaluating 'ViewPropTypes.Style')

### ISSUE THREAD

**Issue by ahsan-aurora** [skv-headless/react-native-scrollable-tab-view#633]
I have installed react-native-scrollable-tab-view via npm. As soon as I use the following import in my component,
import ScrollableTabView from 'react-native-scrollable-tab-view';

I get the following error, 
Undefiend is not an object (evaluating 'ViewPropTypes.Style')

Please help. Am I missing something?

**Comment by ahsan-aurora** [comment]
Okay so I solved this issue by changing the version of react-native-scrollable-tab-view in my package.json file. 
I changed it too     "react-native-scrollable-tab-view": "^0.7.3", and now its working.

**Comment by perfecten** [comment]
I have the same issue.
but I install  it by "npm i -s "react-native-scrollable-tab-view"", I got the  "0.6.6".
