### ISSUE TITLE
Lock one of n tabs

### ISSUE THREAD

**Issue by Venumteam** [skv-headless/react-native-scrollable-tab-view#637]
Hi, can someone help me understand - how to lock one tab by condition if I have for example three tabs? Other tabs must be unlocked...

**Comment by skv-headless** [comment]
Can it be helpful https://github.com/skv-headless/react-native-scrollable-tab-view/issues/629?

**Comment by Venumteam** [comment]
Thanks for answering, I just solved this problem by this approach:
`<ScrollableTabView
          initialPage={1}
          renderTabBar={() => <View />}
          ref={(tabView) => { this.tabView = tabView }}
          contentProps={{bounces: false}}
          onChangeTab={this.handleChangeTab}
        >
          <FirstTab />
          <SecondTab />
          {!condition && <ThirdTab />}
</ScrollableTabView>`

**Comment by skv-headless** [comment]
Great :+1:
