### ISSUE TITLE
Cannot find ViewPropTypes.style 

### ISSUE THREAD

**Issue by Jiepeixuan** [skv-headless/react-native-scrollable-tab-view#643]
![image](https://cloud.githubusercontent.com/assets/13375587/26479720/fdee1ddc-4207-11e7-883c-2eb2334a4826.png)
what can i do to slove this Q?

**Comment by Jiepeixuan** [comment]
React version: 15.3.2
React native version: 0.37.0

**Comment by happierco** [comment]
You can change `ViewPropTypes` to `View.propTypes` and also remove the import

**Comment by skv-headless** [comment]
downgrade `react-native-scrollable-tab-view`. Latest versions not compatible with `react-native` older than `0.44` 😞

**Comment by dozel** [comment]
@skv-headless which version doesn't have this issue for older RN versions? 0.7.0?

**Comment by janaka120** [comment]
@Jiepeixuan & @dozel I had had the same issue. 
I solve this by downgrade the react-native-scrollable-tab-view version.

React version: 15.4.0
React native version: 0.38.0
React-native-scrollable-tab-view: 0.6.0

this may be help
