### ISSUE TITLE
Underline IOS Problem

### ISSUE THREAD

**Issue by kenvandemar** [skv-headless/react-native-scrollable-tab-view#645]
When I set scrollWithoutAnimation to ScrollableTabView, it works fine with Android, but with IOS, when I click to tab 2 and then click back tab1, the underline is still tab2.

**Comment by teofiluscandra** [comment]
I had same problem too

**Comment by kenvandemar** [comment]
I fixed it already, just need to modified ScrollableTabBar.js file. If you guys meet trouble like me, you can check the file I upload here as reference.

[ScrollableTabBar.txt](https://github.com/skv-headless/react-native-scrollable-tab-view/files/1066396/ScrollableTabBar.txt)
