### ISSUE TITLE
Nesting on android dose not work?

### ISSUE THREAD

**Issue by lwddsy** [skv-headless/react-native-scrollable-tab-view#656]
Nesting when using ScrollableTabView does not work on android

no animation and no render
if Nesting width react-navigation TabNavigator also not working

Hope that God can understand what I said, my English is not good

**Comment by uinz** [comment]
@lwddsy did you resolve it?

**Comment by xuanmiao-zero** [comment]
I have the same problem when  trying nested ScrollableTabView in TabNavigator  which i hope to create second level menu . I will appreciate very much if someone gives some method to slove it . 
My English is really awful, sorry

**Comment by uinz** [comment]
@xuanmiao-zero render ScrollableTabView after `componentDidMount`. maybe 1s ?

**Comment by xuanmiao-zero** [comment]
@uinz  many thanks for your reply , I find the method yesterday,and it's worked. you are really good man.thank you again.

**Comment by callcter** [comment]
@xuanmiao-zero 我用两个scrollable-tab-view嵌套，你是怎么解决的？能说一下思路吗
