### ISSUE TITLE
Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by IZHQT** [skv-headless/react-native-scrollable-tab-view#665]
![image](https://user-images.githubusercontent.com/6813909/27063609-43ffc02a-5025-11e7-8a52-4f89baaee00f.png)
![image](https://user-images.githubusercontent.com/6813909/27063618-4955fbb6-5025-11e7-8535-c4ddaaecb94a.png)
My Rreact-Native Version is 0.43.3。The ViewPropTypes's Value is undefined when I print it！

**Comment by NARUTOyuyang** [comment]
![77091e2a-7992-44a0-af1a-4d65dc057e92](https://user-images.githubusercontent.com/22002078/27073715-641c7ef2-5057-11e7-970d-48f63b7db51a.png)我都把里面相关代码注释掉了，还是遇见这个问题

**Comment by NARUTOyuyang** [comment]
解决了！使用react-native-scrollable-tabbar的插件报错问题，看下自己的rn版本，升级到0.44之后就没问题，主要是 0.44版本后对viewproptypes的使用限定

**Comment by IZHQT** [comment]
项目中版本已经限定为0.43.3了

**Comment by IZHQT** [comment]
react-native-scrollable-tab-view@NARUTOyuyang

**Comment by IZHQT** [comment]
@NARUTOyuyang ,项目中的版本已经限定为0.43.3了

**Comment by skv-headless** [comment]
same as #634
