### ISSUE TITLE
undefined is not an object (evaluating 'ViewPropTypes.style')

### ISSUE THREAD

**Issue by felemedeiros** [skv-headless/react-native-scrollable-tab-view#668]
Hi,

I didn't see this posted before, just adding:

`import ScrollableTabView from 'react-native-scrollable-tab-view';`

Throws an _**undefined is not an object (evaluating 'ViewPropTypes.style')**_

code:

```
import React, {Component} from 'react';
import {View} from 'react-native';
import Colors from './../../../res/colors';
import ScrollableTabView, {DefaultTabBar, } from 'react-native-scrollable-tab-view';

export default class About extends Component {
  render() {
    return (
      <View style={{flex: 1, backgroundColor: Colors.THEME_PRIMARY}} />
    );
  }
}
```

Best regards.

**Comment by roycehe** [comment]
use this version ^0.7.4 ,and it worked

**Comment by tianmengmengliang** [comment]
在node_moudle ---> 'react-native-scrollable-tab-view'资源包下面的 ScrollableTabBar.js和Defaulttabbar.js文件中, 注释掉所有的viewproptypes.style属性。
