### ISSUE TITLE
Module not found: Error: Can't resolve './Button' in 

### ISSUE THREAD

**Issue by damiaozi** [skv-headless/react-native-scrollable-tab-view#675]
what can I do？
ERROR in ./~/react-native-scrollable-tab-view/ScrollableTabBar.js
Module not found: Error: Can't resolve './Button' in 'E:\workspace\fjsgo\node_modules\react-native-scrollable-tab-view'
 @ ./~/react-native-scrollable-tab-view/ScrollableTabBar.js 12:11-30
 @ ./~/react-native-scrollable-tab-view/index.js
 @ ./src/View/Mine/AddAddressView.js
 @ ./src/Navigator.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server react-hot-loader/patch ./index.web.js

**Comment by skv-headless** [comment]
Are you using it with react-native-web?

**Comment by skv-headless** [comment]
close for no response

**Comment by vantb9x** [comment]
Hi @damiaozi , have you resolved your issue? I meet the same as you with library

**Comment by summerkiflain** [comment]
@damiaozi @skv-headless, I am also facing the same issue and yes I am using it with react-native-web, Is there any solution for this?

**Comment by astro11** [comment]
Same here, has anyone come across a solution?
