### ISSUE TITLE
Attempt to invoke virtual method 'void com.facebook.react.uimanager.ReactShadowNode.setStyleWidth(float)' on a null object reference

### ISSUE THREAD

**Issue by juanmanuelarze** [skv-headless/react-native-scrollable-tab-view#677]
The app crash in some devices sometimes...

`Attempt to invoke virtual method 'void com.facebook.react.uimanager.ReactShadowNode.setStyleWidth(float)' on a null object reference`

**Comment by Moumene** [comment]
any new about this one?! :/

**Comment by skv-headless** [comment]
seems to be fixed https://github.com/facebook/react-native/issues/10845
