### ISSUE TITLE
Underline doesn't show on initial load

### ISSUE THREAD

**Issue by rvpyrv** [skv-headless/react-native-scrollable-tab-view#682]
Tab's Underline doesnt show on initial page load, but appears when i tap on some other tab. 

Code:

`<ScrollableTabView `
    `style={{borderBottomWidth: 5, borderBottomColor: '#222222'}}`
     `page={1}`
      `tabBarUnderlineStyle={{backgroundColor: 'red'}}`
      `renderTabBar={() => <ScrollableTabBar />}`
   ` >`
      `<Text tabLabel='Tab #2'>favorite</Text>`
    `  <Text tabLabel='Tab #3'>project</Text>`
     ` <Text tabLabel='Tab #4'>favorite</Text>`
     ` <Text tabLabel='Tab #5'>project</Text>`
   ` </ScrollableTabView>`

**Comment by rvpyrv** [comment]
`     	<ScrollableTabView
      style={{borderBottomWidth: 5, borderBottomColor: '#222222'}}
      page={1}
      tabBarUnderlineStyle={{backgroundColor: 'red'}}
      renderTabBar={() => <ScrollableTabBar />}
    >
      <Text tabLabel='Tab #2'>favorite</Text>
      <Text tabLabel='Tab #3'>project</Text>
      <Text tabLabel='Tab #4'>favorite</Text>
      <Text tabLabel='Tab #5'>project</Text>
    </ScrollableTabView>`

**Comment by rvpyrv** [comment]
It's strange, but it works now...

**Comment by rvpyrv** [comment]
It seems that i have done this:


Changed 
renderTabBar={() => <ScrollableTabBar />} 

to
renderTabBar={() => <DefaultTabBar />

If u copypasting the code, watch what you are pasting. Closing.

**Comment by Clcll** [comment]
For static it's ok but not for scrollableTabs

**Comment by CodingMonkeyzh** [comment]
So, it's a bug in scrollableTabs ?

**Comment by CodingMonkeyzh** [comment]
@rvpyrv I think you should reopen this issue :)

**Comment by ozsirma** [comment]
yes I have the same problem. Underline doesn't show on initial load.

**Comment by CodingMonkeyzh** [comment]
@ozsirma you can fix this problem by change `this.props.scrollValue._value` to `this.props.scrollValue.__getValue()` in the `< ScrollableTabBar/>`

see https://github.com/skv-headless/react-native-scrollable-tab-view/pull/678/commits/4312d6cca2fe7859caa5219f2ee8b61edcf04884

**Comment by shahankit** [comment]
@skv-headless when will this be released?

**Comment by hectorsc** [comment]
It happened to me when updating to the last version

The version 0.6.5 it works perfectly.

**Comment by shahankit** [comment]
I'm using version 0.6.7 and still facing the issue. I had to manually change the line suggested by @CodingMonkeyzh  to get it working.
