### ISSUE TITLE
Compatibility with RN 0.46+

### ISSUE THREAD

**Issue by spezzino** [skv-headless/react-native-scrollable-tab-view#691]
Fixed incompatibility with ReactNative 0.46+

PropTypes moved to a new independent package.
CreateClass moved to a new independent package.

**Comment by ali322** [comment]
+1

**Comment by eaeao** [comment]
+1

**Comment by jing-wu** [comment]
+1

**Comment by RichardLindhout** [comment]
+1

**Comment by awebr000** [comment]
:+1:

**Comment by drpiou** [comment]
+1, please

**Comment by spezzino** [comment]
any updates on this?

**Comment by jackdcrawford** [comment]
Nice work @spezzino 🎉 

@skv-headless nice library, has helped us out a lot! Would be great to get this one released at some point so we can upgrade react-native to > 0.46

**Comment by wanghaixu** [comment]
+1

**Comment by chenlin8** [comment]
+1

**Comment by skv-headless** [comment]
should be fixed in 0.8.0
