### ISSUE TITLE
the content sometimes does not display

### ISSUE THREAD

**Issue by Tgoing** [skv-headless/react-native-scrollable-tab-view#696]
当我动态更换tab里面的组件时，组件有时候不显示，但是还是可以触发组件的事件（自动翻译）

When I change the components in the TAB dynamically, the component sometimes does not display, but it can also trigger the event of the component (automatic translation).

**Comment by jintangWang** [comment]
update to ^0.7.4

**Comment by zi6xuan** [comment]
我目前使用的版本是1.0.0，还是出现了这种情况，而且在android下出现的概率更大，有时候第一页内容不显示，但是里面的touch事件可以触发，切换tabBar之后就可以正常显示了
