### ISSUE TITLE
Lazy scrollable tab view

### ISSUE THREAD

**Issue by ssssssssssss** [skv-headless/react-native-scrollable-tab-view#70]
Dear @brentvatne 
I'm trying to extend your work to support a lazy scrollable tab view, it works for iOS but not for Android, I think the Android port has some difficult time for re-rendering, I have issue filed here, hope you can help it out. Thanks. 
https://github.com/facebook/react-native/issues/3823

**Comment by brentvatne** [comment]
I agree this would be an excellent feature!

**Comment by ericraio** [comment]
+1 would love this feature!

**Comment by brentvatne** [comment]
Doesn't seem too hard, who wants to take a crack at it?

**Comment by ssssssssssss** [comment]
Still stuck in Android version.

**Comment by cancan101** [comment]
When you say lazy scrollable tab view, do you mean to defer the first render of a tab until it first shown (along the lines of[ what TabBarIOS does](https://github.com/facebook/react-native/blob/648aaf440b70780e3ca35314760cd6c5e69ea8a0/Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js#L104-L111))?

**Comment by ericraio** [comment]
@cancan101 the way i think it should goes is when the tab is activated, it then mounts the component instead of rendering all of them at once.

**Comment by cancan101** [comment]
Yes see my link above and also #232

**Comment by ssssssssssss** [comment]
Not only lazy for the rendering of activated tab, but also lazy for the tab creation, so I'd expected a WindowedViewPager. :)

**Comment by dcworldwide** [comment]
Any progress on this?

It is expensive to render all child views at once.

**Comment by code-smith** [comment]
It's done.
https://github.com/skv-headless/react-native-scrollable-tab-view/pull/303
https://github.com/code-smith/react-native-scrollable-tab-view
