### ISSUE TITLE
how can i add shadow instead of border bottom of the tabs?

### ISSUE THREAD

**Issue by panhna** [skv-headless/react-native-scrollable-tab-view#702]
<img width="508" alt="screen_shot_2017-07-04_at_11 54 56_am" src="https://user-images.githubusercontent.com/5246440/28534913-b528f3b2-70cc-11e7-8fa4-d68f51df3356.png">

**Comment by TaylorDurden** [comment]
@panhna 
Add this below style to scrollable tab view.

style={{
borderBottomWidth:0,
shadowOffset: {width: 0.5, height: 0.5},
                           shadowOpacity: 0.4,
                            shadowRadius: 1,
                            elevation: 2, }}

**Comment by panhna** [comment]
thx. @TaylorDurden. i already try this before many time but it not good enough.
i found the solution. tabBarPosition='overlayTop' to make the content below the tab-bar.
