### ISSUE TITLE
react.createclass is no longer supported

### ISSUE THREAD

**Issue by slowman123** [skv-headless/react-native-scrollable-tab-view#703]
version: 
		"react": "16.0.0-alpha.12",
		"react-native": "0.46.4"

warning message:
               React.createClass is no longer supported. use a plain JavaScript class instead

![image](https://user-images.githubusercontent.com/5105604/28654950-cd70de58-72ca-11e7-86d9-2bbc54611f24.png)

**Comment by developer239** [comment]
+1

**Comment by developer239** [comment]
I wanted to create pull request but seeing they even use mixins I did not really want to get into that.

**Comment by skv-headless** [comment]
close for #691

**Comment by relunctance** [comment]
+1

**Comment by developer239** [comment]
@skv-headless #691 is also closed...

**Comment by wanghaixu** [comment]
+1
