### ISSUE TITLE
scrollabletabview inside scrollview cannot display 

### ISSUE THREAD

**Issue by Kariko** [skv-headless/react-native-scrollable-tab-view#704]
when i take a scrollabletabview inside scrollview, the content of scrollabletabview can not display, what should i do to solve this problem?

**Comment by HeinZawHtet** [comment]
i have the same problem. But I updated to ^0.7.4 & problem solved.

**Comment by ahmadms1** [comment]
@HeinZawHtet upgrading to ^0.7.4 works for me too for a ScrollableTabView inside a View. Cheers!

**Comment by guobg** [comment]
+1, any one resloved this problem?

**Comment by Kariko** [comment]
@HeinZawHtet  Thank you very much!

**Comment by aijason** [comment]
but 0.74  scrollView  can not horizatal inside  , and srollableTabView inside ScrollView two children pages has the same height ,  any one resloved this?  very Thank

**Comment by ftxbird** [comment]
srollableTabView inside ScrollView two children pages has the same height , any one resloved this? very Thank

**Comment by wyn0731** [comment]
+1 still not working
