### ISSUE TITLE
Need tab vertical align center

### ISSUE THREAD

**Issue by Xixi20160512** [skv-headless/react-native-scrollable-tab-view#705]
![image](https://user-images.githubusercontent.com/19320239/28708591-57b07bac-73af-11e7-97c9-1bf83ea25274.png)

![image](https://user-images.githubusercontent.com/19320239/28708651-92ea13fe-73af-11e7-948d-947a4364cab5.png)
I see those code in DefaultTabBar.js ,and I dont find the way to reset this 'paddingBottom:10'

**Comment by anceque** [comment]
This is because we cannot use `tabBarTabStyle` :(  as mentioned here #604.

It would be very useful to have this if we want to use the `defaultTabBar` but don't want to render a custom one just because of one padding issue.

**Comment by Xixi20160512** [comment]
@anceque thanks,this solve my problem
