### ISSUE TITLE
Reduce the heigh of tab bar

### ISSUE THREAD

**Issue by iLeonelPerea** [skv-headless/react-native-scrollable-tab-view#723]
Hi.

How can I reduce the heigh of the tabar? I dont need the space of the tablabel

![example](https://user-images.githubusercontent.com/2968628/29538528-e3c1bafe-868b-11e7-8d2a-a1ce0b900e4a.jpg)

**Comment by zhaochu0821** [comment]
How to modify the react-native-scrollable- tab -view tag height

**Comment by LiuYibin** [comment]
+1
