### ISSUE TITLE
ReactNative is not defined

### ISSUE THREAD

**Issue by guopeng1994** [skv-headless/react-native-scrollable-tab-view#734]
RN version: 0.47
react-native-scrollable-tab-view version: 0.6.7
android api  23

when i use ScrollableTabView , RN debug mode told me that "ReactNative is not defined", and the error place  is : 
           const { ViewPropTypes } = ReactNative = require('react-native');
I chage the code to：
           const ReactNative = require('react-native');
           const { ViewPropTypes } = ReactNative;
it will be all right.
now the question is everytime i install new npm packages it will back to the old code, i used babel,es6. so how could i to resove this propblem?does there anybody knows?

**Comment by guopeng1994** [comment]
i just find the authors solved this problem a few days ago. but it's  just a commit,not realse version, so what should i do now?

**Comment by guopeng1994** [comment]
ok . i resolved this problem by : 
yarn add https://github.com/skv-headless/react-native-scrollable-tab-view.git#0.7.4 --save

**Comment by Casepl** [comment]
Your solution for this tag break builds (react-native: 0.63.4, typescript project) with an error about trailing comma. In this file https://github.com/ptomasroos/react-native-scrollable-tab-view/blob/master/SceneComponent.js
