### ISSUE TITLE
Native animated module is not available

### ISSUE THREAD

**Issue by hanxk** [skv-headless/react-native-scrollable-tab-view#736]
react-native: 0.47.1
npm: 5.3.0
node: v8.4.0

![image](https://user-images.githubusercontent.com/5105604/30152477-cda4bafc-93e5-11e7-81dd-555e82e63e47.png)

**Comment by seanquinn** [comment]
@hanxk how did you fix this? I tried adding RCTAnimation to the project, however I think it's an issue with this package.

**Comment by dytiz** [comment]
i  got same problem and  solved it:
../node_modules/react-native/Libraries/NativeAnimation/RCTAnimation.xcodeproj
Find this file and drag it to the Libraries.
<img width="168" alt="qq20180627-214041 2x" src="https://user-images.githubusercontent.com/10192599/41977886-1e91dfb8-7a53-11e8-86f4-54eb3acda6d1.png">
then select targets->build Phases -> Link Binary With Libraries -> add   libRCTAnimation.a
command+B ～～～   ok!
