### ISSUE TITLE
runAfterInteractions doesn't fire from within the component

### ISSUE THREAD

**Issue by eyaleizenberg** [skv-headless/react-native-scrollable-tab-view#76]
I have a 3 views nested inside the scrollable tab view. One of them has a link which pushes the navigator to another scene. In my next scene I have:

```coffeescript
  componentDidMount: ->
    InteractionManager.runAfterInteractions =>
       someCodeWhichIsSupposedToRunAfterInteractions
```

However, the runAfterInteractions doesn't fire. If I change the container view from ScrollableTabView to just a normal View, everything works as expected. Any suggestions?

**Comment by eyaleizenberg** [comment]
@brentvatne Any chance to look into this?

**Comment by brentvatne** [comment]
Hi! Does this still happen on the latest release? I think this should work now

**Comment by eyaleizenberg** [comment]
Happens on 0.2.2 alpha and Rn0.17
The implementation you did with Scroll View is not right for us. Can you
direct me on how to solve this or do you know of a fork which still uses
the old solution with animated?

**Comment by Efimster** [comment]
+1,  same issue here

**Comment by skv-headless** [comment]
I don't see a reason to keep this issue opened if it is for 0.2.2 version.
