### ISSUE TITLE
Blank Tab Content with initialPage value 1

### ISSUE THREAD

**Issue by ishita-kothari** [skv-headless/react-native-scrollable-tab-view#762]
Hello,

I have 2 tabs in my react-native app. First tab has "favourite" content and Second tab has "All" content. When the array of "favourite" content is empty, I need to show "All" contents. For this I am using initialPage={1}. I can see the active tab, but the content is not visible. I just see blank screen. 

If I scroll to tab 0 and then scroll back to tab 1, the content is visible. I tried every solution provided in few issues but didn't find any luck. Can anyone please help?

Thanks!

**Comment by SupriyaKalghatgi** [comment]
+1

**Comment by syzer** [comment]
also `React.createClass` is deprecated to it needs a bit of `face lifting` :)

**Comment by koansang** [comment]
+1

**Comment by syzer** [comment]
Did you try ```prerenderingSiblingsNumber={1}```?

**Comment by luco** [comment]
Any updates? Can't use this yet.

**Comment by syzer** [comment]
Would fix it but current maintainer @skv-headless is gone missing :D
So all it would is 36 open PR's => 37 open PR's.

**Comment by antoinerousseau** [comment]
maybe @brentvatne can help along with @skv-headless ?

**Comment by syzer** [comment]
The next week, I might have couple hour to drill to that.. but no promises on that.
We had performance issues with tab switching 7.4 so we need to come back to this package :D

**Comment by antoinerousseau** [comment]
I switched to https://github.com/react-native-community/react-native-tab-view but thanks anyway

**Comment by skv-headless** [comment]
https://github.com/facebook/react-native/issues/15808

**Comment by skv-headless** [comment]
close for #750

**Comment by shubham81407** [comment]
I have the same problem with iOS. What is the solution to resolved this issues?

**Comment by SupriyaKalghatgi** [comment]
@syzer When can we expect fix for this

**Comment by syzer** [comment]
currently not working on this issue

**Comment by kubilaytural** [comment]
Try this. It worked. Ideal for changing first pages.

componentDidMount() {
setTimeout(() => this.scrollableTabView.goToPage(1), 300);
}
...
.....
...
<ScrollableTabView
ref={(ref) => { this.scrollableTabView = ref; }}

**Comment by syzer** [comment]
@Balasnest did you try @kubilaytural solution or|and using `prerenderingSiblingsNumber={1}` ?

**Comment by Balasnest** [comment]
@syzer Most of the time data is not loading. Very rarely its working out. I guess settimeout is not working exactly. How can resolve this?

**Comment by syzer** [comment]
have you tried using react timing functions?
or does bigger timeout help ? if so you could patch it

to be honest i'm not sure how i patched it 😄 it was august last year or so :)

you could also try this replacement:
https://www.npmjs.com/package/react-native-scrollable-tab-view-fix

**Comment by hanzoow** [comment]
> Try this. It worked. Ideal for changing first pages.
> 
> componentDidMount() {
> setTimeout(() => this.scrollableTabView.goToPage(1), 300);
> }
> ...
> .....
> ...
> <ScrollableTabView
> ref={(ref) => { this.scrollableTabView = ref; }}

ty, fixed the problem
