### ISSUE TITLE
initial page shows blank

### ISSUE THREAD

**Issue by svallen** [skv-headless/react-native-scrollable-tab-view#769]
When I force an initial page to something other than the first page it is rendering blank. Scrolling to other tabs will render data and then going back to that initial forced page renders the data correctly.

Using:
"react": "16.0.0-alpha.12",
"react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",

Any insights into fixing this would be great.

**Comment by sinapcs** [comment]
I have this problem too after updating my app to react-native 48.4
on react-native 49.3 also this problem exists.

**Comment by svallen** [comment]
Any luck on getting this fixed or an ETA? Seems like a big issue and is causing a lot of loading problems.

**Comment by dyaacov** [comment]
I'm about to release my app and this is a blocker. appreciate fast response

**Comment by svallen** [comment]
Same situation here

**Comment by dyaacov** [comment]
See here:
https://github.com/skv-headless/react-native-scrollable-tab-view/issues/762

I think it’s time to replace the library...

**Comment by skv-headless** [comment]
close for #750

**Comment by svallen** [comment]
You closed this and I downloaded the latest commit, but the issue is still happening.  Does this mean the updates you made have not been committed yet?

**Comment by skv-headless** [comment]
No, It is just duplication of #750

**Comment by skv-headless** [comment]
This https://github.com/skv-headless/react-native-scrollable-tab-view/issues/750#issuecomment-335413285 should work I think maybe I will make temporary solution with this patch

**Comment by svallen** [comment]
I followed that, but I'm using 0.8.0 version. There is no componentDidMount in that version to update what that person had said.

**Comment by svallen** [comment]
FYI - By putting in the componentDidMount code that was suggested that was missing from 0.8.0 version did the trick to get it back to functioning better.

**Comment by zhangjun920912** [comment]
delay load render scrollable-tab-view can resolve this question,you can set state,when open this page ,show an activityIndicator,after 500ms,change state,then render scrollable-tab-view,this is an temporary method,maybe ,wo can wait plaugs refresh

eg:if(this.state.delayShowScrollableTabView)
{
return(
<View style={{flex:1,backgroundColor:'#fff'}}>
<View style={{marginTop:screenHeight*0.4+99,alignSelf:'center',flexDirection:'row'}}>
<ActivityIndicator size={'small'}/>
Loading...


);
}else{
return (

<TouchableOpacity activeOpacity={0.95} style={newsNavRow.searchWrapper} onPress={()=> {this.props.navigation.navigate("NewsSearch_V2",{searchContent:"News"})}}>
<View style={{backgroundColor:'#204B7D',flex:1,alignItems:'center',justifyContent:'center',height:Platform.OS=="ios"?44:55,width:44}}>
<Image source={require("../images/searchNews.png")} style={{height:20,width:20}}/>


<View style={{flex:1,width:30,height:Platform.OS=="ios"?44:55,zIndex:11,position:"absolute",top:0,right:44}}>
<Image source={require("./../images/overlayGradient.png")} style={{width:30,height:Platform.OS=="ios"?44:55}} resizeMode={Image.resizeMode.stretch}/>

{newsListView}
{this.getUserVerifiedModal()}

);
}
