### ISSUE TITLE
ScrollableTabView with ScrollableTabBar has an incorrect position in landscape mode in ios 

### ISSUE THREAD

**Issue by CircleCurve** [skv-headless/react-native-scrollable-tab-view#770]
Hello, I'm new of react native and try to integrate this library with both portrait and landscape mode. Unfortunately, ios render a wrong position 

Portrait

![image](https://user-images.githubusercontent.com/8490834/31713019-6ebe2658-b42f-11e7-986d-a9abfc1bbb2b.png)

Move to next tab 

![image](https://user-images.githubusercontent.com/8490834/31713047-87629de2-b42f-11e7-8eac-a183983f72d3.png)

In Landscape mode

![image](https://user-images.githubusercontent.com/8490834/31713074-9e75d76a-b42f-11e7-8420-897f24d8bd92.png)

Below is my code. I just copy the source code from [](https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/Example/ScrollableTabsExample.js). I only reduce the wording and size of tab. 

```
<ScrollableTabView
                style={{ marginTop: 20, }}
                initialPage={0}
                renderTabBar={() => <ScrollableTabBar />}
            >
                <Text tabLabel='Tab #1'>My</Text>
                <Text tabLabel='Tab #2'>favorite</Text>
                <Text tabLabel='Tab #3'>project</Text>

            </ScrollableTabView>
```

**Comment by skv-headless** [comment]
dup #750

**Comment by malonguwa** [comment]
@CircleCurve hi mate, have find a walk around for this landscape issue?

**Comment by malonguwa** [comment]
@skv-headless Could you mind to explain little more why you refer this issue to https://github.com/skv-headless/react-native-scrollable-tab-view/issues/750
? Is there a way to fix this landscape layout issue?

**Comment by yurnery** [comment]
@malonguwa @skv-headless @CircleCurve could you tell me how to solve this problem more clear? the issue #750 this not the same as this problem at all
