### ISSUE TITLE
goToPage and initialPage

### ISSUE THREAD

**Issue by yotavm** [skv-headless/react-native-scrollable-tab-view#776]
hi,
I'm working with the last version
I'm using the ScrollableTabBar
when I change the initial page the tabs work fine 
its move to the initial page but the page is blank
and if I'm using  goToPage with ref only the color of the text change and but 
the page not change and the underline not move

**Comment by anthonied** [comment]
Same issue +1

**Comment by anthonied** [comment]
https://github.com/facebook/react-native/issues/15808 - this fixed it for me

**Comment by skv-headless** [comment]
dup #750

**Comment by kubilaytural** [comment]
Try this. It worked. Ideal for changing first pages.

componentDidMount() {
setTimeout(() => this.scrollableTabView.goToPage(1), 300);
}
...
.....
...
<ScrollableTabView
ref={(ref) => { this.scrollableTabView = ref; }}

**Comment by lichao2018** [comment]
how to fix this.
gotoPage cannot re-render.

**Comment by buxiaoxia** [comment]
> how to fix this.
> gotoPage cannot re-render.

延迟300ms

**Comment by hz-sanaullah** [comment]
> Try this. It worked. Ideal for changing first pages.
> 
> componentDidMount() { setTimeout(() => this.scrollableTabView.goToPage(1), 300); } ... ..... ... <ScrollableTabView ref={(ref) => { this.scrollableTabView = ref; }}

Sounds weird but it'll even work fine if the delay is 0ms like this "setTimeout(() => this.scrollableTabView.goToPage(1), 0);" 😄
