### ISSUE TITLE
How to pass values/props to target page using goToPage()? [help wanted]

### ISSUE THREAD

**Issue by BalalRaza** [skv-headless/react-native-scrollable-tab-view#792]
@brentvatne can you please help me on this? I have four tabs. From the second one, I want to pass a 'filterBy' prop to the fourth tab, so that there I can read the prop and show filtered Results. Is it possible? Any instructions or suggestions would be of immense help.

**Comment by Susmitha-Bogala** [comment]
how to send props to target page using gotoPage()?
can you please me in that
