### ISSUE TITLE
RN 0.51 PropTypes error

### ISSUE THREAD

**Issue by guopeng1994** [skv-headless/react-native-scrollable-tab-view#815]
please add new RN version support !! Thanks~~~~

**Comment by guopeng1994** [comment]
maybe u guys should change the ES5 to ES6 , because the React and React Native Update is very frequent, u gays can try to make this be compatible with these versions

**Comment by whinc** [comment]
I had found the reason leading error above. 

the newest version 0.6.7 use 'PropTypes' from individual package 'prop-types', but another "newest version" 0.7.4 use 'React.PropTypes'. Here is a comparation bettwen [0.6.7](https://github.com/skv-headless/react-native-scrollable-tab-view/blob/v0.6.7/DefaultTabBar.js) and [0.7.4](https://github.com/skv-headless/react-native-scrollable-tab-view/blob/v0.7.4/DefaultTabBar.js)

![unnamed capture](https://user-images.githubusercontent.com/5096493/34759885-8c837762-f618-11e7-939b-0f672e23bc1d.png)
