### ISSUE TITLE
ScrollableTabView is undefined, likely forgot to export your component

### ISSUE THREAD

**Issue by denis-shostik** [skv-headless/react-native-scrollable-tab-view#852]
error on screenshot http://prntscr.com/io66e6
my versions
```
"react-native": "^0.51.0",
"react": "^16.2.0",
```
testing on simulator iPhone 8 - 11.2
I have installed     `"react-native-scrollable-tab-view": "^0.7.2",`
trying to run the code example
```
               import ScrollableTabView, { DefaultTabBar }       from 'react-native-scrollable-tab-view';
               
               <ScrollableTabView
                    style={{marginTop: 20, }}
                    initialPage={1}
                    renderTabBar={() => <DefaultTabBar />}
                >
                    <Text tabLabel='Tab #1'>My</Text>
                    <Text tabLabel='Tab #2'>favorite</Text>
                    <Text tabLabel='Tab #3'>project</Text>
                </ScrollableTabView>
```

I have checked that ScrollableTabView is equal to undefined

any idea?

**Comment by denis-shostik** [comment]
I want notice one important moment, I use typescript, and I have checked compiled code, and it's looks so http://prntscr.com/io69t4 you can see that theere is added required field, and because I get undefined, without the "required" field all works properly

**Comment by denis-shostik** [comment]
make following import and it will work
```
 import * as ScrollableTabView                     from 'react-native-scrollable-tab-view';
```

**Comment by jakabjack** [comment]
import * as ScrollableTabView   from 'react-native-scrollable-tab-view'; will result in typescript compilation error: JSX element type 'ScrollableTabView' does not have any construct or call signatures.
