### ISSUE TITLE
the try to resolve ListView or ScrollView outsider of react-native-scrollable-tab-view(Android)

### ISSUE THREAD

**Issue by fortunelly** [skv-headless/react-native-scrollable-tab-view#874]
First: we can add a accurate height to ListView or ScrollView.
 Second: wo can modifying the source code(index.js). In the 'renderScrollableContent' method, we can only return Animated.ScrollView to replace AnimatedViewPagerAndroid. if you use AnimatedViewPagerAndroid, you can't load the data for react-native-scrollable-tab-view. If you only use Animated.ScrollView, the data will load success. I don't know it would happen any other something, you can only attempt.

**Comment by afresh** [comment]
我遇到了相同的问题。请问你是怎么解决的？
I have the same problem. How do you solve it, please?
