### ISSUE TITLE
Run into exception in RN 0.56.

### ISSUE THREAD

**Issue by williams-voon** [skv-headless/react-native-scrollable-tab-view#908]
error: bundling failed: SyntaxError: /Users/apple/Documents/workspace/react-native/fzbdemo8/node_modules/react-native-scrollable-tab-view/SceneComponent.js: A trailing comma is not permitted after the rest element (9:32)

   7 | 
   8 | const SceneComponent = (Props) => {
>  9 |   const {shouldUpdated, ...props, } = Props;
     |                                 ^
  10 |   return <View {...props}>
  11 |       <StaticContainer shouldUpdate={shouldUpdated}>
  12 |         {props.children}

const {shouldUpdated, ...props, } = Props; 
should be changed to
const {shouldUpdated, ...props} = Props;

**Comment by hungdev** [comment]
/node_modules/react-native-scrollable-tab-view/SceneComponent.js
remove comma after ...props (line 9)

**Comment by WhoJave** [comment]
Any Solutions ?

**Comment by hungdev** [comment]
@WhoJave  run npm i -s https://github.com/happypancake/react-native-scrollable-tab-view.git to get fix code from master

**Comment by WhoJave** [comment]
@hungdev tkx Im trying now

**Comment by WhoJave** [comment]
@hungdev this command not working for me ,  any ideas ?

**Comment by hungdev** [comment]
@WhoJave remove node_modules first then run that command.

**Comment by WhoJave** [comment]
It seems OK ,tkx @hungdev

**Comment by LannyCodes** [comment]
@hungdev Thanks!
