### ISSUE TITLE
[Android] Locked param

### ISSUE THREAD

**Issue by skv-headless** [skv-headless/react-native-scrollable-tab-view#95]
As I know react native https://facebook.github.io/react-native/docs/viewpagerandroid.html doesn't support that option.

**Comment by kevinejohn** [comment]
Started working on this:

https://github.com/facebook/react-native/pull/5968

Needs to be tested and the documentation updated for react-native. Hope we can get this in there

**Comment by tugucci** [comment]
Hello @kevinejohn, any updates on Locked param? cheers

**Comment by KevinHu2014** [comment]
any updates?

**Comment by skv-headless** [comment]
look at progress here https://github.com/facebook/react-native/pull/5968

**Comment by kevinejohn** [comment]
@KevinHu2014 @tugucci I've done everything they've asked for. Just needs to be merged.

**Comment by shidhincr** [comment]
Good job @kevinejohn .. Waiting for this to get merged.
